osmandapp/OsmAnd

OsmAnd-java/src/net/osmand/osm/edit/Entity.java
OsmAnd-java/src/net/osmand/osm/io/NetworkUtils.java
OsmAnd/res/values/strings.xml
OsmAnd/res/xml/general_settings.xml
OsmAnd/src/net/osmand/plus/OsmandSettings.java
OsmAnd/src/net/osmand/plus/activities/SettingsGeneralActivity.java
OsmAnd/src/net/osmand/plus/download/DownloadFileHelper.java
OsmAnd/src/net/osmand/plus/download/DownloadOsmandIndexesHelper.java
OsmAnd/src/net/osmand/plus/download/DownloadTracker.java
OsmAnd/src/net/osmand/plus/osmedit/OpenstreetmapRemoteUtil.java
OsmAnd/src/net/osmand/plus/osmedit/OsmBugsRemoteUtil.java
OsmAnd/src/net/osmand/plus/poi/NameFinderPoiFilter.java
OsmAnd/src/net/osmand/plus/routing/RouteProvider.java
OsmAnd/src/net/osmand/plus/views/YandexTrafficAdapter.java

This pull request mostly is about adding support for an HTTP proxy for internet connections.  Some networks require proxies in order to access the internet from behind an firewall.  Proxies are also useful for circumvention and privacy tools.
This also changes some connections to use HTTPS (except on `android-9` where it is problematic).  Location-related internet traffic can contain a lot of private information, so it should be protected.
There is also a small fix of a leaked resource that wasn't being closed.

add support for a proxy and use more HTTPS

---

OsmAnd-java/src/net/osmand/util/GeoPointParserUtil.java
OsmAnd/AndroidManifest.xml

This pull request adds support for parsing more URLs:
* http://amap.com
* https://www.here.com
* http://map.qq.com
* http://maps.apple.com
* https://maps.yandex.com
* all Google map domains (e.g. https://www.google.at/maps, google.ru, google.es, etc.)
It also adds more tests including adding unparsable URLs to make sure the parsing does the right thing.  The last commit includes some valid Google Maps links that cause problems with the new `parseGoogleMapsPath()` method.  I didn't have time to fix `parseGoogleMapsPath()` though, and I couldn't really make senses of it either, so I'm just documenting the issues with that commit.

More url parsing updates

---

OsmAnd/src/net/osmand/plus/SQLiteTileSource.java

Add ellipsoid projection (Yandex). Use new optional field ELLIPSOID in table INFO. 1 means ellipsoid. If there is no field ELLIPSOID or its value differs from 1, used default spheroid projection.
I'm sorry but as I see ellipsoid is supported only in .metainfo. And now Yandex map cached in sqlitedb displayed incorrectly.

Add support for ellipsoid in sqlitedb

---

OsmAnd-java/src/net/osmand/map/TileSourceManager.java
OsmAnd/src/net/osmand/plus/SQLiteTileSource.java

Add beanshell use. Use new optional field RULE in table INFO. Value "beanshell" makes to use interpreter for processing of a script which put into the field URL. If there is no field RULE or its value differs from "beanshell", content of the field URL used as before.

Add beanshell use in SQLiteDB

---

OsmAnd/src/net/osmand/plus/SQLiteTileSource.java

Add beanshell use. Use new optional field RULE in table INFO. Value "beanshell" makes to use interpreter for processing of a script which put into the field URL. If there is no field RULE or its value differs from "beanshell", content of the field URL used as before.

Continue work on BeanShell in SQLiteDB

---

OsmAnd-java/src/net/osmand/map/MapTileDownloader.java
OsmAnd/src/net/osmand/plus/SQLiteTileSource.java
OsmAnd/src/net/osmand/plus/resources/AsyncLoadingThread.java
OsmAnd/src/net/osmand/plus/resources/ResourceManager.java

In case of SQLiteTileSource using:
Changed loading tiles into sqlitedb when using "Download map" from context menu. Before now in such cases tiles were saved in files in TEMP folder
Changed saving tiles directly into sqlitedb when browsing new area. Before now in such cases 
intermediate temp files were used.

Saving tiles into sqlitedb

---

OsmAnd-java/src/net/osmand/map/MapTileDownloader.java
OsmAnd-java/src/net/osmand/map/TileSourceManager.java
OsmAnd/src/net/osmand/plus/activities/ContributionVersionActivity.java
OsmAnd/src/net/osmand/plus/activities/search/SearchAddressOnlineFragment.java
OsmAnd/src/net/osmand/plus/osmedit/OsmBugsLayer.java
OsmAnd/src/net/osmand/plus/routing/RouteProvider.java

This keeps the code consistent, provides a single common method for setting
up URLConnections, and allows the proxy support to work on all network
connections.
NetworkUtils.getHttpURLConnection() provides a common method for creating
HttpUrlConnection instances from URLs.  That's where the proxy config
happens.  If you can think of a better way to add proxy support, I'm all
ears.  This is the best that we've found in our proxy work at Guardian
Project.
this is a follow up on https://github.com/osmandapp/osmand/pull/1043

use NetworkUtils.getHttpURLConnection for all URLConnections

---

OsmAnd-java/src/net/osmand/map/TileSourceManager.java
OsmAnd/src/net/osmand/plus/SQLiteTileSource.java

Add in urlTemplate support of variables {z}, {x} and {0} interpreted like {0}, {1} and {2}.
Before now these variables were supported in some cases. Now they are supported always in both .metainso and sqlitedb.
No support in beanshell!

Add in urlTemplate support of variables {z}, {x} and {0} interpreted like {0}, {1} and {2}

---

OsmAnd/src/net/osmand/plus/FavouritesDbHelper.java
OsmAnd/src/net/osmand/plus/dialogs/FavoriteDialogs.java

StringBuilder adds trailing null characters so that duplicate favourite names are never detected, because fp.getName().equals(name) always returns false.
Dialog was never shown, so that addFavorite() was never called, in case of duplicate favourite name.
Also setPositiveButton() was called twice.
https://code.google.com/p/osmand/issues/detail?id=2400

Fix duplicate favourites again (issue 2400)

---

OsmAnd/res/values/strings.xml

Move the comments before the strings to which they belond as otherwise Weblate system shows them for incorrect strings.

Move comments in strings.xml

---

OsmAnd/build.gradle
OsmAnd/build.xml

It seems that specialphrases were migrated to phrases.xml.

Don't copy unused specialphrases

---

OsmAnd/res/values-de/strings.xml
OsmAnd/res/values/strings.xml

"default" value was replaced with empty value [1], thus I also added translation for empty value "rendering_value__name".
[1] https://github.com/osmandapp/OsmAnd-resources/commit/cfa2123c0e97f786d59958a4c56e1f89fb4d4b02

Add road style translations

---

OsmAnd/res/values/phrases.xml
OsmAnd/res/values/strings.xml

"Accommodation" is frequently misspelt.
"Wintry" is the correct spelling of "wintery"--one of the many inconsistencies in English.

Fix some minor typos in English phrases

---

OsmAnd/res/values/colors.xml
OsmAnd/src/net/osmand/plus/activities/search/SearchPOIActivity.java

Currently only colors used in the POI dialog for opening hours: red and green. I introduced new orange color for POIs that are closing in 30 minutes or less - this way we can easily distinguish POIs that are still open when we travel to them. 
I am not practically sure about 30 minutes, but it should be ok for shops, pharmacies and other pois of such type. Not very useful for restaurants, as an example.

Orange color for POIs that are closed in 30 minutes from now

---

OsmAnd/res/values/strings.xml

each month we have users who cannot find places in offline address search because they do not press the button "search villages/postcode" because instant search has no result for smaller places.
see https://groups.google.com/forum/#!topic/osmand/IDm-pPb4IpI again.
So users need to know that this button does a further deeper search.
Alternatively add a text like "Press above button when place name is not found instantly."

Add "more" to "search villages/postcodes"

---

OsmAnd-java/src/net/osmand/osm/edit/EntityParser.java
OsmAnd-java/src/net/osmand/osm/edit/OSMSettings.java

In case when only one entrance is present it is nice to route user directly to that entrance. 
Logic: if only one main entrance is present - it's chosen. If only one entrance in a building - it's chosen. Otherwise, default behavior is using weighted center.

Use building entrance as a building location (handy for routing)

---

README.md

The title is only there because Github doesn't support title-less tables.

Use table for map coverage/quality in readme.

---

OsmAnd/res/values-de/strings.xml

Open can either be a verb (de: öffnen), an adjective (de: offen) or a
participle (de: geöffnet). At the place where this string is used
in the app ("Filter for open shops") it is used as the participle or
the adjective with the adjective form sounding less clunky.

fix german translation of "open"

---

OsmAnd/res/values-bg/strings.xml
OsmAnd/res/values-lt/strings.xml
OsmAnd/res/values-pt-rBR/strings.xml

When you set the language to Bulgarian and then you go to Manage map files (Управление на карти) the application crashes.

Fixed a crash due to errors in format strings

---

OsmAnd/src/net/osmand/plus/views/OsmAndMapLayersView.java
OsmAnd/src/net/osmand/plus/views/OsmAndMapSurfaceView.java
OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java

Behaviour should possibly be fine-tuned to use a
smooth instead of animated zooming and to keep
the cursor position as a fixed point instead of
moving it to the center.
Still, this should be a small improvement for usage
with mouse.

Support zooming via mouse wheel.

---

OsmAnd-java/build.gradle
OsmAnd-java/src/net/osmand/util/GeoPointParserUtil.java
OsmAnd/src/net/osmand/plus/activities/search/GeoIntentActivity.java

* OsmAnd-java/build.gradle
* modified gradle file for testing purposes
* GeoPointParserUtil.java
* created test for URL from issue #1486
* double parentheses and their content are now removed from URL
* GeoIntentActivity.java
* imports and tiny Javadoc fix

Double parentheses in URL fix

---

OsmAnd/res/layout/osm_edit_list_item.xml
OsmAnd/res/values/strings.xml
OsmAnd/src/net/osmand/plus/osmedit/DashOsmEditsFragment.java
OsmAnd/src/net/osmand/plus/osmedit/OpenstreetmapPoint.java
OsmAnd/src/net/osmand/plus/osmedit/OpenstreetmapRemoteUtil.java
OsmAnd/src/net/osmand/plus/osmedit/OsmBugsRemoteUtil.java
OsmAnd/src/net/osmand/plus/osmedit/OsmEditUploadListenerHelper.java
OsmAnd/src/net/osmand/plus/osmedit/OsmEditsFragment.java
OsmAnd/src/net/osmand/plus/osmedit/OsmEditsUploadListener.java
OsmAnd/src/net/osmand/plus/osmedit/OsmEditsUploadListenerHelper.java
OsmAnd/src/net/osmand/plus/osmedit/OsmNotesPoint.java
OsmAnd/src/net/osmand/plus/osmedit/OsmPoint.java
OsmAnd/src/net/osmand/plus/osmedit/UploadOpenstreetmapPointAsyncTask.java

Created dialog as a visual representation of unsuccessful upload of OSM edit operation. Issue #1291.
* Created default implementation of `OsmEditsUploadListener`
* DashOsmEditsFragment
* Removed implementation of `OsmEditsUploadListener` and replaced it with customized default
* OsmPoint now implements `Serializeble` implementation removed from subclasses.
* OpenstreetmapRemoteUtil
* Removed silly `if(true)` check. Made IOExecption message little bit more descriptive.
* OsmEditUploadListenerHelper new general implementation of `OsmEditsUploadListener`
* UploadingErrorDialogFragment - dialog if one item failed to load
* UploadingMultipleErrorDialogFragment - dialog if there were multiple items
* PointsWithErrorsAdapter - adapter for list items of UploadingMultipleErrorDialogFragment
* …

Dialog for issue #1291

---

OsmAnd/res/values/strings.xml
OsmAnd/src/net/osmand/plus/dashboard/tools/DashboardSettingsDialogFragment.java

The "show on start" string in dashboard configuration is hardcoded in DashboardSettingsDialogFragment.java.

"show on start" string not translatable

---

OsmAnd/res/values/strings.xml

Similar to #1712, remove "announce" prefix as it clutters the screen.

Remove "announce" prefix as well in "Announce..." menu

---

OsmAnd/res/values/strings.xml

It seems "favorite" (US spelling) is the more used variant in OsmAnd. GPX acronym should probably be used capitalized at all places.

Fix 'favourite' typos in strings.xml

---

OsmAnd/src/net/osmand/plus/development/TestVoiceActivity.java

I try to update sk/ttsconfig.p to support more of the existing features of voice commands. As there are several forms of plurals, I update the route times to be more different.
I still do not understand why in the phrase "onto 'Market Square'", the internal command is 'street(p,"", "", "Market Square")' (market square as 3rd argument to street()).
In the phrase "onto 'Bridge Avenue'" the internal command is 'street(p, "Bridge Avenue")' (Bridge avenue is first argument).
What is the difference? It seems to me the 2nd argument is road ref, first could be the street name. 3rd could be the destination (something a bit away, not current street/road). But these assumptions are not true at these commands, and also at the "onto 'SR 80'" (it looks like a ref, but is used in 1st argument). So what …

add more variants of times into testing voice commands

---

OsmAnd/res/values/strings.xml

Within the address search, there is no hint that the user can search for a postcode. Adding this text in the 'City' field (displayed when no input given) helps the user a lot.

Add 'or postcode' address search

---

OsmAnd/res/values/strings.xml
OsmAnd/src/net/osmand/plus/download/DownloadValidationManager.java

Currently, OsmAnd checks the free space against the cumulated size of the downloaded files.
This works well with new downloads, but results in irritating messages when downloading map updates.
Properly calculate the changed disk usage and max temp usage and show it to the user.
Don't allow the download if the free space will not be sufficient.

Properly calculate the disk usage change for downloads of updates, improve messages to user

---

OsmAnd-java/src/net/osmand/OsmAndCollator.java

Search without diacritics will work properly in Czech Republic, Slovakia or Romania only when phone UI is set to these languages.
This is temporary solution.This should be handled better.
Addition to bug: https://github.com/osmandapp/Osmand/issues/2193

support diacritics symbols also with czech language

---

OsmAnd/res/layout-land/search_by_name.xml
OsmAnd/res/layout-land/searchbyname_list.xml
OsmAnd/src/net/osmand/plus/activities/search/SearchByNameAbstractActivity.java

Avoid blocking of street list (during address search) in landscape mode with large soft-keyboard by changing imeOptions, thereby avoiding the "extracted text UI" issue.
!!! **This makes address search finally more usable on e.g. in-car head units** !!!
Additionally added minor layout changes to squeeze the street list in landscape mode (less line separator height and margin).

Address search in landscape mode fixed, no more "extracted text UI" issue

---

OsmAnd-java/src/net/osmand/router/RouteResultPreparation.java
OsmAnd-java/src/net/osmand/router/TurnType.java
OsmAnd-java/test/resources/test_turn_lanes.json

I don't like this solution because it's still limited. `TurnType` supports only 3 turn options. Here (https://www.openstreetmap.org/#map=19/55.71127/37.62080), for example, we have 4 different turn options, so I'm proposing to rewrite `TurnType` to support arbitrary number of turn options by using an `AbstractList` interface. What do you think?
Illustration of a bug:

Support three turn options for one segment in the result route description

---

OsmAnd/src/net/osmand/plus/GpxSelectionHelper.java
OsmAnd/src/net/osmand/plus/myplaces/AvailableGPXFragment.java

Before this change, GPX tracks are not shown in "My Tracks" in "My Places"
unless they have a lowercase .gpx extension.
Such tracks are still shown in "Configure map", "GPX track..." but the
extension isn't removed like it is for tracks with a lowercase extension.
This has been fixed too.

Fix #2484 - GPX tracks not shown unless extension is .gpx

---

OsmAnd/src/net/osmand/plus/routing/RouteProvider.java

The brouter navigation service was always ignoring any intermediate waypoints. This patch adds support by passing all intermediate waypoints to the brouter service.

Add support for intermediates in brouter navigation service

---

OsmAnd/src/net/osmand/plus/views/OsmandMapLayer.java

When a new segment of a path is drawn the first line was not drawn when the start coordinates were visible but the second set was not.
Screenshot with navigation path not being drawn:
Screenshot after fix:

Fix bug causing first segment of drawn path to be not drawn

---

OsmAnd/src/net/osmand/plus/widgets/InterceptorFrameLayout.java

listener might be null if plugin method isDismissAllowed return false.
See DashBaseFragment.java line 62. It will create the SwipeDismissListeneer only in case of value is true.

listener might be null

---

OsmAnd-java/src/net/osmand/binary/BinaryMapAddressReaderAdapter.java
OsmAnd-java/src/net/osmand/binary/BinaryMapIndexReader.java
OsmAnd-java/src/net/osmand/data/City.java
OsmAnd-java/src/net/osmand/data/Postcode.java
OsmAnd/src/net/osmand/plus/activities/search/SearchByNameAbstractActivity.java
OsmAnd/src/net/osmand/plus/activities/search/SearchCityByNameActivity.java
OsmAnd/src/net/osmand/plus/activities/search/SearchStreetByNameActivity.java
OsmAnd/src/net/osmand/plus/resources/RegionAddressRepository.java
OsmAnd/src/net/osmand/plus/resources/RegionAddressRepositoryBinary.java

Usability:
* Removed almost all magic constants (like search villages only if 3 letters are written).
* Search postcodes automatically if input looks like postcode.
* Search villages and postcodes if nothing was found.
* Made nearest cities in villages description consistent.
Speed:
Made cities search use only one loop.

Improve speed and usability of address search

---

OsmAnd/src/net/osmand/plus/mapcontextmenu/other/DestinationReachedMenuFragment.java

When reaching your destination in OsmAnd, the context menu shows a "find
parking" button to help you find a parking space. This might be useful if
you're driving (or using an application mode derived from car) but isn't
useful if you've just walked up to the top of a hill or you're cycling.
With this change, the button is shown only if you've reached the
destination by car (or a car-derived mode).

Only show "find parking" if destination is reached by car-derived modes

---

OsmAnd/build.gradle
plugins/Osmand-ParkingPlugin/build.gradle
plugins/Osmand-SRTMPlugin/build.gradle

On dependency changes in File -> Project structure... I get following errors (for 3 projects):
{% for project in ['Osmand', 'Osmand-SRTMPlugin', 'Osmand-ParkingPlugin'] %}
Module "{{ project }}"
must not contain source root
"~/osmand/android/plugins/{{ project }}/src".
The root already belongs to module "{{ project }}"
{% endfor %}
This is due duplicate lines in "{{ project }}.iml" file that is
generated based on "build.gradle" files.
This commit fixes this situation.

Fix idea dependency error.

---

OsmAnd/res/values-it/phrases.xml

In Italy there are not "Chemist" shops, the more similar
kind of shop is the "mesticheria", which sells various
goods for housekeeping and personal care.
Moreover: adding a "Farmacia" POI in OsmAnd should
insert amenity=pharmacy, not shop=chemist.

Changed Italian translation for poi_chemist.

---

OsmAnd/src/net/osmand/plus/GPXUtilities.java

GPX distinguishes between routes (where you should go) and tracks (where you've been).
OsmAnd can already use a colour specified in \<color\> in \<extensions\> for tracks, but not routes.
With this change, OsmAnd uses colour specified in GPX files for routes. This is very useful when viewing multiple routes or to emphasise a particular route.

Allow colours for GPX routes (not just tracks) to be specified in files

---

OsmAnd/src/net/osmand/plus/api/SQLiteAPIImpl.java

app.openOrCreateDatabase expects flags from android.content.Context
which are completely different

 Fix SQLite open flags

---

OsmAnd/src/net/osmand/plus/helpers/GpxImportHelper.java

Dear developers,
I moved the database cursor closing code outside the if block to fix the potential leak of empty database cursor (when moveToFirst() returns false). Issue #3135 
@vshcherb please let me know if there are any problems. Thanks!

fix database cursor leak in GpxImportHelper.java

---

OsmAnd/res/values/phrases.xml

There is no resource_cereal in poi_types.xml (only crop_cereal) and it is not documented on the wiki for what it means.

Remove resource_cereal from phrases.xml

---

OsmAnd/src/net/osmand/plus/render/RendererRegistry.java

After I upgraded to OsmAnd+ 2.5.3, I noticed that my custom rendering file could not be selected. I got this toast: "Exception occurred: renderer was not loaded". Several people on the [forum](https://groups.google.com/forum/#!topic/osmand/w9111YDV_r8) reported the same problem.
I couldn't see any exception in logcat, so I investigated in more detail. In src/net/osmand/plus/dialogs/ConfigureMapMenu.java I could see that the toast is generated if this code returns null:
```java
app.getRendererRegistry().getRenderer(renderer);
```
`getRenderer()` only returns null if the specified renderer cannot be found, or an exception occurs. I added some debug code and found that the specified renderer could not be found, so null was being returned here:
```java
if(!hasRender(name)){
return null;
}
``` …

Fix loading of custom rendering files containing dashes and underscores (regression)

---

OsmAnd/src/net/osmand/plus/activities/SavingTrackHelper.java

OsmAnd 2.5 introduced optional minimum precision for location when recording tracks. When enabled, track points are only recorded if the location accuracy at the time of sampling is within the minimum precision:
```java
float precision = settings.SAVE_TRACK_PRECISION.get();
if(precision > 0 && (!location.hasAccuracy() || location.getAccuracy() < precision)) {
record = false;
}
```
Logic in this code was inverted: points with accuracy below (i.e. within) the minimum precision were rejected, and points with accuracy above the minimum precision were incorrectly accepted. 
For example, if the minimum precision was set to 20 metres, all points with an accuracy under 20 metres were incorrectly rejected, because `location.hasAccuracy()` is true, `location.getAccuracy()` returns (say) 10, and 10 …

Fix incorrect minimum precision logic for track recording

---

OsmAnd/src/net/osmand/view/ExpandableButton.java
OsmAnd/src/net/osmand/view/ExpandableLinearLayout.java

Hi,
I am developing a tool to automatically refactor Android applications with the goal of improving energy efficiency.
This pull request has the changes generated while applying the rule "Recycle".
Some resources (e.g., ```Cursor``` instances) should be closed when they are no longer necessary. 
I have made a previous validation of the changes and they seem correct.
Please consider them and let me know if you agree with them.
Best,
Luis

Android automatic refactor - Recycle

---

OsmAnd-java/src/com/google/openlocationcode/OpenLocationCode.java
OsmAnd-java/src/net/osmand/LocationConvert.java
OsmAnd-java/src/net/osmand/search/core/SearchCoreFactory.java
OsmAnd/res/layout/search_advanced_coords.xml
OsmAnd/res/values/strings.xml
OsmAnd/src/net/osmand/data/PointDescription.java
OsmAnd/src/net/osmand/plus/activities/SettingsGeneralActivity.java
OsmAnd/src/net/osmand/plus/mapcontextmenu/MenuController.java
OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/AmenityMenuBuilder.java
OsmAnd/src/net/osmand/plus/osmedit/EditPOIMenuBuilder.java
OsmAnd/src/net/osmand/plus/search/QuickSearchCoordinatesFragment.java

Hello! I have implemented the [Open Location Code](http://openlocationcode.com) (OLC, Plus Code) support in OsmAnd. It has been requested in #2740.
Could you please review and accept it?
**What is added**
- Added OpenLocationCode classes from official repository. It contains only one unchanged java file.
- Show OLC in point descriptions along with latitude/longitude.
- Support OLC positions in full-text search. If a full OLC is typed, it is shown as a coordinate.
- Support OLC in advanced coordinate search. It is an additional search mode. Also it shows information about specified OLC and how large is represented area.
**What is missing**
- Only full OLC is supported.
- No localization yet
**Notes about full vs short OLC**
Example of full OLC: `849VCWC8+R9`.
Example of short OLC (local): …

Open Location Code support

---

OsmAnd/src/net/osmand/plus/activities/MapActivity.java

Apparently it was added once just for accessibility purposes,
but now in this context it causes some mess and confusion
rather than helps.

Removed zoom control by volume keys

---

OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java

I cannot imagine the reason these strings should be commented out for,
but not having the list properly initialized it is impossible to go
through the same route again hearing the announcements without force
reload.

Waypoints announcement initialization fix

---

OsmAnd/src/net/osmand/plus/activities/SavingTrackHelper.java

Previously, when selecting a custom colour for the current recording track, any new track segments after the first one were displayed in the default GPX colour, not the custom colour.

Display all segments of the current recording track in the same colour

---

OsmAnd/res/values/strings.xml
OsmAnd/src/net/osmand/plus/notifications/GpxNotification.java

Previously, the track recording notification displayed "Pause" when recording was paused. This was confusing because when recording, the notification also shows "Pause" to allow recording to be paused.
With this change, "Paused" (rather than "Pause") is shown in the notification when recording is paused.

Show paused state more clearly on track recording notification

---

README.md

In GitHub Flavored Markdown, a space is required between a heading marker (like ##) and the heading text. Fixed the "Some of the main features" heading so it gets rendered properly.
Includes a few other very small fixes.

Trivial formatting and style fixes for README.md

---

OsmAnd/src/net/osmand/plus/activities/ShowRouteInfoDialogFragment.java

When showing the elevation details, we need to distinguish between the user arriving by the dashboard or the route info menu. Only in the latter case the menu needs to be closed.

Fixes #3617.

---

OsmAnd-java/build.gradle

On Windows 10 x64 Russian with Java 8.0.1210.13 compiler uses cyrillic encoding "cp1251" by default. That's why gradle fails with error
```
Validating translations
Incremental java compilation is an incubating feature.
:OsmAnd-java:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.7
E:\projects\Android\osmand_project\osmandapp\android\OsmAnd-java\src\net\osmand\data\MapObject.java:26: error: unmappable character for encoding Cp1251
* Looks like: {ru=ÐœÐ¾ÑÐºÐ²Ð°, dz=à½?à½¼à½¦à½²à¼‹à½€à½¼...} and does not contain values of OSM tags "name" and "name:en",
^
E:\projects\Android\osmand_project\osmandapp\android\OsmAnd-java\src\net\osmand\Reshaper.java:98: error: unmappable character for encoding Cp1251
String s = "Ú¯Ú† Ù¾Ú? Ù†Ù…Ú©ÛŒ Ø¨Ø§Ù„Ù„ØºØ© …
```

Added explicit encoding for Java source code

---

OsmAnd/src/net/osmand/plus/AppInitializer.java

Currently, after the update (in my case to 2.6.2), a click on "More infos" still opens the detailed 2.5 description in the browser.

update link to latest version

---

OsmAnd/src/net/osmand/plus/activities/actions/StartGPSStatus.java

It provides a replacement for the removed "sleep mode".
While the GPS status apps might be the obvious thing
to show here for new users, none of them being a replacement
for the previous functionality is annoying and confusing
to existing users.
Note: I don't have a working compilation setup to actually test this, sorry!

Add "GPS Connected" app to GPS status app list.

---

OsmAnd/src/net/osmand/plus/osmedit/EditPoiDialogFragment.java

In v2.6.3, Osmand would keep complaining about too many capital letters in a name when using any script that doesn't distinguish between upper- and lowercase such as the CJK family, Arabic, Thai/Lao etc.
This is because the `Character.toUpperCase(c) != c` test could never be true for those scripts so all characters were classified as uppercase. The builtin Character.isUpperCase() handles this correctly and is much clearer, too.

fix testTooManyCapitalLetters wrt unicameral scripts

---

OsmAnd/res/values/strings.xml
OsmAnd/src/net/osmand/plus/OsmandSettings.java
OsmAnd/src/net/osmand/plus/activities/SavingTrackHelper.java
OsmAnd/src/net/osmand/plus/monitoring/SettingsMonitoringActivity.java

I use OsmAnd's track recording extensively and have over 200 recorded tracks saved. Managing them is inconvenient as they are all displayed in a single, flat list.
With this feature, recorded GPX tracks can optionally be automatically stored in monthly directories. For example, GPX tracks recorded in July 2017 will be stored in rec/2017-07. This makes tracks much easier to
manage.

Optionally store recorded GPX tracks in monthly directories

---

OsmAnd/res/values/strings.xml

Pink is one of the least used colours on the map, making it a good choice for clearly showing GPX tracks. Pink was previously available in OsmAnd 2.5 but removed in 2.6.
**This requires the corresponding [OsmAnd-resources pull request](https://github.com/osmandapp/OsmAnd-resources/pull/443).**

Add support for showing GPX tracks in pink

---

OsmAnd/src/net/osmand/plus/views/GPXLayer.java

Previously, if a track contained multiple segments, split distance/time markers were drawn for *each* segment, including the overview segment produced by OsmAnd.
This meant that many duplicate labels were shown, cluttering the display and making the split markers useless. For example, given a track with two segments of 6 km each, and a 1 km split interval, two 1 km markers are shown: one for the first segment and one for the second segment.
Now splits are only shown for the overview segment, making the display clear and usable.
Please merge this into r2.7 as well :)

Fix drawing splits for tracks with multiple segments

---

OsmAnd/src/net/osmand/data/FavouritePoint.java
OsmAnd/src/net/osmand/plus/helpers/GpxImportHelper.java

When importing as favourites the color was not being passed through.
Override equals and hashcode in FavouritePoint to allow deleteFavourite to work correctly. This prevents duplicates if the same gpx file is imported more than once.

Fix favorite import issues

---

README.md

According to https://github.com/osmandapp/Osmand/issues/4329#issuecomment-324415127 (and others) F-Droid is not an official publication target and not supported by this repository.  The F-Droid badge gives the impression it is official so removing the badge helps to clarify this misconception.

Remove "Get it on F-Droid" from README

---

OsmAnd/src/net/osmand/plus/monitoring/LiveMonitoringHelper.java

Any http response code 2xx indicates success.
Actually we should expect that server replies with "201 Created" (check https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html for details) after storing proposed data point.
Alleviates #4472 
-----
I have not tried building OsmAnd with this change but it's pretty trivial and I expect it to work. Though pay attention, I don't know Java.

All 2xx responses as success in Online Tracking

---

OsmAnd-java/src/net/osmand/osm/MapRenderingTypes.java

A trivial little change that would make my life a lot easier: add the ISO-639-1 code for Lao

add Lao language code

---

OsmAnd/src/net/osmand/plus/activities/SavingTrackHelper.java

(Fixes the other part of #4895 not fixed in de4d697)
When a setting is enabled, OsmAnd saves recorded tracks to monthly directories. For example, all tracks recorded in January 2018 are saved to a directory named 2018-01, tracks recorded in February 2018 are saved to 2018-02, and so on.
Previously, the UTC time of the first track point was to determine the monthly directory to use, but the local time of the first track point was used to determine the track filename.
This meant that if OsmAnd was running on a device with a time zone ahead of UTC, at the start of a month, a track could be saved in the previous month's directory, but with the new month in the filename, causing confusion.
For example, suppose OsmAnd is running on a phone whose time zone is set to UTC+0300. A user starts …

Save recorded tracks to correct month directories

---

OsmAnd/src/net/osmand/plus/measurementtool/MeasurementEditingContext.java

This check helps us avoid writing intermediate points with no elevation to gpx file

added check for elevation

---

OsmAnd/res/values/strings.xml

"Knots" sounds more naturally to those who use nautical miles. "Kn" is the ISO standard for the short form (ISO 80000-3).

Changed nmi/h to kn

---

OsmAnd/AndroidManifest.xml

Currently Osmand intercepts media button and then ignores it. This change allows a music player to keep the media button focus.
I'm commenting out the MEDIA_BUTTON as there is bunch of commented out code in the listener class. We may want to simply delete the code, but that is for another pull request.

Fix #5358: Do not intercept media button

---

OsmAnd/res/values/strings.xml

Commits e14d7518 and 554e433c changed many English strings. Many of the changes (use of active voice, clearer phrasing, some simplification) were good, but others introduced unusual style, inconsistencies in the UI, and strange language.
Some examples:
* import_gpx_file_description: was "can be imported as Favorites, or as track file.", changed to "can be imported as favorite, or track file.". The new phrase doesn't take into account that OsmAnd has a concept or feature called "Favorites", so when referring to that, an initial capital letter should be used, and that a track can have many waypoints, so it's more appropriate to use "Favorites" (plural).
* Several strings containing colons have been changed such that the initial letter of the word immediately following the colon is in …

English string correctness, typo and style fixes

---

OsmAnd-java/build.gradle

At my PC java compiler use codepage CP1251 by default and fails to compile file OsmAnd-java/src/main/java/net/osmand/data/MapObject.java because in line 26 because there are some unicode symbols.
To fix compilation errors I've added UTF8 encoding configuration to Osmand-java/build.gradle file

Added explicit Java source encoding

---

OsmAnd/src/net/osmand/plus/activities/MapActivityActions.java
OsmAnd/src/net/osmand/plus/activities/ShowRouteInfoDialogFragment.java
OsmAnd/src/net/osmand/plus/measurementtool/MeasurementToolFragment.java
OsmAnd/src/net/osmand/plus/routing/RouteProvider.java
OsmAnd/src/net/osmand/plus/routing/RoutingHelper.java

When saving the current route as new gpx-file the containing track and route-elements do not have a name-element. That might cause trouble when opening the gpx-file with other soft- or hardware (e.g. a Garmin eTrex-device will ignore the filename of the gpx-file and list the track as empty string).
This pull request does:
- set the name-element of track and route to the filename entered (without the '.gpx' suffix) when saving the current route as new gpx-file.
- As when sharing the current route no filename is given (it defaults to 'route.gpx') the track within the shared gpx-file gets a name created from the current timestamp.
- When saving a route being newly created with the measurment-tool the entered filename is also being used as track-name.

Add name element to track and route when saving gpx-files

---

OsmAnd/src/net/osmand/plus/monitoring/DashTrackFragment.java

Set the totalCount to 10 as this is the max number of rows available in settings.
The actual list is limited to the value defined in settings by DashboardOnMap.handleNumberOfRows.

Fix for #6002, number of tracks from disk on dashboard limited to 3

---

OsmAnd/res/values/phrases.xml

E.g. from "bump" to "speed bump"
or from "table" to "speed table".
Sure, "bump" and "hump" may be clear to some, but "table" isn't very clear. "speed table" much more clear
(Note this is my first pull request ever, I may have made mistakes, e.g. more files need to be editied)

Update traffic calming names

---

OsmAnd/src/net/osmand/plus/OsmAndAppCustomization.java

download.osmand.net is accessible via https. Please consider using https for index file downloading.

Use https when downloading index file

---

OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/AmenityMenuBuilder.java

Fixing empty prefixes/values for amenity fields

Fixing empty prefixes/values for amenities' fields.

---

OsmAnd/src/net/osmand/plus/views/MapQuickActionLayer.java

This should fix #6508 and the duplicated issue #6624. The regression happened in 713a3b9.
The `setLayer` method with the false parameter call the method `quitMovingMarker` https://github.com/osmandapp/Osmand/blob/e1392212dbd36ecc3ed8b37b861e51b7cbcd0fe7/OsmAnd/src/net/osmand/plus/views/MapQuickActionLayer.java#L219 which seems to do magic things with the center of the map.
I don't know the reason behind the initial change. Any hints @MadWasp79?

Fix the resulting position when using a quick action.

---

OsmAnd/src/net/osmand/plus/activities/MapActivity.java

Now instead of "Shared location" in Search history will be shown every shared lat/lon

Issue #6651 - Shared location in search history wrong - fixed

---

OsmAnd-java/src/test/java/net/osmand/util/OpeningHoursParserTest.java

As the source code has changed too much, the previous pull request from ntruchsess no longer works. I simply redid ntruchsess' changes

REDO: avoid test failing on non en-US default-locale (#6106)

---

OsmAnd/res/values/strings.xml

The string 'commiting_way' seems unused, is not referenced in Java code of any OsmAnd repository.
People do not know how to translate it (what the context is), and nobody replies to them at https://hosted.weblate.org/translate/osmand/main/sk/?type=nottranslated&offset=2#comments . Please check the string and remove it if it really isn't needed.

Remove 'commiting_way' from strings.xml

---

OsmAnd/src/net/osmand/plus/routing/RouteProvider.java

Some versions of BRouter can't read the favorites with nogo circles for BRouter anymore.  With this commit the avoid roads points are send as nogo circles with 10 meter radius.

avoid roads for BRouter

---

OsmAnd/src/net/osmand/aidl/IOsmAndAidlInterface.aidl
OsmAnd/src/net/osmand/aidl/OsmandAidlApi.java
OsmAnd/src/net/osmand/aidl/OsmandAidlService.java
OsmAnd/src/net/osmand/aidl/mapmarker/RemoveMapMarkerParams.java
OsmAnd/src/net/osmand/aidl/mapmarker/UpdateMapMarkerParams.java

- introduction of an option to ignore coordinates in updateMapMarker and removeMapMarker AIDL functions; default behaviour is that marker name and coordinates have to match for update/remove functions. The new option allows to ignore the coordinate values, so only the name has to match.
- added new AIDL function removeAllMarkers which removes all map markers

AIDL updates updateMapMarker, removeMapMarker, removeAllMarkers

---

OsmAnd/src/net/osmand/plus/routing/RouteProvider.java

The Android intent interface that is used to call the BRouter-Service has a limit of 1 MB for the request and response data.
The returned GPX exceeds that limit typically for a 200km GPX in bike-mode.
In order to workaround that limit, this patch adds a compression option for that interface, allowing 5 times longer routes to be transfered via the service interface.
Compression is negotiated between both parties, so this patch is up- und downward compatible.

add compression option for service calls to BRouter

---

OsmAnd/src/net/osmand/plus/OsmandSettings.java
OsmAnd/src/net/osmand/plus/activities/SettingsNavigationActivity.java
OsmAnd/src/net/osmand/plus/voice/MediaCommandPlayerImpl.java
OsmAnd/src/net/osmand/plus/voice/TTSCommandPlayerImpl.java

Tested to work on Android 6, not yet 8 or 9.
This should replace the `setAudioStreamType`, while replacing the also deprecated `requestAudioFocus (AudioManager.OnAudioFocusChangeListener l, int streamType, int durationHint)` and `abandonAudioFocus` is still open.

Replace deprecated setAudioStreamType

---

OsmAnd/src/net/osmand/plus/routepreparationmenu/RouteOptionsBottomSheet.java

Fix "Directions->Options->GPX route" theme of this popup was switching only after restart app.

Fix "GPX route" theme of popup is switching immediately

---

OsmAnd/src/net/osmand/plus/routing/RouteCalculationResult.java

When evaluating direction from segments, algorithm attempts to detect name of the street that follows turn by examining several segments.

Fix #8476 Missing some street names in the detailed route

---

OsmAnd-java/src/main/java/net/osmand/binary/BinaryMapDataObject.java

Exception was caused by additionalTypes being null.
Occurred consistently after zooming out some steps.
**Solution**
Check that additionalTypes is not null before accessing it.
**Details**
A `rendering_exception` was caught in
```
net/osmand/plus/render/MapRenderRepositories.java:830
java.lang.NullPointerException: Attempt to get length of null array
```
Putting a breakpoint there revealed:
```
e = {NullPointerException@6117} "java.lang.NullPointerException: Attempt to get length of null array"
backtrace = {Object[15]@6193} 
cause = {NullPointerException@6117} "java.lang.NullPointerException: Attempt to get length of null array"
detailMessage = "Attempt to get length of null array"
stackTrace = {StackTraceElement[14]@6197} 
0 = {StackTraceElement@6204} …
```

Fix rendering_exception leading to "Could not draw chosen area"

---

OsmAnd-java/src/main/java/net/osmand/router/BinaryRoutePlanner.java
OsmAnd-java/src/main/java/net/osmand/router/RoutingConfiguration.java
OsmAnd-java/src/main/java/net/osmand/router/RoutingContext.java

Otherwise it overflows to a negative value and gives
out of memory errors if set to 2GB or higher.

Change memoryLimitation variable to long.

---

OsmAnd/res/values-cs/strings.xml
OsmAnd/res/values-de/strings.xml
OsmAnd/res/values-es/strings.xml
OsmAnd/res/values-fr/strings.xml
OsmAnd/res/values-it/strings.xml
OsmAnd/res/values-pl/strings.xml
OsmAnd/res/values-sk/strings.xml

Fix a few translations of modified strings `gpx_monitoring_start` and `gpx_monitoring_stop` changed in 
https://github.com/osmandapp/Osmand/commit/75b8b0de3a69e429f850aa0e60be17192c909eba

Fix cs/de/es/fr/it/pl/sk translations of pause/resume

---

OsmAnd/res/values-cs/strings.xml
OsmAnd/res/values-de/strings.xml
OsmAnd/res/values-es/strings.xml
OsmAnd/res/values-fr/strings.xml
OsmAnd/res/values-it/strings.xml
OsmAnd/res/values-pl/strings.xml
OsmAnd/res/values-sk/strings.xml

Add cs/de/es/fr/it/pl/sk translations of `shared_string_resume` to #8945

Add cs/de/es/fr/it/pl/sk translations of shared_string_resume

---

OsmAnd/src/net/osmand/plus/poi/PoiFiltersHelper.java

Test if there is a translation for the filter name and use it. 
It allows to use standard names in custom packages so that translation can be done automatically.

CHANGE: enable translation on filter names from a custom package

---

OsmAnd-api/src/net/osmand/aidlapi/map/SetMapLocationParams.java
OsmAnd-telegram/src/net/osmand/aidl/map/SetMapLocationParams.java
OsmAnd/src/net/osmand/aidl/OsmandAidlApi.java
OsmAnd/src/net/osmand/aidl/OsmandAidlService.java
OsmAnd/src/net/osmand/aidl/OsmandAidlServiceV2.java
OsmAnd/src/net/osmand/aidl/map/SetMapLocationParams.java

Added a rotation parameter to setMapLocation.
I think it's better to have it before animated parameter, but if you prefer to put it at the end I can do it.
I also added a  SetMapLocationParams constructor without rotation for backward compatibility

Add rotation to setMapLocation API

---

OsmAnd/src/net/osmand/plus/activities/MapActivityKeyListener.java

Looks like a recent change to handle onKeyUp and onKeyDown produces duplicate input with External Input Device.  This is a quick fix.

Fix external device keypresses

---

OsmAnd/src/net/osmand/AndroidUtils.java
OsmAnd/src/net/osmand/plus/activities/FavoritesSearchFragment.java
OsmAnd/src/net/osmand/plus/dialogs/FavoriteDialogs.java
OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/EditCategoryDialogFragment.java
OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/PointEditorFragment.java
OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/PointEditorFragmentNew.java
OsmAnd/src/net/osmand/plus/mapmarkers/CoordinateInputDialogFragment.java
OsmAnd/src/net/osmand/plus/osmedit/EditPoiDialogFragment.java
OsmAnd/src/net/osmand/plus/osmedit/OsmBugsLayer.java
OsmAnd/src/net/osmand/plus/search/QuickSearchCustomPoiFragment.java
OsmAnd/src/net/osmand/plus/search/QuickSearchDialogFragment.java
OsmAnd/src/net/osmand/plus/search/QuickSearchSubCategoriesFragment.java
OsmAnd/src/net/osmand/plus/settings/fragments/ProfileAppearanceFragment.java

Ask to unlock device if it requires keyboard interaction while in FLAG_SHOW_WHEN_LOCKED mode.
It's usefull while hicking with "Turn screen on: Power button" enabled and one wants to add a Poi or search something.
Without  it the keyboard won't show, and the user need to put osmand in backgrund, unlock the screen and put osmand in foreground again in order to interact

Fix: ask to unlock device if it requires keyboard interaction while locked

---

OsmAnd-java/src/main/java/net/osmand/map/ITileSource.java
OsmAnd-java/src/main/java/net/osmand/map/MapTileDownloader.java
OsmAnd-java/src/main/java/net/osmand/map/TileSourceManager.java
OsmAnd/src/net/osmand/plus/SQLiteTileSource.java
OsmAnd/src/net/osmand/plus/resources/AsyncLoadingThread.java
OsmAnd/src/net/osmand/plus/resources/TilesCache.java
OsmAnd/src/net/osmand/plus/settings/backend/SettingsHelper.java

This PR allows you to use a custom "User-Agent" for tile request, instead of the default one. Like "Referer", this parameter is optional in both SQLite and MetaInfo formats. Btw, this PR also loads `referer` parameter from MetaInfo.

Allow custom "user-agent" for tile download

---

OsmAnd/res/values/phrases.xml

recycling:small_electrical_applicances is documented in https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling and it's a bit more precise than just recycling:small_appliances.
recycling:small_electrical_applicances gets more and more used when people want to add the information that there is the possibility to recycle these things.

added recycling:small_electrical_appliances

---

OsmAnd-java/src/main/java/net/osmand/router/RoutePlannerFrontEnd.java
OsmAnd/src/net/osmand/plus/routing/GpxApproximator.java

When a user starts "route between points"  and switches profiles in "plan a route" the calculations might not stop.

Plan a route executor multiple calculations bug fix

---

OsmAnd/AndroidManifest.xml

The whole "handle import" plumbing is already in place to handle both file:// and content:// URIs for OBF files.  The `ObfImportTask` gets an `InputStream` from the `ContentResolver` already.  `handleContentImport` defers to the `handleFileImport` for which helper to instantiate.  Supporting content:// URIs here means this import can happen via `FileProvider` and other `ContentProvider` instances.
My use case is offline sharing of OBF files as handled by F-Droid Nearby Swap.  Users can select which installed OBF files to share, then nearby users can connect to the device via Bluetooth or local WiFi to get the files.

support incoming content:// URIs pointing to OBF files

---

OsmAnd/res/values/phrases.xml

The poi_motorcar_yes string is missing "yes" after colon, inconsistently to other access strings. I also checked that it is simply displayed as "Motorcar access:" in the app, without any yes/no/other value attached.

Fix poi_motorcar_yes in phrases.xml

---

OsmAnd-java/src/main/java/net/osmand/GPXUtilities.java

this fixes #1326 and #10209 and conflicts with #10526
I could also import a file created with this changes to BaseCamp without modification and I could verify correct XML syntax with `SAXCount`.

fix #1326 and #10209 by adding the XML namespace 'osmand' to the header and the writeExtensions function

---

OsmAnd-java/src/main/java/net/osmand/GPXUtilities.java
OsmAnd-java/src/main/java/net/osmand/binary/StringBundleWriter.java

I had to change the order in which wpt, rte and trk was written into the gpx files to comply to the gpx 1.1 standard.
I did test examples of both type of gpx files with BaseCamp and could successfully import them.

Add BaseCamp compatibility for planned Tracks and claculated routes exported to gpx

---

OsmAnd/src/net/osmand/plus/settings/backend/ApplicationMode.java
OsmAnd/src/net/osmand/plus/settings/fragments/ConfigureProfileFragment.java

https://github.com/osmandapp/OsmAnd-Issues/issues/399
video:
https://www.dropbox.com/s/s4butfyozb566n7/Screen%20Recording%202021-02-19%20at%2011.00.43.mov?dl=0
test osf file:
https://www.dropbox.com/s/vl0kvd5c18mhrqf/trucktest.osf?dl=0
ios pr:
https://github.com/osmandapp/OsmAnd-iOS/pull/1092

fix empty profile name on main settings screen

---

OsmAnd/src/net/osmand/plus/helpers/kml2gpx.xslt

[KML](https://developers.google.com/kml/documentation/kmlreference#gxtrack) allows empty gx:coord elements and [OpenTracks](https://github.com/OpenTracksApp/OpenTracks) has started to use them. Currently, kml2gpx.xslt creates trkpt elements with empty lon and lat attributes, which are later interpreted as 0. This pull request adds an xsl:if conditional to kml2gpx.xslt so that empty gx:coord elements are omitted from the GPX output.
```xml
<trkpt lon="" lat="">
<time>2021-03-02T09:30:40.993Z</time>
</trkpt>
```

Ignore empty gx:coord elements in kml files

---

OsmAnd-java/src/main/java/net/osmand/binary/GeocodingUtilities.java

Added finding buildings on the next street if on the prevous was not found any.
Code will not have influence on street geocoding, building only.

Fix reverse geocoding for building only

---

OsmAnd/res/values/strings.xml

Add probably missing space after "Next time" that all translators have added into their localized strings.

Fix space after "Next time" in strings.xml

---

OsmAnd/src/net/osmand/plus/settings/backend/ApplicationMode.java
OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java

After import a file that contains only global settings (no profiles), empty profiles with a name (string key + "_" + milliseconds) are created, as in this screenshot:

Fix import nonexistent application modes

---

.github/FUNDING.yml

Since I was looking for the funding links myself, this is my humble effort to make it easier for other to support this wonderful project ❤️ 
This will require an admin to enable the repos funding feature, see [GitHub's funding docs](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository).
_Sidenote: It would be possible to also add the App Store links here, to allow users to quickly find them._

Add GitHub funding link to official OsmAnd FAQ

---

OsmAnd/src/net/osmand/plus/parkingpoint/ParkingPositionPlugin.java
gradle.properties

https://github.com/osmandapp/OsmAnd-iOS/issues/1309
Without this line parking point is always exported with default time:
<time>1969-12-31T23:59:59Z</time>

fix export parking with time in osf

---

OsmAnd/src/net/osmand/plus/OsmAndFormatter.java

While fixing #12573 I found the bug, that no total duration is rendered, if the route duration is < 1 minute. This PR fixes this issue by formatting times < 60 seconds as `<1 min`. The alternative would be to render this as `… sec`.
Compare the two screenshots:

fix formatting of durations < 1 minute

---

.github/ISSUE_TEMPLATE/3-routing-report.md
OsmAnd/res/values-ar/strings.xml
OsmAnd/res/values-b+ast/strings.xml
OsmAnd/res/values-cs/strings.xml
OsmAnd/res/values-da/strings.xml
OsmAnd/res/values-de/strings.xml
OsmAnd/res/values-eo/strings.xml
OsmAnd/res/values-es-rAR/strings.xml
OsmAnd/res/values-es-rUS/strings.xml
OsmAnd/res/values-et/strings.xml
OsmAnd/res/values-fa/strings.xml
OsmAnd/res/values-fi/strings.xml
OsmAnd/res/values-fr/strings.xml
OsmAnd/res/values-hu/strings.xml
OsmAnd/res/values-it/strings.xml
OsmAnd/res/values-iw/strings.xml
OsmAnd/res/values-ja/strings.xml
OsmAnd/res/values-nb/strings.xml
OsmAnd/res/values-pl/strings.xml
OsmAnd/res/values-pt-rBR/strings.xml
OsmAnd/res/values-pt/strings.xml
OsmAnd/res/values-ro/strings.xml
OsmAnd/res/values-ru/strings.xml
OsmAnd/res/values-sc/strings.xml
OsmAnd/res/values-sk/strings.xml
OsmAnd/res/values-tr/strings.xml
OsmAnd/res/values-uk/strings.xml
OsmAnd/res/values-zh-rTW/strings.xml
OsmAnd/res/values/strings.xml
OsmAnd/src/net/osmand/plus/onlinerouting/engine/OrsEngine.java

This PR fixes the implementation of [openrouteservice](https://openrouteservice.org) into OSMAnd. The issue was brough up initially in the openrouteservice ask forum: https://ask.openrouteservice.org/t/osmand-route-is-empty/3088
* **OrsEngine.java**: `parseServerResponse` returns the `OnlineRoutingResponse` object and not `null`
* **OrsEngine.java**: `parseServerResponse` adds basic directions to the `OnlineRoutingResponse` object
* **OsmAnd/res/values\*/strings.xml**: change the spelling of `OpenRouteService` to `openrouteservice`
* **.github/ISSUE_TEMPLATE/3-routing-report.md**: change the spelling of `OpenRouteService` to `openrouteservice`
closes #12568

Fix integration of openrouteservice in OSMAnd

---

OsmAnd/AndroidManifest.xml

Tested with gradle settings: "compileSdkVersion 30" and "targetSdkVersion 30"
Without \<queries\> tag in manifest TTS doesn't work

Fix #12038 manifest TTS declaration when targeting Android 11

---

OsmAnd/src/net/osmand/AndroidUtils.java

The compatibility code would do the block count * block size
multiplication using int, which meant it would overflow if the
total size is above 2GB, leading to errors claiming negative
space available and refusing to download.
Add explicit cast to long to avoid the overflow.

Avoid integer overflow in disk space calculation.

---

OsmAnd/res/values/sizes.xml
OsmAnd/res/values/styles.xml

Created styles for basic text appearances: title, description, small description.
* TitleStyle
* DescStyle
* SmallDescStyle
By default each style uses "regular" font family. To use "medium" add ".Medium" extension to text style name:
* TitleStyle.Medium
* DescStyle.Medium
* SmallDescStyle.Medium
To apply style for a specific TextView, use TextViewEx and tag "style".
Don't use tag "textAppearance". It loses font family and line height parameters.

Add basic text styles

---

OsmAnd/src/net/osmand/plus/myplaces/FavouritesDbHelper.java

The app had problems when e.g. importing large amount of favourites data or when deleting a favourite point. The app froze for several seconds when saving the changes.
I observed almost all the time being spent in the backup method.
After this change, with my test data, I observed decrease of method run time from 8300 ms to 700 ms.

Improved performance of the backup method

---

OsmAnd/src/net/osmand/plus/wikimedia/WikiImageHelper.java

These changes aim to resolve the problem reported in https://github.com/osmandapp/OsmAnd/issues/12765 by using [Wikimedia Commons hotlinking](https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia/technical#Hotlinking)
Take for exampled [File:Il Monumento a Francesco Baracca - Lugo - 3.tif](https://commons.wikimedia.org/wiki/File:Il_Monumento_a_Francesco_Baracca_-_Lugo_-_3.tif) which as shown in the issue is not represented correctly in the current version of OsmAnd.
This is how this image and it's thumbnail would be fetched before and after these changes:
| Description | URL | Actual URL (redirects to) | Visualization |
| --- | --- | --- | --- |
| **Image** link **before** changes | https://upload.wikimedia.org/wikipedia/commons/4/47/Il_Monumento_a_Francesco_Baracca_ …

Fix Wikimedia Commons TIFF image visualization

---

OsmAnd/src/net/osmand/plus/helpers/LocaleHelper.java

This change adds support for scripts in locales, that is - ability to parse scripts (as in `sr_RS+Latn` or `sr+Latn`), sets them in locales and make sure they are applied in `setLanguage`. This will fix problem when loading language with different script (currently, only `sr+Latn` as explained in #12940).
Creation of Locales is changed to use `Locale.Builder`. 
Tested with different languages, different system locales, tested also with different countries (e.g. `pt` vs `pt_BR`) - everything works as expected.

Add support for scripts in locales, fixes #12940

---

.github/ISSUE_TEMPLATE/2-bug-report.md
.github/ISSUE_TEMPLATE/3-routing-report.md
.github/ISSUE_TEMPLATE/4-feature-request.md

Issue templates have inconsistent emoji use in the name fields.
For example, `1-support-request` has emoji but the others have Unicode numbers for the emojis.
This PR replaces the Unicode numbers with emojis.

Replace unicode characters with emojis

---

OsmAnd-api/src/net/osmand/aidlapi/IOsmAndAidlCallback.aidl
OsmAnd-api/src/net/osmand/aidlapi/IOsmAndAidlInterface.aidl
OsmAnd-api/src/net/osmand/aidlapi/logcat/ALogcatListenerParams.aidl
OsmAnd-api/src/net/osmand/aidlapi/logcat/ALogcatListenerParams.java
OsmAnd-api/src/net/osmand/aidlapi/logcat/OnLogcatMessageParams.aidl
OsmAnd-api/src/net/osmand/aidlapi/logcat/OnLogcatMessageParams.java
OsmAnd-api/src/net/osmand/aidlapi/navigation/OnVoiceNavigationParams.java
OsmAnd/src/net/osmand/aidl/OsmandAidlApi.java
OsmAnd/src/net/osmand/aidl/OsmandAidlServiceV2.java
OsmAnd/src/net/osmand/plus/plugins/development/BaseLogcatActivity.java
OsmAnd/src/net/osmand/plus/plugins/development/LogcatAsyncTask.java
OsmAnd/src/net/osmand/plus/plugins/development/LogcatMessageListener.java

Add ability to receive OsmAnd logs by AIDL.
To receive callback with logs, AIDL user should register callback and put logs type he wants to receive. Logs type must be one of the values below:
- "D" (for _debug_ messages)
- "I" (for _info_ messages)
- "W" (for _warn_ messages)
- "E" (for _error_ messages)
Logcat logs will come through appropriate method of IOsmAndAidlCallback interface.

Rescue Track: Retrieve Logs API

---

OsmAnd/res/values/phrases.xml

Based on the [OSM wiki](https://wiki.openstreetmap.org/wiki/Key:traffic_signals:sound):
> **traffic_signals:sound=locate** when there is only the signal to _find the pole_ (tock - tock in most countries) , but no signal when walking is allowed.

Fix description of traffic_signals:sound=locate

---

.github/workflows/gradle-wrapper-validation.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

OsmAnd-java/src/main/java/net/osmand/router/GeneralRouter.java
OsmAnd/src/net/osmand/plus/routepreparationmenu/EmissionHelper.java
OsmAnd/src/net/osmand/plus/routing/RouteProvider.java
OsmAnd/src/net/osmand/plus/routing/TransportRoutingHelper.java
OsmAnd/src/net/osmand/plus/settings/fragments/RouteParametersFragment.java
OsmAnd/src/net/osmand/plus/settings/fragments/VehicleParametersFragment.java

To reproduce the bug that was fixed in this pull request, you should remove profile preferences or only "prouting_motor_type" preference for needed profile.
Then start navigation with this profile and after that move to "Navigation Settings" -> "Vehicle Parameters" -> "Fuel used by motor". "Fuel used by motor" preference has missed its default value, that should be displayed as "Not selected".
It happened because of wrong default value (an empty string) that initialize preference when navigation started.
The correct default value must be "0.0" for routing preferences which have **_numeric_** type.

Fix "Not selected" is not selected by default after clean installation

---

OsmAnd/res/values/strings.xml

There does not seem to be any "Manage map files" item in the settings.

Remove references to Manage map files from strings.xml

---

OsmAnd/src/net/osmand/plus/views/mapwidgets/WidgetsPanel.java
OsmAnd/src/net/osmand/plus/views/mapwidgets/configure/WidgetsSettingsHelper.java
OsmAnd/src/net/osmand/plus/views/mapwidgets/configure/reorder/ReorderWidgetsFragment.java
OsmAnd/src/net/osmand/plus/views/mapwidgets/configure/reorder/WidgetsDataHolder.java

Use the same widgets order like when copying after click on "Copy from another profile" action button in the bottom of the selected panel widgets screen.

Fix "Problem with copying widgets from other profiles"

---

OsmAnd-java/src/main/java/net/osmand/util/Algorithms.java
OsmAnd/src/net/osmand/plus/auto/FavoritesScreen.java
OsmAnd/src/net/osmand/plus/backup/BackupExecutor.java
OsmAnd/src/net/osmand/plus/backup/BackupExporter.java
OsmAnd/src/net/osmand/plus/dashboard/DashFavoritesFragment.java
OsmAnd/src/net/osmand/plus/download/DownloadIndexesThread.java
OsmAnd/src/net/osmand/plus/mapmarkers/MapMarkersHelper.java
OsmAnd/src/net/osmand/plus/myplaces/FavouritesHelper.java
OsmAnd/src/net/osmand/plus/plugins/osmedit/data/EditPoiData.java
OsmAnd/src/net/osmand/plus/plugins/osmedit/data/OpenstreetmapPoint.java
OsmAnd/src/net/osmand/plus/plugins/osmedit/helpers/OpenstreetmapsDbHelper.java
OsmAnd/src/net/osmand/plus/poi/PoiFiltersHelper.java
OsmAnd/src/net/osmand/plus/utils/AndroidUtils.java
OsmAnd/src/net/osmand/plus/views/OsmandMap.java
OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
OsmAnd/src/net/osmand/plus/views/layers/FavouritesLayer.java
OsmAnd/src/net/osmand/plus/views/layers/MapInfoLayer.java
OsmAnd/src/net/osmand/plus/views/mapwidgets/MapWidgetRegistry.java
OsmAnd/src/net/osmand/plus/voice/JsMediaCommandPlayer.java

We had the same problem with sorting CopyOnWriteArrayList that resulted in diferent issues on Android 6: #15128, #15129, #15202, #15203.
**Problem:** Collections.sort uses ListIterator.set, but CopyOnWriteArrayList's ListIterator does not support the "remove", "set" or "add" methods.

Fix "Android 6: CopyOnWriteArrayList sort problems"

---

OsmAnd/res/values-fr/phrases.xml

"Kindergarten" would be translated as "Crèche", not "Maternelle".

[FR translation] Kindergarten

---

OsmAnd-java/src/main/java/net/osmand/map/TileSourceManager.java

Some online map data sources do not have native support for tiled web map
(slippy map) requests. A common way of operating without the tile zoom/x/y
triplet is to specify a lat/lon bounding box in the tile request.
Previously, as a workaround, osmand suggested pointing at a redirecting
proxy that would rewrite requests for zoom/x/y tiles with an equivalent request
for a bounding box (i.e. http://whoots.mapwarper.net/tms)
Instead of this workaround, implement this functionality natively by adding
a "{bbox}" parameter to templated tile URLs, which will be replaced at request
time with the tile's lat/lon bounding box.
Examples of services that use the templated bounding box method:
1) ArcGIS rest service:
https://gis.charttools.noaa.gov/arcgis/rest/services/MCS/NOAAChartDisplay/MapServer/exts …

Add support for online tile source template URLs with only bounding box

---

OsmAnd/res/values/strings.xml

Proposed fixes for most relevant items originally mentioned in issue  #15279:
- Times given when next update will take place are absolute (time of day). Adapt phrasing accordingly ("at" instead of "in").
- Typo: dayly --> daily
In my understanding, other languages will be covered by re-translating the English version via Weblate, so left out of this PR.

Fix time-related live-update-related strings

---

OsmAnd-java/src/main/java/net/osmand/router/RoutePlannerFrontEnd.java

When recalculationEnd was changed from RouteSegment to RouteSegmentPoint, a gap appeared in routing. 
before: recalculationEnd = segment with start 0 end 16
after:  recalculationEnd = point with start 0 end 1
**solution** : if RouteSegmentResult length > 1 segment -> other part of RouteSegmentResult will be added to the parent.
And Error **Points are not connected** was fixed.

fix recalculationEnd

---

OsmAnd/src/net/osmand/plus/AppVersionUpgradeOnInit.java
OsmAnd/src/net/osmand/plus/poi/PoiFiltersHelper.java
OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java

We should not use a single comma sign as a delimiter when storing a list of POI selected to display.

Fix #14993 Custom POI disappears when screen turns off

---

OsmAnd/src/net/osmand/plus/routepreparationmenu/MapRouteInfoMenu.java

This PR is meant to fix the following issue:
As you can see the button to stop navigation is translated to french as "Ignorer" which means "ignore", translated from "dissmiss" I think. In my opinion the button should be more assertive: "stop" or something like that.
Unfortunately I failed to build the app locally to check that I fixed the right file.
```
> Task :OsmAnd:processAndroidFullOpengldebugArm64ReleaseResources FAILED
FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':OsmAnd-java:test'.
> There were failing tests. See the report at: file:///home/symphorien/src/OsmAnd/OsmAnd-java/build/reports/tests/test/index.html
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or …
```

Navigation: use cancel/stop instead of dismiss to stop navigation

---

OsmAnd/src/net/osmand/plus/measurementtool/MeasurementToolLayer.java
OsmAnd/src/net/osmand/plus/views/layers/GPXLayer.java
OsmAnd/src/net/osmand/plus/views/layers/RouteLayer.java

Apk Version : 4.3.2 4302
Exception occured in thread Thread[Thread-27936,5,main] : 
java.lang.NullPointerException: null upcall object in OsmAnd::interface_MapTiledCollectionProvider::getPoint31

Fix crash MapTiledCollectionProvider

---

OsmAnd/src/net/osmand/plus/routing/VoiceRouter.java

Note: Looks like check for `toRef == null` not needed, because it is always filled with `getNonNullString(...)`.

Fix TTS ref concatenation (#16256)

---

OsmAnd/src/net/osmand/core/android/MapRendererContext.java
OsmAnd/src/net/osmand/plus/activities/MapActivity.java
OsmAnd/src/net/osmand/plus/views/MapViewWithLayers.java

Wait for all renderer resources to be removed

Wait for renderer resources to be removed

---

OsmAnd/res/values-en-rGB/phrases.xml
OsmAnd/res/values-ru/phrases.xml
OsmAnd/res/values-uk/phrases.xml
OsmAnd/res/values/phrases.xml

This adds strings for four new types of recycling waste that I see in OSM. They are all present in the table for [`amenity=recycling`][table].
This PR replaces https://github.com/osmandapp/OsmAnd-iOS/pull/2593 and https://github.com/osmandapp/OsmAnd-resources/pull/937.
How can I test this change locally on iOS? I don't know how to sync these `phrases.xml`s to `ios`.
* I tried `resources/poi/copy_phrases.sh`, but it prints a lot of errors like `cp: directory phrases/en does not exist`;
* tried `ios/Scripts/add_translations.swift`, and killed it after ~15 minutes of running, it only updated `Resources/Localizations/*.lproj/Localizable.strings` files;
* running `ios/prepare.sh` doesn't update any `xml`s.
I was able to generate a piece of the map with the modified `poi_types.xml` …

Add several recycling waste types

---

OsmAnd/src/net/osmand/plus/importfiles/ImportHelper.java
OsmAnd/src/net/osmand/plus/myplaces/ui/AvailableGPXFragment.java
OsmAnd/src/net/osmand/plus/plugins/osmedit/dialogs/UploadMultipleGPXBottomSheet.java
OsmAnd/src/net/osmand/plus/track/helpers/GPXInfo.java

Retained the logic proposed as a fix (https://github.com/osmandapp/OsmAnd/commit/cd1097a95a3efe77ff1ac8fe75e2e4b6b03464de) for this problem (#1239), but also made it possible to get the real (not increased) file size in places where it is needed.

Use increased file size only where it was used before

---

OsmAnd/src/net/osmand/plus/widgets/popup/PopUpMenuDisplayData.java

Fix crash that appeared after refactoring PopUpMenu in this commit: https://github.com/osmandapp/OsmAnd/pull/16317/commits/b113ca7fc0d168d2c2f80822e5bb4187082a741a
In this commit the default layoutId for a popup menu item was accidentally lost.

Fix crash #16755 Use default layoutId unless otherwise specified

---

OsmAnd/src/net/osmand/plus/settings/fragments/ExportSettingsFragment.java

dd-MM-yy is easily confused with the ISO 8601 standard for dates, so I suggest to stick to the standard.
For further reference: https://xkcd.com/1179/

Change DATE_FORMAT in  Export Settings Filename to ISO8601

---

OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java

Don't slide my location icon on double tap zooming

Fix my location moving on double tap

---

.github/workflows/build-debug-apk.yml
gradle.properties

This PR adds GitHub workflow for letting GitHub build OsmAnd on demand (so people can easily let GitHub build OsmAnd debug version .apk even without having Android development environment setup)
The workflow was tested and works fine (e.g. [here](https://github.com/mnalis/OsmAnd/actions/runs/5020565930)).

GitHub workflow for building Android APK on demand

---

OsmAnd/res/values/strings.xml

This is shown in the Maps→Updates section for maps, but also for the Wikipedia files and Wikivoyage (which are not).
Having it be just "Update" works better, seeing as all entries already have a title. aka. "Travel guides" for Wikivoyage vs.
having dedicated entries for each "Update map" "Update travel guide" etc.
Could be that this "Update map" is used elsewhere, but there is a separate one for the context menu already.

Spelling: Update map → Update

---

OsmAnd/src/net/osmand/plus/plugins/rastermaps/DownloadTilesFragment.java
OsmAnd/src/net/osmand/plus/resources/SQLiteTileSource.java

For SQLiteTileSource default 'maxZoom' parameter was initialized with wrong value (because value from the database was not pulled up in the right place). 
It caused a crash because the default maximum value could sometimes go ouside the allowed limits of the slider.

Fix #17599 Crash on raster map download

---

OsmAnd-java/src/main/java/net/osmand/CollatorStringMatcher.java
OsmAnd-java/src/main/java/net/osmand/RenderingContext.java
OsmAnd-java/src/main/java/net/osmand/router/BinaryRoutePlanner.java
OsmAnd-java/src/main/java/net/osmand/router/RoutePlannerFrontEnd.java
OsmAnd-java/src/main/java/net/osmand/router/TestRouting.java
OsmAnd-java/src/main/java/net/osmand/search/SearchUICore.java
OsmAnd-java/src/main/java/net/osmand/util/LocationParser.java
OsmAnd-java/src/main/java/net/osmand/util/MapAlgorithms.java
OsmAnd-java/src/main/java/net/osmand/util/MapUtils.java
OsmAnd-java/src/main/java/net/osmand/util/SunriseSunset.java
OsmAnd-telegram/src/net/osmand/aidl/IOsmAndAidlInterface.aidl
OsmAnd/src/net/osmand/plus/helpers/FeedbackHelper.java
OsmAnd/src/net/osmand/plus/plugins/audionotes/MultimediaNotesFragment.java
OsmAnd/src/net/osmand/plus/render/RendererRegistry.java
OsmAnd/src/net/osmand/plus/resources/ResourceManager.java
OsmAnd/src/net/osmand/plus/resources/SQLiteTileSource.java
OsmAnd/src/net/osmand/plus/settings/backend/backup/SettingsHelper.java
OsmAnd/src/net/osmand/plus/views/MapLayers.java
OsmAnd/src/net/osmand/plus/views/controls/SwipeDismissListViewTouchListener.java
OsmAnd/src/net/osmand/plus/views/layers/MapQuickActionLayer.java
OsmAnd/src/net/osmand/plus/views/mapwidgets/widgets/StreetNameWidget.java

Fix a variety of typos, notably documentation related and user-facing.
Found via `codespell -q 3 -S "./OsmAnd/res/values-*,./OsmAnd-telegram/res/values-*" -L alocation,ans,currenty,finaly,initialy,isplay,nd,pres,ser,te`

Fix various typos

---

OsmAnd/res/values/phrases.xml

Attribute ``shop=yes`` is used to describe a shop without any other information, like shop category.
Source: https://wiki.openstreetmap.org/wiki/Key:shop 
"General store" means a shop where all (or, at least, many) types of items are sold.
I think just "Shop" is more correct than "General Store" in this case.
Thanks!
Edit: I think, "General Store" is corresponding with ``shop=general`` tag.

"General Store" > "Shop"

---

OsmAnd-java/src/main/java/net/osmand/binary/BinaryInspectorNative.java

"lan" was meant to be "lat" for "latitude"

Fix typo in BinaryInspectorNative.java

---

OsmAnd/src/net/osmand/plus/activities/MapActivity.java
OsmAnd/src/net/osmand/plus/keyevent/devices/NoneDeviceProfile.java
OsmAnd/src/net/osmand/plus/keyevent/devices/base/DefaultInputDeviceProfile.java
OsmAnd/src/net/osmand/plus/keyevent/devices/base/InputDeviceProfile.java

When device profile is "None", volume buttons were also dissabled, but in settings they could be enabled in the same time.
Also small code appearance improvements.

Fix bug with volume buttons for key event listener

---

OsmAnd/src/net/osmand/plus/activities/MapActivity.java
OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java
OsmAnd/src/net/osmand/plus/views/AnimateDraggingMapThread.java
OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java

Use elevation data to avoid going below the surface of the terrain when zooming

Use zooming relative to terrain

---

OsmAnd/src/net/osmand/plus/measurementtool/graph/ChartAdapterHelper.java
OsmAnd/src/net/osmand/plus/measurementtool/graph/CustomChartAdapter.java

Quick fix for https://github.com/osmandapp/OsmAnd/issues/18316
The problem was observed on Android 13.
The bug arose due to the connection of the main chart (LineChart) with secondary charts (HorizontalBarChart).
When HorizontalBarChart is Clicked, the MotionEvent is passed to the main chart (LineChart).
After that main chart searches for the nearest highlight, update its position and distributes this position to child graphs.
For unknown reasons on new versions of Android (the bug is absent on Android 11, but present on Android 13), the click event on HorizontalBarChart came with too much displacement along the Y-axis (On Android 11, it seems like the "y" coordinate was calculated relative to local coordinates within the HorizontalBarChart itself, while on Adnroid 13 it seems like the …

Fix "Can't click on graph Road Type in Plan Route #18316"

---

OsmAnd/src/net/osmand/plus/settings/datastorage/DataStorageFragment.java

As per official docs [getExternalFilesDirs](https://developer.android.com/reference/android/content/Context#getExternalFilesDirs(java.lang.String)) & [getObbDirs](https://developer.android.com/reference/android/content/Context#getObbDirs()) don`t need permissions. "_No additional permissions are required for the calling app to read or write files under the returned path. Write access outside of these paths on secondary external storage devices is not available._" 
Also [WRITE_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE) is obsolete for apps which target Android 11 or higher, so we cannot get proper access to non app-specific directories, only via [ACTION_OPEN_DOCUMENT_TREE](https://developer.android.com/training/data-storage/ …

Fix #18352

---

OsmAnd-java/src/main/java/net/osmand/data/RotatedTileBox.java
OsmAnd/src/net/osmand/plus/activities/MapActivity.java
OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java
OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java

Use terrain elevation value to restore correct map zoom on relief when heightmaps is not yet loaded

Restore correct map zoom on relief

---

OsmAnd/res/values-de/phrases.xml

The German translation for board:title was not completely correct until now, so I changed it.

fix German translation for board:title.xml

---

OsmAnd/src/net/osmand/plus/render/UpdateVectorRendererAsyncTask.java

Don't redraw map after unlocking the device

Fix unnecessary map redrawing after device unlock

---

OsmAnd/res/layout/map_hud_top.xml
OsmAnd/src/net/osmand/plus/mapcontextmenu/MapContextMenuFragment.java
OsmAnd/src/net/osmand/plus/views/controls/SideWidgetsPanel.java

The problem seems to be caused by trying to display the left widget panel above the map hud top buttons when that panel is empty (has no widgets to display).
In this case, the visibility panel becomes visible for a moment, and then automatically becomes invisible when the panel refreshes and realizes that it has nothing to display.
In this fix, we prevent the panel from becoming visible if it has nothing to display (however, we keep the ability to become visible in the future if visible widgets appear on it).

Fix 18275 Top buttons jump when open Context Menu

---

OsmAnd/src/net/osmand/plus/routing/RouteProvider.java

In keeping with #18865, here is an update for the RouteProvider so that a BRouter profile can be called directly.

Call a BRouter profile by name

---

OsmAnd/res/values/strings.xml

https://english.stackexchange.com/questions/7657/use-of-hypens-with-auto-autopopulate-auto-populate-or-auto-populate
https://grammarhow.com/auto-populate-or-autopopulate/
https://books.google.com/ngrams/graph?content=auto+zoom%2Cauto-zoom%2Cautozoom&year_start=1800&year_end=2019&corpus=en-2019&smoothing=3
Using a dash is consistent with other use of dashes in OsmAnd, it isn't wrong, only one source say to avoid "auto-" followed by a consonant, other than that cited as correct and conservative.
It is a bit of a wash on the whole.
"Auto zoomed past me", meaning either a car flying by, or auto-focus not doing its thing is what to avoid.

Spelling: Auto-zooming/ed

---

OsmAnd/AndroidManifest.xml
OsmAnd/res/layout/bottom_sheet_icon_title_description.xml
OsmAnd/src/net/osmand/plus/settings/controllers/BatteryOptimizationController.java

Fixes after UI Review: https://github.com/osmandapp/OsmAnd/issues/14958#issuecomment-1916542271
+ Open system settings for a particular application (OsmAnd) instead of opening list of all applications (when user click on "Battery optimization settings" option).
+ Fix line spacing for description.

Fix "Battery optimization settings" feature after UI review

---

OsmAnd-java/src/main/java/net/osmand/router/RoutePlannerFrontEnd.java

Avoid prepareResult is a wrong way (no regions/data loaded in Java after Native)
This reverts commit 9cc00a8a1bd49fc28e60325c9674dc505d4dad4d.

[hotfix] Revert "Avoid double call prepareResult (fix 1st/last seg) (#19117)"

---

OsmAnd/src/net/osmand/plus/settings/controllers/RouteLineColorController.java

Use correct strings "Day" and "Night" on the "Route Line Appearance" dialog (fix #11570).
Original fix: https://github.com/osmandapp/OsmAnd/pull/19232

Fix using of "Day / Night" strings for "Route Line Appearance" dialog

---

OsmAnd-java/src/main/java/net/osmand/NativeLibrary.java

See NO_DIRECTION in legacy repo:
`#define NO_DIRECTION ((float)(-2 * M_PI)) // -360 degrees in RADIANS for no-direction rule (Java uses ==null instead)`
Changed to constant because using `-2 * (float) Math.PI` in not so clear for this particular case.
Previously changed from broken value -360:
69eaaddd5622f8720d90fcb2b24fa858ee685d1a

Replace magic value with constant CPP_NO_DIRECTION

---

OsmAnd-java/src/main/java/net/osmand/router/BinaryRoutePlanner.java
OsmAnd-java/src/main/java/net/osmand/router/PrecalculatedRouteDirection.java

Original C++ request: https://github.com/osmandapp/OsmAnd-core-legacy/pull/185
C++ code needs that fixes to fix broken match of 2-phase start/end and to fix incorrect 2-phase detection at all.
Java methods have correct 2-phase startPoint/endPoint (for today, but who knows what might happen later).
Reasons to approve:
1. This request will sync Java and C++ code
3. Addionally, BRP h() method will be faster because old implementation was not optimal for 2-phase.

Backport C++ car 2-phase fix legacy/pull/185

---

OsmAnd/src/net/osmand/plus/mapcontextmenu/MapContextMenuFragment.java
OsmAnd/src/net/osmand/plus/mapcontextmenu/MenuBuilder.java
OsmAnd/src/net/osmand/plus/mapcontextmenu/controllers/TransportStopController.java

the nearest only subway stop doesn't includes in the bbox inscribed in circle with 150m radius

 Add nearest stop for Olympiiska bus stop

---

OsmAnd-java/src/main/java/net/osmand/router/MissingMapsCalculator.java

The problem. We have SRTM-only (sub)regions such as Afghanistan, Egypt, Libya, Chile, etc.
That SRTM-only regions (no map, no routing, only contours) are added regions List and a few lines later the list is sorted to get 1st only String from regions finally.
In case of Afghanistan + Tajikistan, the sorted result is:
afghanistan_baghlan_asia - the longest name, sorted to the top = get(0)
afghanistan_asia (ignored)
tajikistan_asia (ignored)
As a result, afghanistan_baghlan_asia is the only mapsToDownload region, which is obviously NOT A MAP/roads, not allowed to download as a map/roads, and finally we have the EMPTY list of Missing Maps and the disabled Download button.
The bugfix just excludes NOT map/roads regions from List.

Missing Maps: avoid adding SRTM-only regions

---

OsmAnd-java/src/main/java/net/osmand/router/MissingMapsCalculator.java

This request fixes some cases in Europe such as Austria (Salzburg) -> Germany -> Austria (Innsbruck), Switzerland -> France -> Switzerland where the fastest route should run by a highway not via mountain roads.
I've tested the performance on 2000+ km distance and Missing Maps calc speed was not degraded.

Missing Maps: Decrease DISTANCE_SPLIT to 15km

---

OsmAnd-java/src/main/java/net/osmand/binary/BinaryMapPoiReaderAdapter.java

To issue https://github.com/osmandapp/OsmAnd/issues/16397
Before we had not problem with this because subcategories always was single. After adding top_index_brand subcategories increase to 100 pcs.
It is backshift operation to this:
this.targetId = (valueId << 16) | (catId << 1) | 1;

Fix subcategories POI reading (bits operation)

---

OsmAnd/src/net/osmand/core/android/MapRendererContext.java

Don't show vector map symbols on online map layer

Fix vector map symbols shown over online map

---

OsmAnd-java/src/main/java/net/osmand/gpx/GPXUtilities.java

Hardy, please approve a little fix.
PS. Kotlin GpxUtilities seems OK.
```
2024-09-07 21:36:14.151 ERROR [http-nio-127.0.0.1-8090-exec-2]: Error saving gpx
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "net.osmand.gpx.GPXUtilities$WptPt.getBackgroundType()" is null
at net.osmand.gpx.GPXUtilities.writeWpt(GPXUtilities.java:1296)
at net.osmand.gpx.GPXUtilities.writePoints(GPXUtilities.java:1125)
at net.osmand.gpx.GPXUtilities.writeGpx(GPXUtilities.java:1031)
at net.osmand.gpx.GPXUtilities.writeGpxFile(GPXUtilities.java:998)
at net.osmand.server.controllers.pub.GpxController.saveTrackData(GpxController.java:280)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at …
```

Fix NPE p.getIconName/p.getBackgroundType is null

---

OsmAnd/res/values-da/phrases.xml

some spelling issues.
and caravan_site should be "autocamplerplads". On most caravan_sites "campingvogn" is not allowed or not possible.

update Danish phrases

---

OsmAnd/src/net/osmand/plus/download/local/CollectLocalIndexesAlgorithm.java
OsmAnd/src/net/osmand/plus/download/local/CollectLocalIndexesRules.java
OsmAnd/src/net/osmand/plus/download/local/LocalItemsLoaderTask.java

This request has to fix problem described here: https://github.com/osmandapp/OsmAnd/issues/21252#issuecomment-2462754169
The problem comes from the new conditions we set to calculate the size of the tiles (Issue: https://github.com/osmandapp/OsmAnd/issues/20974), however we shouldn't set these limits for tiles those are stored as one SQLite file, because there is only one file and it calculates anyway.

Don't limit display size for tiles stored as SQLite DB

---

OsmAnd/src/net/osmand/plus/auto/NavigationSession.java
OsmAnd/src/net/osmand/plus/routing/RouteRecalculationHelper.java

Fixes multiple NPE (was displayed as a toast) when Navigation started immediately after OsmAnd start (previous navigation and/or quick navigation to any point is the action to reproduce).
The problem might happen when PlatformUtil.getOsmandRegions() is still not ready, searchRoute() starts and MissingMapsCalculator requires non-null regions.
On slow devices, the bug might happen even in 5-10 seconds after OsmAnd is loaded and UI is ready.
Now the frightening NPE message in the toast changed to "Calculating route…" from strings.xml
PS. Additionally, the same issue in NavigationSession should be fixed by this request, because `if (app.getRegions() != null)` seems as incorrect way to validate regions.
```
14:43:41.270  E  RouteProvider Runtime error: Attempt to invoke virtual method …
```

Fix NPE when PlatformUtil.getOsmandRegions() is not ready

---

OsmAnd/src/net/osmand/plus/routing/CurrentStreetName.java

Avoid to create street name based on _ref_ if shields was already created. In most cases shields already based on the _ref_ in different combinations.
To issue https://github.com/osmandapp/OsmAnd/issues/21362

Avoid show ref is shields was created

---

OsmAnd/src/net/osmand/plus/views/layers/GPXLayer.java
OsmAnd/src/net/osmand/plus/views/layers/MapMarkersLayer.java
OsmAnd/src/net/osmand/plus/views/layers/geometry/GpxGeometryWay.java
OsmAnd/src/net/osmand/plus/views/layers/geometry/MultiColoringGeometryWay.java

Don't recreate symbol providers for arrows on the trip vector line

Fix blinking arrows while trip is recording

---

OsmAnd/src/net/osmand/plus/myplaces/tracks/dialogs/BaseTrackFolderFragment.java

Fix bug that tracks folder didn't disappear immediately from UI on `My Places` -> `Tracks` after it had been deleted

Remove tracks folder immediately from UI after it was deleted

---

OsmAnd-java/src/main/java/net/osmand/router/TransportRoutePlanner.java
OsmAnd/src/net/osmand/plus/routing/TransportRoutingHelper.java

To issue https://github.com/osmandapp/OsmAnd/issues/20784

Fix public transport routing

---

OsmAnd/src/net/osmand/plus/resources/ResourceManager.java

```
16:04:17.723  E  DownloadResources java.text.ParseException: Unparseable date: "12/1/24" {AsyncTask #2}
16:04:17.723  E  DownloadResources java.text.ParseException: Unparseable date: "11/11/24" {AsyncTask #2}
16:04:17.725  E  DownloadResources java.text.ParseException: Unparseable date: "12/1/24" {AsyncTask #2}
16:04:17.725  E  DownloadResources java.text.ParseException: Unparseable date: "12/1/24" {AsyncTask #2}
```

Fix lastModified for deactivated maps (DateFormat)

---

OsmAnd-java/src/main/java/net/osmand/search/core/SearchCoreFactory.java

SearchCoreFactory.java:1250
```
for (PoiTypeResult poiTypeResult : poiTypeResults.values()) {
for (String foundName : poiTypeResult.foundWords) {
CollatorStringMatcher csm = new CollatorStringMatcher(foundName, StringMatcherMode.CHECK_ONLY_STARTS_WITH);
// matches only completely
int mwords = SearchPhrase.countWords(foundName);
if (csm.matches(phrase.getUnknownSearchPhrase()) && countExtraWords < mwords) {
countExtraWords = SearchPhrase.countWords(foundName);
List<String> otherSearchWords = phrase.getUnknownSearchWords();
nameFilter = null;
if (countExtraWords - 1 < otherSearchWords.size()) {
nameFilter = "";
for (int k = countExtraWords - 1; k < otherSearchWords.size(); k++) {
if (nameFilter.length() > 0) {
nameFilter += SearchPhrase.DELIMITER;
}
nameFilter += otherSearchWords.get(k);
} …
```

Order PoiTypeResult by: top, categories, types, additionals

---

OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/cards/ImageCard.java
OsmAnd/src/net/osmand/plus/mapcontextmenu/gallery/GalleryDetailsFragment.java

The issue occurs due to missing necessary data (e.g., the source icon for the image) in the response sent from the OsmAnd server. The server currently provides only the URL but lacks other metadata about the image (e.g., author, upload date, license, source). It might be a good idea to add these params on the server side if such data can be retrieved.
> **Tip:** To get images from OsmAnd server make sure the **Mapillary Plugin** is enabled.
For one of the locations mentioned in the issue, the server returns the following JSON image data:
```
{
"type": "wikimedia-photo",
"lat": 48.12747,
"lon": 8.088678,
"timestamp": "2024-11-09T09:05:24Z",
"key": "File:Dorerbühl-Huette_01.jpg",
"title": "Dorerbühl-Huette 01.jpg",
"url": "https://commons.wikimedia.org/wiki/File:Dorerb%C3%BChl-Huette_01.jpg" …
```

Fix "Crash when trying to observe image details" #21579

---

OsmAnd/src/net/osmand/plus/activities/MapActivity.java
OsmAnd/src/net/osmand/plus/auto/TripHelper.java
OsmAnd/src/net/osmand/plus/notifications/NavigationNotification.java
OsmAnd/src/net/osmand/plus/views/mapwidgets/widgets/StreetNameWidget.java

We also added an update to the **`onConfigurationChanged`** method of the **`MapActivity`** class to ensure that the colors of the turn drawable are updated in the notification as well.
Here is an example of successfully updating colors in notification when changing the device's system theme:
[Screen_recording_20250107_171411.webm](https://github.com/user-attachments/assets/73c6cf54-514a-452f-b3c1-87b66b196e06)

Update turn outlay color everywhere it's used

---

OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java
OsmAnd/src/net/osmand/plus/routepreparationmenu/MapRouteInfoMenu.java
OsmAnd/src/net/osmand/plus/routepreparationmenu/RouteOptionsBottomSheet.java
OsmAnd/src/net/osmand/plus/routepreparationmenu/ShowAlongTheRouteBottomSheet.java

The problem occurred due to the lack of automatic recalculation of user points when changing the settings for announcing these types of points in the "Voice Prompts" screen. In other parts of the app, points were recalculated if the "Show Points" feature was enabled. However, on the Voice Prompts settings screen, this recalculation was not triggered.
**Fix:**  
1. Added listeners to the settings and implemented automatic recalculation of points whenever voice prompt settings were changed.  
2. Introduced the variable `rejectPointsCalculation` to prevent excessive recalculations when the settings were modified internally within the `WaypointsHelper` class.
3. The update process is now triggered asynchronously from the UI to prevent potential freezes in case of a large number of points. …

Fix "Turning off Nearby POIs doesn't mute instructions #21657"

---

OsmAnd/src/net/osmand/plus/measurementtool/MeasurementEditingContext.java

This pull request addresses the issue described in https://github.com/osmandapp/OsmAnd/issues/21418.
The issue occurred exclusively for tracks recorded manually via **Trip Recording** and did not affect tracks created with **Plan Route** or exported from navigation routes.
The root cause was point duplication in tracks, resulting in a mismatch between the number of points in GPX tracks and segments in the editing context. This problem is described in detail [here](https://github.com/osmandapp/OsmAnd/issues/21418#issuecomment-2561959908) and [here](https://github.com/osmandapp/OsmAnd/issues/21418#issuecomment-2573242477).
- The duplication was traced back to code added over 8 years ago, which caused errors in elevation calculations.
- All potential use cases for duplication were analyzed …

Fix "Elevation Correction doesn't work"

---

OsmAnd/src/net/osmand/plus/importfiles/tasks/ObfImportTask.java

```
01-20 16:43:22.714  8934 28729 W System.err: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.osmand.plus/files/travel/malta.travel.obf: open failed: ENOENT (No such file or directory)
01-20 16:43:22.714  8934 28729 W System.err:  at libcore.io.IoBridge.open(IoBridge.java:574)
01-20 16:43:22.714  8934 28729 W System.err:  at java.io.FileOutputStream.<init>(FileOutputStream.java:259)
01-20 16:43:22.714  8934 28729 W System.err:  at java.io.FileOutputStream.<init>(FileOutputStream.java:208)
01-20 16:43:22.714  8934 28729 W System.err:  at net.osmand.plus.importfiles.ImportHelper.copyFile(ImportHelper.java:419)
01-20 16:43:22.714  8934 28729 W System.err:  at net.osmand.plus.importfiles.ImportHelper.copyFile(ImportHelper.java:387)
01-20 16:43:22.714  8934 28729 W …
```

Fix first time import for road/travel/wiki obf(s)

---

OsmAnd-java/src/main/java/net/osmand/CollatorStringMatcher.java
OsmAnd-java/src/main/java/net/osmand/search/core/SearchCoreFactory.java
OsmAnd-java/src/main/java/net/osmand/search/core/SearchPhrase.java
OsmAnd-java/src/main/java/net/osmand/util/ArabicNormalizer.java

To issue https://github.com/osmandapp/OsmAnd/issues/11709

Add arabic normalizer for search

---

OsmAnd-java/src/main/java/net/osmand/osm/AbstractPoiType.java
OsmAnd-java/src/main/java/net/osmand/search/SearchUICore.java
OsmAnd-java/src/main/java/net/osmand/search/core/SearchCoreFactory.java
OsmAnd-java/src/main/java/net/osmand/search/core/TopIndexFilter.java

To issue [Brand search results are duplicated after increasing the search radius](https://github.com/osmandapp/OsmAnd/issues/21577)

Fix duplications in search

---

OsmAnd/src/net/osmand/plus/configmap/ConfigureMapUtils.java
OsmAnd/src/net/osmand/plus/helpers/LocaleHelper.java
OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java
OsmAnd/src/net/osmand/plus/settings/fragments/BaseSettingsFragment.java
OsmAnd/src/net/osmand/plus/settings/fragments/GlobalSettingsFragment.java

The issue we aimed to fix was incorrect parsing of the **script** in a locale tag. This occurred because the system-provided locale tag used a different format than what our app expected—specifically, it used `#` instead of `+` to separate the script from other locale parameters.  
A quick fix was introduced in [PR #21908](https://github.com/osmandapp/OsmAnd/pull/21908), which addressed this formatting issue. However, it assumed that if a script was present, it would always be the third element in the locale tag. This assumption was incorrect, as scripts are optional, and other components like **extensions** could take the third position instead. Attempting to set an extension as a script in `Locale.Builder` caused crashes, since scripts must be **alpha-4 codes** as per ISO 15924 (all …

Implement modern locale tag processing

---

OsmAnd/src/net/osmand/plus/track/fragments/TrackMenuFragment.java

Tested on NetworkRouteSelector, TravelGpx and ClickableWay.
Click from map = OK
Click from search = OK
Save to permanent GPX = OK

Remove useless GPX reloading for isTempFile tracks (avoid double-call to getAnalysis, etc)

---

OsmAnd/src/net/osmand/plus/poi/PoiFiltersHelper.java

Reverting part of the logic introduced in this pull request: https://github.com/osmandapp/OsmAnd/pull/20468/files (which was related to fixing this issue: https://github.com/osmandapp/OsmAnd/issues/17944).  
Keeping the Wikipedia POI type visible when displaying the POI filter in Search can obstruct the user's view of relevant points on the map. Therefore, the logic for preserving Wikipedia visibility is unnecessary and excessive.  
Additionally, due to an incomplete implementation of this logic, a bug occurred:  
- If the Wikipedia layer was disabled, and the user searched for Wikipedia POIs in Search and displayed the results on the map, upon returning from the Search screen, the Wikipedia layer remained visible, which was incorrect behavior.

Hide Wiki POIs like other types when showing search filter on map

---

OsmAnd-java/src/main/java/net/osmand/data/Amenity.java

Fix man_made=eductation - non present in poi_types.xml, man_made is category for poi landuse_education
To issue https://github.com/osmandapp/OsmAnd/issues/21993

Fix BinaryInspector

---

OsmAnd/src/net/osmand/plus/measurementtool/command/ChangeRouteModeCommand.java

Fixed a bug:
- Create track in Plan Route (with Car profile by example)
- Add new segment. Without any points
- Change routing profile (to Walking by example)
expected: new segment with Walking profile
reality: new segment with Straight line profile
---
Screenshots before / after:
---
Video before:
https://github.com/user-attachments/assets/69cf3805-3e37-49bf-8b25-d5a9f482339b
Video after:
https://github.com/user-attachments/assets/1a966133-5d76-4325-b69a-85abe0237f1e
---
[ios related pr](https://github.com/osmandapp/OsmAnd-iOS/pull/4538)

Plan route segments fix

---

OsmAnd/src/net/osmand/plus/views/MapLayers.java

When the OsmandRasterMapsPlugin was disabled, transparency and (maybe) some other settings related to underlay/overlay layers were still being applied. This led to incorrect rendering (e.g., semi-transparent labels) even though the plugin was inactive.
In the updateMapSource() method, we now check PluginsHelper.isEnabled(OsmandRasterMapsPlugin.class) before applying transparency values from MAP_UNDERLAY or MAP_OVERLAY_TRANSPARENCY. If the plugin is disabled, transparency defaults to 255, and the related settings are ignored.
* Check and unsubscribe from other related data and settings when the plugin is disabled

Fix: incorrect transparency when raster plugin is turned off

---

OsmAnd-java/src/main/java/net/osmand/router/network/NetworkRouteSelector.java

Ignore click on "route_road_1" as well as previously on "route_road" (and other unsupported routes.)

Hotfix containsUnsupportedRouteTags (route_road_1)

---

OsmAnd/src/net/osmand/plus/plugins/monitoring/LiveMonitoringHelper.java

LiveMonitoringData receives location coordinates as doubles, but converts them to floats, significantly reducing precision. You can spot this easily by comparing a recorded GPX track to the live locations sent during the same ride.
Green track: GPX trip recording
Red track: Live monitoring locations
Removing the float cast should allow the live locations to be as precise as the GPX track.

Increase precision of coordinates in live monitoring by using doubles instead of floats

---

OsmAnd/src/net/osmand/plus/quickaction/AddQuickActionFragment.java

It turns out these are actually different screens.
On the main "Add Quick Action" screen we display the list of categories along with the search bar, and in this case when rotating the screen we restore the search query and save it in onSaveInstanceState. If this screen is visible, everything works as expected.
However, if we navigate into a specific category, then on the first rotation the adapter in the parent fragment is still not null, so the state is saved without issues. But after that the base fragment is recreated — onCreate() is called, but onCreateView() is not (since its view is not needed while it’s not visible). This means the adapter is never re-initialized. On the next rotation, the adapter is null, which leads to the NPE.
In this case the simplest and correct fix is just …

Fix crash when rotating screen while adding a new quick action #23271

---

OsmAnd-java/src/main/java/net/osmand/wiki/WikiCoreHelper.java

Was GET `https://data.osmand.net/wikimedia/images-1280/0/0e/Azores_100%_(35905078875).jpg`.
Now GET `https://data.osmand.net/wikimedia/images-1280/0/0e/Azores_100%25_%2835905078875%29.jpg`

Hotfix misplaced decode() in parseImageDataFromFile
