osmandapp/OsmAnd

OsmAnd-java/src/net/osmand/util/GeoPointParserUtil.java, OsmAnd-java/src/net/osmand/util/MapUtils.java, OsmAnd/AndroidManifest.xml, OsmAnd/old-ndk-build.sh, OsmAnd/src/net/osmand/plus/activities/actions/ShareLocation.java, OsmAnd/src/net/osmand/plus/activities/search/GeoIntentActivity.java, OsmAnd/src/net/osmand/plus/audionotes/AudioVideoNotesPlugin.java
This follows on from #1037 and #1039. The changes that affect the Google parsing were removed until they are reworked.  This pull request brings complete OpenStreetMap URL parsing to Osmand.  It also adds support for Baidu Map URLs.  It also changes the shared location message to use http://osmand.net/go as the short link and a `geo:` link.
=> Update url parsing

OsmAnd-java/src/net/osmand/util/GeoPointParserUtil.java, OsmAnd/src/net/osmand/plus/activities/search/GeoIntentActivity.java
Provide a method for getting all the data from a `GeoParsedPoint` in a `geo:` URI String.   This pull request follows up on #1052
=> GeoParsedPoint.getGeoUriString()

OsmAnd/res/values/strings.xml
=> Fix typos in strings.xml

OsmAnd-java/src/net/osmand/util/GeoPointParserUtil.java
Update the parsing of Google Maps URLs to get all the known URLs working.
=> Google url parsing updates

LICENSE
Qt Project has a new URL.
Corrected a few typos while I was at it.
=> New Qt URL

OsmAnd/res/values/strings.xml
=> Align new strings in strings.xml

OsmAnd/res/values-bg/strings.xml, OsmAnd/res/values-ko/strings.xml, OsmAnd/res/values-lt/strings.xml, OsmAnd/res/values-pt-rBR/strings.xml
https://github.com/osmandapp/Osmand/pull/1405#issuecomment-115564948
=> Fixed format strings in r2.1 branch

OsmAnd/res/layout/favorite_edit_dialog.xml, OsmAnd/src/net/osmand/plus/widgets/AutoCompleteTextViewEx.java
Now, if user hasn't typed anything, he will see all categories as a suggestion.
=> Add bookmark dialog: Category suggestion on 0 characters added.

OsmAnd/src/net/osmand/plus/activities/HelpActivity.java
* Fixed issue #1430
misc:
* Fixed imports
* Renamed field to match android conventions.
=> issue #1430 fix, saving WebView state 

OsmAnd/src/net/osmand/plus/osmedit/EditingPOIDialogProvider.java
Wrong value was put as an argument in `dialogBundle`. NullPointerException as a result.
=> issue #1500, POI dialog fix

OsmAnd/res/layout/favorites_list_item.xml, OsmAnd/src/net/osmand/plus/activities/FavoritesListFragment.java, OsmAnd/src/net/osmand/plus/activities/FavoritesTreeFragment.java, OsmAnd/src/net/osmand/plus/dialogs/FavoriteDialogs.java, OsmAnd/src/net/osmand/plus/views/controls/MapRouteInfoControl.java
Favourite items now have 3 dots on their left. To suggest that they are clickable.
=> Menu button for favourites items. For better use experience: issue #1340

OsmAnd/res/values-de/phrases.xml
see also: https://github.com/osmandapp/Osmand/issues/1517
=> Updated German POI translation "car sharing"

OsmAnd/src/net/osmand/plus/activities/search/GeoIntentActivity.java, OsmAnd/src/net/osmand/plus/dashboard/DashBaseFragment.java, OsmAnd/src/net/osmand/plus/resources/RegionAddressRepositoryBinary.java, OsmAnd/src/net/osmand/plus/widgets/InterceptorFrameLayout.java, OsmAnd/src/net/osmand/plus/widgets/tools/SwipeDismissTouchListener.java
=> Dashboard swipe to dismiss

OsmAnd/res/layout/fragment_edit_poi.xml, OsmAnd/res/layout/fragment_edit_poi_advanced.xml, OsmAnd/res/layout/fragment_edit_poi_normal.xml, OsmAnd/src/net/osmand/plus/dashboard/DashboardOnMap.java, OsmAnd/src/net/osmand/plus/dashboard/tools/DashFragmentData.java, OsmAnd/src/net/osmand/plus/dashboard/tools/DashboardSettingsDialogFragment.java, OsmAnd/src/net/osmand/plus/osmedit/AdvancedDataFragment.java, OsmAnd/src/net/osmand/plus/osmedit/EditPoiFragment.java, OsmAnd/src/net/osmand/plus/osmedit/EditingPOIDialogProvider.java, OsmAnd/src/net/osmand/plus/osmedit/NormalDataFragment.java, OsmAnd/src/net/osmand/plus/osmedit/OsmEditingPlugin.java
Poi types implemented, not tested.
=> Poi dialog design. Work in progress

OsmAnd-java/src/net/osmand/map/ITileSource.java, OsmAnd-java/src/net/osmand/map/MapTileDownloader.java, OsmAnd-java/src/net/osmand/map/TileSourceManager.java, OsmAnd/src/net/osmand/plus/SQLiteTileSource.java, OsmAnd/src/net/osmand/plus/resources/AsyncLoadingThread.java, OsmAnd/src/net/osmand/plus/resources/ResourceManager.java
… of new optional field Referer in table INFO of sqlitedb
2. Delete old tiles from sqlitedb in case of using field time. Usefull for unstable tiles, for example traffic map.
=> Means to set Referer field in connection to a tile server and old tiles clearing

OsmAnd/src/net/osmand/plus/views/MapTileLayer.java
There were formatting errors and beside this I unified usage of ternary operators in simple getters.
=> MapTileLayer - formatting & use of ternary op.

OsmAnd/build.gradle, OsmAnd/jni/Application.mk
=> Revert "Enable x86_64 and arm64-v8a ABIs"

OsmAnd/src/net/osmand/plus/osmedit/OsmEditingPlugin.java
I do not know the Java language, but have programming skills. Part of the problem is the issue #1948
=> Add space for better viewing

OsmAnd-java/build.xml, OsmAnd-java/test/java/net/osmand/router/RouteResultPreparationTest.java, OsmAnd-java/test/java/net/osmand/router/TestEntry.java, OsmAnd-java/test/java/net/osmand/router/test_routes.json
This test provide ability to test conformity of lanes suggested by algorithm.
=> Test lanes

OsmAnd/res/values-ru/strings.xml
Please review the following changes:
* 8cbd5db Added a few Russian translations.
* 2ff6382 More exact direction instructions in Russian.
=> [Review] Request from 'poretsky' @ 'poretsky/Osmand/review_160408_proposal'

OsmAnd/res/values-ru/strings.xml, OsmAnd/res/values/strings.xml, OsmAnd/src/net/osmand/access/NavigationInfo.java, OsmAnd/src/net/osmand/access/SettingsAccessibilityActivity.java, OsmAnd/src/net/osmand/plus/OsmandSettings.java, OsmAnd/src/net/osmand/plus/routing/RoutingHelper.java
Please review the following changes:
* 3a02be2 Introduced accessibility mode options allowing to prevent automatic route recalculation.
* 1111ed1 Implemented autoannounce control options for accessibility mode.
=> [Review] Request from 'poretsky' @ 'poretsky/Osmand/review_160413_a11y_proposal'

OsmAnd-java/src/net/osmand/util/Algorithms.java, OsmAnd/src/net/osmand/plus/GpxSelectionHelper.java, OsmAnd/src/net/osmand/plus/activities/ShowRouteInfoActivity.java, OsmAnd/src/net/osmand/plus/audionotes/AudioVideoNoteMenuController.java, OsmAnd/src/net/osmand/plus/audionotes/AudioVideoNoteRecordingMenu.java, OsmAnd/src/net/osmand/plus/audionotes/AudioVideoNotesPlugin.java, OsmAnd/src/net/osmand/plus/helpers/GpxUiHelper.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/GpxItemMenuBuilder.java, OsmAnd/src/net/osmand/plus/myplaces/AvailableGPXFragment.java, OsmAnd/src/net/osmand/plus/osmo/SettingsOsMoActivity.java, OsmAnd/src/net/osmand/plus/routing/RoutingHelper.java
Distance information is not duplicated by the accessibility
feedback. Added particular items for arrival points. Fully qualified
time format is used in accessibility mode since it is treated by
speech synthesizers more correctly.
=> Better accessibility feedback in the route description screen

OsmAnd/src/net/osmand/plus/AppInitializer.java, OsmAnd/src/net/osmand/plus/OsmandSettings.java, OsmAnd/src/net/osmand/plus/activities/MapActivityLayers.java, OsmAnd/src/net/osmand/plus/activities/search/SearchPOIActivity.java, OsmAnd/src/net/osmand/plus/dialogs/ConfigureMapMenu.java, OsmAnd/src/net/osmand/plus/helpers/WaypointDialogHelper.java, OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java, OsmAnd/src/net/osmand/plus/poi/PoiFiltersHelper.java, OsmAnd/src/net/osmand/plus/poi/PoiUIFilter.java, OsmAnd/src/net/osmand/plus/views/POIMapLayer.java
Now it's possible to display casino and church locations at the same time!
Ping @vshcherb
=> Add POI multiselection

OsmAnd/src/net/osmand/plus/routing/RoutingHelper.java
=> RoutingHelper: fix #2524

OsmAnd/src/net/osmand/plus/activities/search/SearchByNameAbstractActivity.java, OsmAnd/src/net/osmand/plus/activities/search/SearchCityByNameActivity.java, OsmAnd/src/net/osmand/plus/resources/RegionAddressRepositoryBinary.java
Also show all villages if no cities are present in region
=> Fix #2471 and #2540

OsmAnd/src/net/osmand/plus/development/TestVoiceActivity.java, OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java, OsmAnd/src/net/osmand/plus/routing/VoiceRouter.java, OsmAnd/src/net/osmand/plus/voice/CommandBuilder.java
Victor, can you please take a look if we want to do this, and double-check the implementation. Thx - Hardy
=> speedAlarm: pass maxSpeed and speed

OsmAnd/res/values/strings.xml
=> Fix typo in strings.xml

README.md
Added link to Weblate in order to help new translators to find the translation platform
=> Add link to Weblate

OsmAnd/src/net/osmand/plus/activities/SettingsGeneralActivity.java
=> Make landscape orientation setting respect sensor

OsmAnd-java/src/net/osmand/util/GeoPolylineParserUtil.java
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md
=> OSRM now has precision 5, Fix #3055

OsmAnd/src/net/osmand/plus/routing/RouteProvider.java
OSRM Server certificate was fixed
=> Enable https for OSRM

OsmAnd/res/values/phrases.xml
Sort some POI strings in phrases.xml so that similar classes are together (e.g. shops, cuisines, wikis). It is useful for consistent translation.
=> Sort pois in phrases.xml

OsmAnd/src/net/osmand/plus/helpers/MapMarkerDialogHelper.java
=> Only show "Reverse order" if there is more than one active marker

OsmAnd/res/values/phrases.xml
Fix possible typos in Historic periods in phrases.xml .
=> Fix typos in phrases.xml

OsmAnd/res/values-es/strings.xml
Better traslation of 725 2295 and 2298.
=> Update settings.xml (spanish - Spain)

OsmAnd/src/net/osmand/plus/search/QuickSearchCoordinatesFragment.java, OsmAnd/src/net/osmand/plus/search/QuickSearchDialogFragment.java, OsmAnd/src/net/osmand/plus/search/QuickSearchListAdapter.java, OsmAnd/src/net/osmand/plus/search/QuickSearchListFragment.java
Locked superfluous accessibility events. Provided accessible direction
indication for search results.
=> New quick search accessibility enhancement

README.md
Buttons for F-Droid and Google Play Store
=> Add buttons to get the app in the README.md

OsmAnd/res/values/strings.xml
osmand_plus_extended_description_part1 contains the same text twice
=> duplication in strings.xml,  osmand_plus_extended_description_part1

OsmAnd/src/net/osmand/plus/routing/RouteProvider.java
Makes use of BRouter's capability of returning elevation information for a calculated route. This is helpful since OsmAnd's SRTM data is not considered when using BRouter.
=> Extracts elevation data from BRouter.

OsmAnd/src/net/osmand/plus/download/ui/ActiveDownloadsDialogFragment.java
=> Fix string

OsmAnd/res/values/strings.xml
Converts last remaining occurrences of 'OSM bugs' name. They are called Notes for some time now.
=> OSM bugs -> OSM Notes in strings.xml

OsmAnd/src/net/osmand/plus/myplaces/AvailableGPXFragment.java
IMHO, there is no sense in checking possible destinations list for
emptiness as soon as we always hav an option to create new one just in
this dialog. In any case an item that in some obscure circumstances
simply does nothing looks quirky.
=> GPX track moving action fix

OsmAnd/res/values-az/strings.xml
=> Revert "Update strings.xml"

OsmAnd-java/src/net/osmand/binary/GeocodingUtilities.java, OsmAnd-java/src/net/osmand/osm/MapRenderingTypes.java, OsmAnd-java/src/net/osmand/util/GeoPointParserUtil.java, OsmAnd-java/src/net/osmand/util/MapUtils.java, OsmAnd/no_translate.xml
Following #4104 (related to #3815)
=> Use HTTPS for OSM website

OsmAnd/res/values/styles.xml
Needed for Gradle plugin 3.0-alpha2 and above
=> Fix animation name attributes

OsmAnd/src/net/osmand/plus/download/DownloadFileHelper.java
=> Storage leak download fix #4656

OsmAnd/src/net/osmand/plus/activities/LocalIndexHelper.java, OsmAnd/src/net/osmand/plus/download/DownloadIndexesThread.java, OsmAnd/src/net/osmand/plus/download/DownloadResources.java, OsmAnd/src/net/osmand/plus/download/DownloadValidationManager.java, OsmAnd/src/net/osmand/plus/mapmarkers/adapters/MapMarkersGroupsAdapter.java, OsmAnd/src/net/osmand/plus/osmedit/dialogs/SendPoiDialogFragment.java
Minor things I stumbled over. For you to decide if it's worth taking/fixing or you'd rather leave it.
=> cosmetics: spelling fix and remove double semicolon.

ISSUE_TEMPLATE.md
Some minor changes in the `ISSUE_TEMPLATE.md`. Please see the commit messages, for detailed information.
=> Grammar, styling and typo fixes for the issue template

OsmAnd/src/net/osmand/plus/measurementtool/MeasurementEditingContext.java
Inside MeasurementEditingContext getParams() WptPt file was created without elevation data
=> Added Elevation data after Snap to Road inside MeasurementToolFragment

OsmAnd/src/net/osmand/plus/activities/FavoritesTreeFragment.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/MenuBuilder.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/FavouritePointMenuBuilder.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/WptPtMenuBuilder.java
made a group "All points  of the group" always show on top and button "show all" opens necessary group
=> Assign line items context menu

OsmAnd/src/net/osmand/plus/base/BasicProgressAsyncTask.java, OsmAnd/src/net/osmand/plus/download/DownloadFileHelper.java, OsmAnd/src/net/osmand/plus/download/DownloadIndexesThread.java
Currently, I get types of downloading maps from DownloadActivityType
=> added type of map to the contentText in downloading notification

OsmAnd/src/net/osmand/plus/mapcontextmenu/WikipediaDialogFragment.java
=> fixed bug with title language

OsmAnd/res/values/strings.xml
All fixes for the new strings, plus various others.
Additional conundrum:
<string name="monthly_map_updates">Map updates: <b>Every month</b></string>
<string name="daily_map_updates">Map updates: <b>Every hour</b></string>
There is no "weekly", even though it says weekly updates are a feature of the paid app.
=> Language rework 2

OsmAnd/res/values-de/phrases.xml
=> Update phrases.xml .de

OsmAnd/res/values/strings.xml
What does "aerial ways" mean, and what type of skiing is it?
Edit: Can the wiki be imported here?
=> New strings reworked 2

OsmAnd/res/values/strings.xml
=> Spelling: ": Reduced road thichness", "\'Topo\'", "ski lifts"

OsmAnd/res/values/strings.xml, OsmAnd/src/net/osmand/plus/ApplicationMode.java, OsmAnd/src/net/osmand/plus/OsmandSettings.java, OsmAnd/src/net/osmand/plus/routing/RouteCalculationResult.java, OsmAnd/src/net/osmand/plus/routing/RoutingHelper.java, OsmAnd/src/net/osmand/plus/views/MapInfoLayer.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/RouteInfoWidgetsFactory.java
This should probably get new icons as well, but I don't have any artistic skill.
=> Add map widget to show arrival time at first intermediate point

OsmAnd/res/values/strings.xml
Is there a "SRTM" plugin? Isn't it called "Contour lines" these days?
=> Fix Contour lines plugin name

OsmAnd/res/values/strings.xml
Some strings are just comments, should they be removed?
=> Spelling: RTL arrows in comments, and whitespace fixed, App restart

OsmAnd/res/values/strings.xml
I don't quite understand "(enter comment)".
=> Spelling: Tap, type, filename, location…, (comment)

OsmAnd/src/net/osmand/plus/views/MapTextLayer.java
=> Fix points text size on map

OsmAnd-telegram/src/net/osmand/telegram/TelegramSettings.kt, OsmAnd-telegram/src/net/osmand/telegram/helpers/ShareLocationHelper.kt, OsmAnd-telegram/src/net/osmand/telegram/helpers/TelegramHelper.kt, OsmAnd-telegram/src/net/osmand/telegram/ui/AddNewDeviceBottomSheet.kt, OsmAnd-telegram/src/net/osmand/telegram/ui/SettingsDialogFragment.kt, OsmAnd-telegram/src/net/osmand/telegram/utils/OsmandApiUtils.kt
=> Fix sharing bugs

OsmAnd/AndroidManifest.xml, OsmAnd/src/net/osmand/aidl/IOsmAndAidlInterface.aidl, OsmAnd/src/net/osmand/aidl/OsmandAidlApi.java, OsmAnd/src/net/osmand/aidl/OsmandAidlService.java, OsmAnd/src/net/osmand/aidl/tiles/ASqliteDbFile.java, OsmAnd/src/net/osmand/plus/ContextMenuAdapter.java, OsmAnd/src/net/osmand/plus/OsmAndAppCustomization.java, OsmAnd/src/net/osmand/plus/OsmAndCustomizationConstants.java, OsmAnd/src/net/osmand/plus/activities/MapActivityActions.java, OsmAnd/src/net/osmand/plus/dialogs/RasterMapMenu.java, OsmAnd/src/net/osmand/plus/osmedit/OsmEditingPlugin.java, OsmAnd/src/net/osmand/plus/parkingpoint/ParkingPositionPlugin.java, OsmAnd/src/net/osmand/plus/rastermaps/OsmandRasterMapsPlugin.java, OsmAnd/src/net/osmand/plus/views/ContextMenuLayer.java, gradle.properties
=> Ongoing Integration with StrikeLines-app

OsmAnd/AndroidManifest.xml, OsmAnd/assets/bundled_assets.xml, OsmAnd/res/values/strings.xml, OsmAnd/src/net/osmand/plus/activities/actions/StartGPSStatus.java, OsmAnd/src/net/osmand/plus/base/MapViewTrackingUtilities.java, OsmAnd/src/net/osmand/plus/views/TurnPathHelper.java
=> Bugfixes from Issues/3.3 milestone. Kolomiets branch

OsmAnd/res/layout-land/map_hud_bottom.xml, OsmAnd/res/layout/map_hud_bottom.xml, OsmAnd/src/net/osmand/plus/resources/IncrementalChangesManager.java, OsmAnd/src/net/osmand/plus/views/MapControlsLayer.java
=> Kolomiets branch

OsmAnd/res/values/strings.xml
=> Fixed typo

OsmAnd-java/src/main/java/net/osmand/data/Amenity.java
Fixes https://github.com/osmandapp/Osmand/issues/6395
=> Fix POI compare

OsmAnd/src/net/osmand/plus/quickaction/actions/MapOverlayAction.java, OsmAnd/src/net/osmand/plus/quickaction/actions/MapSourceAction.java, OsmAnd/src/net/osmand/plus/quickaction/actions/MapUnderlayAction.java
=> Quickaction issues

OsmAnd-java/src/main/java/net/osmand/util/Algorithms.java, OsmAnd/res/values/strings.xml, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/AmenityMenuBuilder.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/WptPtMenuBuilder.java, OsmAnd/src/net/osmand/plus/quickaction/actions/NavVoiceAction.java
=> Issues fixes 2

OsmAnd/src/net/osmand/plus/dialogs/RasterMapMenu.java, OsmAnd/src/net/osmand/plus/rastermaps/OsmandRasterMapsPlugin.java, OsmAnd/src/net/osmand/plus/routepreparationmenu/WaypointsFragment.java, OsmAnd/src/net/osmand/plus/views/MapControlsLayer.java
a couple of small issues:
https://github.com/osmandapp/Osmand/issues/6493
https://github.com/osmandapp/Osmand/issues/6485
=> Issues fixes #6493 and #6485

OsmAnd-java/src/main/java/net/osmand/util/GeoPointParserUtil.java, OsmAnd-java/src/main/java/net/osmand/util/LocationParser.java, OsmAnd-java/src/test/java/net/osmand/util/GeoPointParserUtilTest.java
Couple of issues with latlon parsing (see commit titles)
=> Latlon parsing issues

OsmAnd/res/values/strings.xml, OsmAnd/src/net/osmand/plus/osmedit/EditPoiDialogFragment.java
Add warning dialog and prevent saving of POI edits if any of fields exceed OSM limit of 255 chars per tag.
=> Issue #6520 Add warning dialog

OsmAnd/src/net/osmand/plus/osmedit/AdvancedEditPoiFragment.java, OsmAnd/src/net/osmand/plus/osmedit/BasicEditPoiFragment.java, OsmAnd/src/net/osmand/plus/osmedit/EditPoiDialogFragment.java
value check logic and add length filters to editText fields in simple and advanced edit poi fragments
=> fix for #6520

OsmAnd/res/values/phrases.xml
The issue "https://github.com/osmandapp/Osmand/issues/6581" is still partially not fixed.
=> fixed letter-error "radiotherapHy"

OsmAnd/res/layout/fragment_measurement_tool.xml, OsmAnd/src/net/osmand/plus/liveupdates/PerformLiveUpdateAsyncTask.java, OsmAnd/src/net/osmand/plus/measurementtool/MeasurementToolFragment.java
logging for #6201 
ui fix for measurement tool
=> Issues fixes

OsmAnd/res/values/phrases.xml
string is "no" and so also the text should be "no"
=> fix two `Multi-pitch routes: yes`

OsmAnd/src/net/osmand/plus/NavigationService.java, OsmAnd/src/net/osmand/plus/OnNavigationServiceAlarmReceiver.java
Already solves issues on some devices, and should create the basis for solving 5532.
=> Use setExact for long-interval recording

OsmAnd/src/net/osmand/plus/AppInitializer.java, OsmAnd/src/net/osmand/plus/NavigationService.java, OsmAnd/src/net/osmand/plus/OsmandApplication.java, OsmAnd/src/net/osmand/plus/monitoring/OsmandMonitoringPlugin.java
see https://github.com/osmandapp/Osmand/issues/5632?_pjax=%23js-repo-pjax-container#issuecomment-490769071
=> Issue 5632 Workaround

OsmAnd/src/net/osmand/plus/routepreparationmenu/AddPointBottomSheetDialog.java, OsmAnd/src/net/osmand/plus/routepreparationmenu/MapRouteInfoMenu.java
change my position icon in road preparation bottomsheet depending on location permission and ask for permission if none.
=> Rp mylocation

OsmAnd/res/layout/bottom_sheet_item_with_descr_and_radio_btn.xml, OsmAnd/res/layout/profile_list_item.xml, OsmAnd/src/net/osmand/plus/ApplicationMode.java, OsmAnd/src/net/osmand/plus/activities/SettingsBaseActivity.java, OsmAnd/src/net/osmand/plus/activities/SettingsNavigationActivity.java, OsmAnd/src/net/osmand/plus/monitoring/SettingsMonitoringActivity.java, OsmAnd/src/net/osmand/plus/profiles/AppModesBottomSheetDialogFragment.java, OsmAnd/src/net/osmand/plus/profiles/AppProfileArrayAdapter.java
=> Added new profile selection dialog to navigational settings menu

OsmAnd/res/values/strings.xml, OsmAnd/src/net/osmand/plus/quickaction/actions/MapStyleAction.java
fix for - Crash quick action Map Layer #6884
=> fix for #6884

OsmAnd/src/net/osmand/plus/profiles/AppModesBottomSheetDialogFragment.java, OsmAnd/src/net/osmand/plus/profiles/ProfileMenuAdapter.java, OsmAnd/src/net/osmand/plus/profiles/SettingsProfileFragment.java
=> fix for icons color glitch

OsmAnd/res/values/strings.xml, OsmAnd/src/net/osmand/access/SettingsAccessibilityActivity.java, OsmAnd/src/net/osmand/plus/OsmandSettings.java, OsmAnd/src/net/osmand/plus/activities/MapActivity.java, OsmAnd/src/net/osmand/plus/routepreparationmenu/MapRouteInfoMenu.java
Hi,
I'm one of the developers of the [WunderLINQ](http://www.wunderlinq.com).  The WunderLINQ enables you to use your motorcycle's handlebar controls to control your smartphone.  Essentially the device acts as a Bluetooth keyboard so I tried to mirror the code for the Parrot device.
Here is a video of the integration in action: [https://youtu.be/gTXtVagOQqk](https://youtu.be/gTXtVagOQqk)
=> Add WunderLINQ support, handlebar control of your smartphone

OsmAnd/res/layout/fragment_selected_profile.xml, OsmAnd/res/layout/preference_activity.xml, OsmAnd/res/layout/profile_list_item.xml, OsmAnd/res/values/colors.xml, OsmAnd/res/values/strings.xml, OsmAnd/res/values/styles.xml, OsmAnd/src/net/osmand/plus/ApplicationMode.java, OsmAnd/src/net/osmand/plus/activities/SettingsBaseActivity.java, OsmAnd/src/net/osmand/plus/activities/actions/AppModeDialog.java, OsmAnd/src/net/osmand/plus/profiles/AppProfileArrayAdapter.java, OsmAnd/src/net/osmand/plus/profiles/EditProfileFragment.java, OsmAnd/src/net/osmand/plus/profiles/ProfileDataObject.java, OsmAnd/src/net/osmand/plus/profiles/ProfileMenuAdapter.java, OsmAnd/src/net/osmand/plus/profiles/RoutingProfileDataObject.java, OsmAnd/src/net/osmand/plus/profiles/SettingsProfileFragment.java, OsmAnd/src/net/osmand/plus/quickaction/actions/NavStartStopAction.java, OsmAnd/src/net/osmand/plus/views/MapControlsLayer.java
=> Profile select color

OsmAnd/src/net/osmand/data/PointDescription.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/MenuBuilder.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/MenuController.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/AmenityMenuBuilder.java
=> 7051 expand coordnates

OsmAnd/src/net/osmand/plus/FavouritesDbHelper.java
=> fix for issue 6971

OsmAnd/src/net/osmand/plus/voice/TTSCommandPlayerImpl.java
crash on samsung when there is no selected locale
=> Issue 7011

OsmAnd/src/net/osmand/data/PointDescription.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/MenuBuilder.java
is it enough? Maybe there is some "universal" Locale that available for all cases for tts?
=> crash fixes

OsmAnd/src/net/osmand/plus/activities/FavoritesTreeFragment.java, OsmAnd/src/net/osmand/plus/activities/MapActivity.java, OsmAnd/src/net/osmand/plus/audionotes/NotesFragment.java, OsmAnd/src/net/osmand/plus/audionotes/adapters/NotesAdapter.java, OsmAnd/src/net/osmand/plus/helpers/ImportHelper.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/FavouritePointMenuBuilder.java, OsmAnd/src/net/osmand/plus/myplaces/AvailableGPXFragment.java, OsmAnd/src/net/osmand/plus/myplaces/FavoritesActivity.java, OsmAnd/src/net/osmand/plus/osmedit/OsmEditsAdapter.java, OsmAnd/src/net/osmand/plus/osmedit/OsmEditsFragment.java
If its normal implementation will refactor for favorites and tracks tabs
=> Issue 6967

OsmAnd/build.gradle, OsmAnd/res/values-ca/strings.xml, OsmAnd/res/values-hy/strings.xml, OsmAnd/res/values-ro/strings.xml, OsmAnd/res/values-tr/strings.xml
Found and fixed several similar issues, add rule to gradle test
=> #7082 - error in string formatting "% s". 

OsmAnd/src/net/osmand/plus/routing/RouteProvider.java
Get turn instructions and travel time estimation from BRouter.
The default travel time calculation was wrong if BRouter is the Navigation service and has no times (e.g. older BRouter version).
=> Turn instructions and travel time from BRouter

OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/AmenityMenuBuilder.java, OsmAnd/src/net/osmand/plus/views/MapTextLayer.java
=> Ui issues fix #6948 #6912

OsmAnd/src/net/osmand/plus/routing/RouteProvider.java
set the right modes for BRouter with the new Aplication Profiles
=> modes for BRouter

OsmAnd/res/layout/fragment_selected_profile.xml, OsmAnd/res/values/strings.xml, OsmAnd/src/net/osmand/data/PointDescription.java, OsmAnd/src/net/osmand/plus/OsmAndFormatter.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/MenuBuilder.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/MenuController.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/AmenityMenuBuilder.java
+ missed string res for profiles
=> Coord formatter

OsmAnd/res/values/strings.xml, OsmAnd/res/xml/general_settings.xml, OsmAnd/src/net/osmand/access/SettingsAccessibilityActivity.java, OsmAnd/src/net/osmand/plus/OsmandSettings.java, OsmAnd/src/net/osmand/plus/activities/MapActivity.java, OsmAnd/src/net/osmand/plus/activities/SettingsGeneralActivity.java
Added External Input Device support for Generic, WunderLINQ and Parrot devices
Removed Parrot setting from Accessibility Plugin
This mimics the UI/logic of the iOS patch.
=> Add External Input Device support

OsmAnd/src/net/osmand/plus/activities/actions/StartGPSStatus.java
Removed Apps which are no longer available and added GPSTest(#5775).
=> Updated GpsStatusApps

OsmAnd/src/net/osmand/plus/notifications/NavigationNotification.java, OsmAnd/src/net/osmand/plus/quickaction/actions/NavResumePauseAction.java
… problem in the end of navigation.
=> Fix NavigationNotification and NavResumePauseAction continue button behavior

OsmAnd/res/values/colors.xml, OsmAnd/src/net/osmand/plus/mapmarkers/MapMarkersHistoryFragment.java, OsmAnd/src/net/osmand/plus/mapmarkers/adapters/MapMarkersActiveAdapter.java, OsmAnd/src/net/osmand/plus/mapmarkers/adapters/MapMarkersGroupsAdapter.java, OsmAnd/src/net/osmand/plus/mapmarkers/adapters/MapMarkersHistoryAdapter.java, OsmAnd/src/net/osmand/plus/routepreparationmenu/MapRouteInfoMenu.java
refactor Route Preparation "start" button text and icon color
refactor MapMarkers -> Group -> Marker text color
refactor Map markers -> Done -> Toast background and "undo" button color
=> Refactor Colors

OsmAnd/res/layout/main_menu_drawer_btn_configure_profile.xml, OsmAnd/res/layout/main_menu_drawer_btn_switch_profile.xml, OsmAnd/res/layout/profile_preference_toolbar_big.xml, OsmAnd/src/net/osmand/plus/activities/MapActivityActions.java, OsmAnd/src/net/osmand/plus/settings/ConfigureProfileFragment.java
Change "Configure profile" button text typeface to "medium"
Configure profile - opens Configure profile screen
=> Profile Drawer Updates

OsmAnd/src/net/osmand/plus/routepreparationmenu/MapRouteInfoMenu.java
=> fix start button text and icon color while route calculated

OsmAnd/src/net/osmand/plus/ApplicationMode.java, OsmAnd/src/net/osmand/plus/OsmandSettings.java, OsmAnd/src/net/osmand/plus/profiles/AppModesBottomSheetDialogFragment.java, OsmAnd/src/net/osmand/plus/profiles/EditProfileFragment.java, OsmAnd/src/net/osmand/plus/profiles/SettingsProfileFragment.java
=> Revert "Change routing profile in default app modes"

OsmAnd-java/src/main/java/net/osmand/router/RoutingContext.java
=> fix for slow excluded id check

OsmAnd/res/values/strings.xml
=> Typo fixed

OsmAnd/src/net/osmand/plus/settings/DataStorageFragment.java, OsmAnd/src/net/osmand/plus/settings/DataStorageHelper.java, OsmAnd/src/net/osmand/plus/settings/DataStorageMemoryItem.java, OsmAnd/src/net/osmand/plus/settings/GlobalSettingsFragment.java
Fix screen hang during calculation bug (add a timer)
Fix UI refreshing stop after screen flipping bug
=> Data Storage

OsmAnd/src/net/osmand/plus/helpers/ImportHelper.java
=> fixed getNameFromContentUri fixes #7624 and #6598

OsmAnd-java/src/main/java/net/osmand/router/GeneralRouter.java
=> add min/max speed to routingSpeed #7230

OsmAnd/res/values-ru/strings.xml, OsmAnd/res/values-uk/strings.xml, OsmAnd/res/values/strings.xml, OsmAnd/src/net/osmand/plus/quickaction/QuickActionFactory.java, OsmAnd/src/net/osmand/plus/quickaction/actions/NavDirectionsFromAction.java
Implement feature of Issue #7646
=> Issue #7646 Quick Action button  "Directions from"

OsmAnd/res/layout/bottom_sheet_item_with_radio_btn.xml, OsmAnd/res/layout/bottom_sheet_item_with_radio_btn_left.xml, OsmAnd/res/layout/preference_radio_button.xml
Black radio buttons Android 4.4
=> Fix 7807 Many Dark theme radio buttons still invisible

OsmAnd/res/layout/list_item_icon_and_switch.xml, OsmAnd/res/layout/list_item_text_button.xml, OsmAnd/src/net/osmand/plus/views/mapwidgets/MapWidgetRegistry.java
add lost marker divider & fix coordinate widget divider
=> fix lost divider

OsmAnd/res/values/strings.xml
I know it should be unmaintained but "unmainted" could be a thing so I'm not sure it's actually a mistake.
Feel free to close this if it's irrelevant.
Thanks!
=> Fixed typo (or is it?)

OsmAnd/res/layout/bottom_sheet_item_simple.xml, OsmAnd/res/layout/bottom_sheet_item_simple_56dp.xml, OsmAnd/res/layout/bottom_sheet_item_with_radio_btn_left.xml, OsmAnd/res/layout/global_preferences_toolbar_with_switch.xml, OsmAnd/res/layout/profile_preference_toolbar.xml, OsmAnd/res/layout/profile_preference_toolbar_big.xml, OsmAnd/res/layout/profile_preference_toolbar_with_switch.xml, OsmAnd/src/net/osmand/plus/settings/BaseSettingsFragment.java
=> Support multiline description

OsmAnd/src/net/osmand/plus/OsmandSettings.java
=> Small fix for keep screen on option

OsmAnd/src/net/osmand/plus/activities/MapActivity.java, OsmAnd/src/net/osmand/plus/helpers/ScrollHelper.java
Add continuous and single scrolling
=> External Input Device

OsmAnd/res/layout/save_gpx_dialog.xml, OsmAnd/src/net/osmand/plus/measurementtool/MeasurementToolFragment.java
Fix text color Measurement Tool -> "show on map after saving"
=> Fix text color

OsmAnd/res/values-en-rGB/strings.xml, OsmAnd/res/values/strings.xml
Hopefully these can still be included in 3.7, and [one of the screenshots for the release announcement](https://github.com/osmandapp/osmandapp.github.io/blob/0a481fd9dfb10c691b2d207a99fd5d61ed02233d/website/images/blog/3.7/1.jpg) can be updated too :)
=> Typo fixes and improvements for English strings, and minor additions to en-GB strings

OsmAnd/res/values/strings.xml
These are fixes for a few English strings that I felt were awkwardly worded.
=> Minor string fixes

OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/PointEditorFragmentNew.java
=>  Fix Favorites/GPX waypoint editing dialog does not show Save button

OsmAnd/src/net/osmand/plus/views/RouteLayer.java
2.25 is the ratio of the stroke size compared to the image size.
=> FIX: rescale arrow if stroke is too large

OsmAnd-api/src/net/osmand/aidlapi/IOsmAndAidlInterface.aidl, OsmAnd-api/src/net/osmand/aidlapi/lock/SetLockStateParams.aidl, OsmAnd-api/src/net/osmand/aidlapi/lock/SetLockStateParams.java, OsmAnd/src/net/osmand/aidl/IOsmAndAidlInterface.aidl, OsmAnd/src/net/osmand/aidl/OsmandAidlApi.java, OsmAnd/src/net/osmand/aidl/OsmandAidlService.java, OsmAnd/src/net/osmand/aidl/OsmandAidlServiceV2.java, OsmAnd/src/net/osmand/aidl/lock/SetLockStateParams.aidl, OsmAnd/src/net/osmand/aidl/lock/SetLockStateParams.java, OsmAnd/src/net/osmand/plus/helpers/LockHelper.java
For instance it can allow a service to wake up the navigation using media buttons
=> Add aidl interface to lock and unlock the screen.

OsmAnd/src/net/osmand/aidl/OsmandAidlApi.java
Keys for KEY_ON_VOICE_MESSAGE  and KEY_ON_KEY_EVENT must be power of two
=> Fix key callback code

OsmAnd/res/values/phrases.xml
As per
https://en.wikipedia.org/wiki/Korfball
https://en.wikipedia.org/wiki/Drive-in
https://en.wikipedia.org/wiki/Charity_shop
https://en.wikipedia.org/wiki/Diesel_exhaust_fluid
=> Spelling: Updates to Phrases from comments

OsmAnd/src/net/osmand/plus/parkingpoint/ParkingPositionPlugin.java
Issue #5374 fixed. Date is now displayed in format "hh:mm dd.MM.yyyy"
=> issue 5374 show the date parked fix

OsmAnd/src/net/osmand/plus/monitoring/OsmandMonitoringPlugin.java
Added 20 seconds option for the Logging interval during navigation setting
=> Added 20 seconds option for the Logging interval during navigation setting

OsmAnd/res/values/strings.xml, OsmAnd/res/xml/accessibility_settings.xml, OsmAnd/src/net/osmand/plus/routing/RoutingHelper.java, OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java, OsmAnd/src/net/osmand/plus/settings/fragments/RouteParametersFragment.java
1) Removed settings item for recalculation menu from **accessibility** 
2) Recalculation parameters are added to **route parameters** section
3) Implementation of _recalculation on wrong direction_ feature
4) UI fixes, strings changed
=> no route recalculation wrong direction issue fix

OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java, OsmAnd/src/net/osmand/plus/settings/fragments/RouteParametersFragment.java
Switch bug fix and UI improvements
=> Issue 9539 Switch bug fix

AUTHORS.md, ISSUE_TEMPLATE.md, LICENSE, README.md
Fixed up a bunch of old links, grammar, and formatting.
=> Update grammar and links in multiple files

OsmAnd/src/net/osmand/plus/views/layers/ContextMenuLayer.java, OsmAnd/src/net/osmand/plus/views/layers/MapControlsLayer.java
Show "My Position" context menu fragment when long tap on location button. Don't show "Whats here" menu
=> Fix #9408 Don't show "Whats here" menu

OsmAnd/src/net/osmand/plus/dialogs/ConfigureMapMenu.java
=> Added Kannada to Map language

OsmAnd/res/layout/map_context_menu_fragment.xml, OsmAnd/src/net/osmand/plus/mapcontextmenu/controllers/FavouritePointMenuController.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/PointEditorFragmentNew.java, OsmAnd/src/net/osmand/view/GravityDrawable.java
1. Skip first direction, then coma - address. (its important changes: some menu items looks ugly);
2. After the user tap on the text field, place the cursor at the end of the text;
3. Align draw able icon.
=> Add_favorite_screen

.github/ISSUE_TEMPLATE/2-faq-report.md, .github/ISSUE_TEMPLATE/3-bug-report.md, .github/ISSUE_TEMPLATE/4-routing-report.md, .github/ISSUE_TEMPLATE/5-feature-request.md
Minor fixes in markdown files.
=> Improve bug templates

OsmAnd-java/src/main/java/net/osmand/router/RoutePlannerFrontEnd.java, OsmAnd-java/src/main/java/net/osmand/router/RouteSegmentResult.java, OsmAnd/src/net/osmand/plus/routing/RouteCalculationResult.java
https://github.com/osmandapp/OsmAnd-Issues/issues/158
Strange point in the ocean after manual attach thru "Plan a route". - !!! CHECK FIXME !!!
=> Issues 158 no ele after attach

OsmAnd/src/net/osmand/plus/measurementtool/MeasurementToolFragment.java, OsmAnd/src/net/osmand/plus/measurementtool/SavedTrackBottomSheetDialogFragment.java, OsmAnd/src/net/osmand/plus/routepreparationmenu/FollowTrackFragment.java
=> Plan route fixes

OsmAnd-java/src/main/java/net/osmand/router/RoutingContext.java, OsmAnd-java/src/test/java/net/osmand/router/RouteTestingTest.java
Issue 9844 oneway is not respected
=> Issue 9844 oneway is not respected

OsmAnd/src/net/osmand/plus/settings/fragments/MainSettingsFragment.java
@vshcherb , @Chumva , here goes another one ✌️
=> #9537 Use a profile color to highlight the selected profile

OsmAnd-java/src/main/java/net/osmand/util/Algorithms.java, OsmAnd/src/net/osmand/plus/monitoring/LiveMonitoringHelper.java, OsmAnd/src/net/osmand/plus/monitoring/SettingsMonitoringActivity.java, OsmAnd/src/net/osmand/plus/settings/fragments/LiveMonitoringFragment.java
=> #9621 Add validation for the online tracking link

OsmAnd/res/layout/bottom_sheet_item_slider_with_two_text.xml
=> #9984 Fix overlapping text

OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/cards/IPFSImageCard.java, OsmAnd/src/net/osmand/plus/osmedit/SettingsOsmEditingActivity.java
=> Issues 201 opr show image added icon

OsmAnd/res/values/strings.xml, OsmAnd/src/net/osmand/plus/settings/fragments/RouteParametersFragment.java
https://github.com/osmandapp/OsmAnd-Issues/issues/136
=> Add icon, string

OsmAnd/src/net/osmand/plus/settings/fragments/ImportSettingsFragment.java
https://github.com/osmandapp/OsmAnd-Issues/issues/257
=> Crash on profile import

OsmAnd/res/layout/send_gpx_fragment.xml
Increase padding between text field and hint text for 2dp.
=> Fix space texthelper

OsmAnd/src/net/osmand/plus/helpers/IntentHelper.java, OsmAnd/src/net/osmand/plus/myplaces/FavoritesActivity.java, OsmAnd/src/net/osmand/plus/osmedit/OsmEditingFragment.java, OsmAnd/src/net/osmand/plus/osmedit/dialogs/SendGpxBottomSheetFragment.java, OsmAnd/src/net/osmand/plus/osmedit/dialogs/SendOsmNoteBottomSheetFragment.java, OsmAnd/src/net/osmand/plus/osmedit/dialogs/SendPoiBottomSheetFragment.java
Redirect to OSM Settings on acccount click
=> Account button on OSM Bottom Sheets

OsmAnd/res/layout/custom_radio_buttons.xml, OsmAnd/res/layout/fragment_measurement_tool.xml, OsmAnd/src/net/osmand/plus/UiUtilities.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/other/HorizontalSelectionAdapter.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/other/TrackDetailsMenu.java, OsmAnd/src/net/osmand/plus/measurementtool/MeasurementToolFragment.java
1. Primary button (Add, Apply): minimum width size 64dp, left/right inner margins = 16dp
2. Lost divider between the top and bottom parts of the menu.
3. Scrollable toggles, graph switchers: left/right inner margins = 16dp (make it default value)
4. Menu shouldn't auto close when user add a new point
5. Убрать красные точки во время просмотра графика (точка = засечка на графике)
6. Toggle "Points/Graph" should be visible when the menu is closed. Tap in "Point" or "Graph" button should open Point or graph.
=> Plan Route Fix UI margins

OsmAnd/res/layout/custom_radio_buttons.xml, OsmAnd/res/layout/fragment_measurement_tool.xml, OsmAnd/src/net/osmand/plus/UiUtilities.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/other/HorizontalSelectionAdapter.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/other/TrackDetailsMenu.java, OsmAnd/src/net/osmand/plus/measurementtool/MeasurementToolFragment.java
Reverts osmandapp/OsmAnd#10249
=> Revert "Plan Route Fix UI margins"

OsmAnd/src/net/osmand/plus/mapcontextmenu/MenuBuilder.java, OsmAnd/src/net/osmand/plus/osmedit/opr/OpenDBAPI.java
=> Issue 251 android add photo backend part2

OsmAnd/src/net/osmand/AndroidUtils.java, OsmAnd/src/net/osmand/plus/settings/bottomsheets/ElevationDateBottomSheet.java
=> Combine use elevation data

OsmAnd/res/layout/bottom_sheet_menu_base.xml, OsmAnd/res/layout/send_gpx_fragment.xml, OsmAnd/src/net/osmand/plus/base/MenuBottomSheetDialogFragment.java, OsmAnd/src/net/osmand/plus/osmedit/dialogs/SendGpxBottomSheetFragment.java, OsmAnd/src/net/osmand/plus/settings/bottomsheets/VehicleParametersBottomSheet.java
1. Bottom sheet should scroll outside the screen
2. Check keyboard doesn't show after open
3. If the bottom sheet contains "text field" taping on it will show the keyboard, bottom sheet main buttons should be above the keyboard.
=> Bottomsheet: should scroll outside the screen, buttons behavior with keyboard

OsmAnd/res/layout/settings_group_title.xml, OsmAnd/src/net/osmand/plus/settings/fragments/ExportItemsBottomSheet.java
1. Bottom sheet, the title is jumping, when the quantity of items or size is changing.
2. Bottom sheet, title: Check font size, letter space for quantity/size text.
3. Show size for "Audio/Video" notes
4. Maps: use "•" instead of "*".
=> Export UI Items

OsmAnd/src/net/osmand/plus/wikivoyage/data/TravelObfHelper.java
Implemented search by name functionality in TravelObfHelper
=> Issue 295 TravelObfHelper articles search by name

OsmAnd/src/net/osmand/plus/activities/PluginsFragment.java
+ Add 3 dots in the  end of the text
=> Plugins screen: description text is scrollable but not tappable.

OsmAnd/src/net/osmand/plus/osmedit/oauth/OsmOAuthAuthorizationAdapter.java, OsmAnd/src/net/osmand/plus/osmedit/oauth/OsmOAuthHelper.java
=> Fix crash OAuth OpenStreetMap

OsmAnd/src/net/osmand/plus/onlinerouting/OnlineRoutingHelper.java, OsmAnd/src/net/osmand/plus/onlinerouting/OnlineRoutingUtils.java, OsmAnd/src/net/osmand/plus/onlinerouting/engine/GraphhopperEngine.java, OsmAnd/src/net/osmand/plus/onlinerouting/engine/OnlineRoutingEngine.java, OsmAnd/src/net/osmand/plus/onlinerouting/ui/OnlineRoutingEngineFragment.java, OsmAnd/src/net/osmand/plus/settings/backend/backup/OnlineRoutingSettingsItem.java
=> Fix Import / Export bugs with Online Routing

OsmAnd/res/layout/subscription_fragment.xml, OsmAnd/res/layout/two_line_with_images_list_item.xml
"Get" button in "Downloads.
OsmAnd Live screen after purchase.
=> Missed text in UI

.github/ISSUE_TEMPLATE/config.yml
Follow-up of #10776. Sorry about that :).
=> Fix config.yml syntax

OsmAnd/res/layout/gpx_track_item.xml, OsmAnd/res/layout/wpt_list_item.xml
[Unnecessary scroll bars](https://github.com/osmandapp/OsmAnd-Issues/issues/464)
=> scrollbars="none"

OsmAnd-java/src/main/java/net/osmand/binary/BinaryMapPoiReaderAdapter.java, OsmAnd-java/src/main/java/net/osmand/binary/OsmandOdb.java, OsmAnd-java/src/main/java/net/osmand/util/MapUtils.java
Implement precision of 26 zoom on Android
=> Implement precision result from 26 zoom

OsmAnd-java/src/main/java/net/osmand/map/WorldRegion.java, OsmAnd/src/net/osmand/plus/download/DownloadResources.java, OsmAnd/src/net/osmand/plus/download/MultipleIndexesUiHelper.java
Don't show country name in for the maps: "Germany Bavaria" > "Bavaria"
=> Add "Russia", "Canada", "USA"

OsmAnd/res/layout/two_line_with_images_list_item.xml
=> Everything in Help Section has a blue box

OsmAnd/res/values/strings.xml, OsmAnd/src/net/osmand/plus/quickaction/QuickActionRegistry.java, OsmAnd/src/net/osmand/plus/quickaction/actions/ShowHideCoordinatesWidgetAction.java
https://github.com/osmandapp/OsmAnd/issues/10196
=> Feature Request: Add "Coordinates widget" toggle to Quick action button

OsmAnd/src/net/osmand/plus/wikipedia/WikiArticleHelper.java
=> Fix description

OsmAnd-java/src/main/java/net/osmand/router/RouteColorize.java
Added class for colorization of route
=> Gradient colorization for route

OsmAnd-java/src/main/java/net/osmand/binary/RouteDataObject.java, OsmAnd/src/net/osmand/data/FavouritePoint.java, OsmAnd/src/net/osmand/plus/FavouritesDbHelper.java, OsmAnd/src/net/osmand/plus/importfiles/FavoritesImportTask.java, OsmAnd/src/net/osmand/plus/importfiles/ImportHelper.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/MapContextMenu.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/FavoritePointEditor.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/FavoritePointEditorFragment.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/FavoritePointEditorFragmentNew.java, OsmAnd/src/net/osmand/plus/quickaction/actions/FavoriteAction.java
not final, first commit to check
=> Adding altitude and timestamp to new favorite

OsmAnd/res/layout/add_new_favorite_category.xml, OsmAnd/res/layout/bottom_sheet_item_with_descr_and_radio_btn.xml, OsmAnd/res/values/strings.xml, OsmAnd/src/net/osmand/plus/activities/MapActivity.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/AddNewFavoriteCategoryBottomSheet.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/PointEditorFragment.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/PointEditorFragmentNew.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/SelectFavoriteCategoryBottomSheet.java
https://github.com/osmandapp/OsmAnd/issues/10835
Still in progress
=> Base Choose category and Add new category

OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/SelectFavoriteCategoryBottomSheet.java
https://github.com/osmandapp/OsmAnd/issues/10835
=> Fix bug addwaypoint

OsmAnd/AndroidManifest.xml, OsmAnd/build-common.gradle, OsmAnd/src-google/net/osmand/plus/inapp/InAppPurchaseHelperImpl.java, OsmAnd/src-huawei/net/osmand/plus/inapp/InAppPurchaseHelperImpl.java, OsmAnd/src/net/osmand/plus/inapp/InAppPurchaseHelper.java, OsmAnd/src/net/osmand/plus/inapp/InAppPurchases.java, OsmAnd/src/net/osmand/plus/inapp/util/BillingManager.java
[Application](https://play.google.com/apps/test/RQK6dtCijIQ/ahAIsfLrxGVf1PtJLHh1lOuVDFV9jcV33WLQfAiSdjd--qsGl1k4_Ggi3tCwj06z1BG9CGR1APdwEcqFi3n3Iy6857) if needed
=> Billing library 3

OsmAnd/src/net/osmand/plus/settings/fragments/ProfileAppearanceFragment.java
If custom color not choose and screen orientation rotate:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
at net.osmand.plus.settings.fragments.ProfileAppearanceFragment.saveState(ProfileAppearanceFragment.java:316)
```
=> NullPointExcepionFix ProfileAppearanceFragment 

OsmAnd/src/net/osmand/plus/UiUtilities.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/MapMarkersWidgetsFactory.java
https://github.com/osmandapp/OsmAnd/issues/10961
=> wrong direction marker toolbar

OsmAnd/src/net/osmand/plus/ContextMenuItem.java
https://github.com/osmandapp/OsmAnd-Issues/issues/512
=> Icons in Configure Map / Screen

OsmAnd/src/net/osmand/plus/activities/PluginsFragment.java, OsmAnd/src/net/osmand/plus/dialogs/PluginInstalledBottomSheetDialog.java
https://github.com/osmandapp/OsmAnd-Issues/issues/489
=> New plugin added dialog missing plugin icon

OsmAnd/res/layout/enough_space_warning_card.xml, OsmAnd/res/layout/select_folder_row.xml
https://github.com/osmandapp/OsmAnd/issues/10986
=> Osmand crashes on Export / Import

OsmAnd/src/net/osmand/plus/dialogs/MapLayerMenuListener.java
https://github.com/osmandapp/OsmAnd-Issues/issues/516
=> Wrong POI Multiselection after 1 selection

OsmAnd/res/values-nl/strings.xml
=> Fix typo in dutch translation

OsmAnd/src/net/osmand/plus/routepreparationmenu/MapRouteInfoMenu.java
https://github.com/osmandapp/OsmAnd-Issues/issues/186
=>  Remove "Swap" button from RP if "Follow track"

OsmAnd/src/net/osmand/plus/UiUtilities.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/MapContextMenuFragment.java
https://github.com/osmandapp/OsmAnd/issues/10961
=> wrong direction contextmenu item

OsmAnd/src/net/osmand/plus/audionotes/AudioVideoNotesPlugin.java
https://github.com/osmandapp/OsmAnd/issues/9883
=> wrong recording note button is shown on profile change

OsmAnd/src/net/osmand/plus/routepreparationmenu/cards/TrackEditCard.java
```
java.lang.IndexOutOfBoundsException: Index: 3, Size: 2
at java.util.ArrayList.get(ArrayList.java:437)
at net.osmand.plus.routepreparationmenu.cards.TrackEditCard.updateContent(TrackEditCard.java:92)
```
=> IndexOutOfBoundsException

OsmAnd-java/src/main/java/net/osmand/data/MapObject.java
Allow to disable en transliteration
=> Allow to disable en transliteration

OsmAnd/res/layout-land/fragment_measurement_tool.xml, OsmAnd/res/layout/fragment_measurement_tool.xml
+ Move point screen: fix "Apply" button width in landscape and portrait.
+ Fix Add button width in landscape mode
https://github.com/osmandapp/OsmAnd-Issues/issues/186
=> Plan route issues

README.md
Looks like an error - there is no opening tag.
=> README.md: remove extra p closing tag

OsmAnd-java/src/main/java/net/osmand/router/BinaryRoutePlanner.java
Fix https://github.com/osmandapp/OsmAnd/issues/10867
=> Compute obstaclesTime before adding final segment

OsmAnd-java/src/main/java/net/osmand/router/BinaryRoutePlanner.java
Reverts osmandapp/OsmAnd#11171
=> Revert "Compute obstaclesTime before adding final segment"

OsmAnd/src/net/osmand/plus/wikivoyage/explore/ExploreRvAdapter.java, OsmAnd/src/net/osmand/plus/wikivoyage/explore/ExploreTabFragment.java, OsmAnd/src/net/osmand/plus/wikivoyage/explore/WikivoyageExploreActivity.java
**For more smoothy update recycle view:**
`notifyItemRangeChanged(getNeededMapsCardPosition(), items.size());`
=> Travel: Maps you need card, popular articles jumping

OsmAnd/res/layout/abc_list_menu_item_icon.xml
https://github.com/osmandapp/OsmAnd/issues/11198
=> RTL issue - Menu misalignment

OsmAnd/src/net/osmand/plus/routepreparationmenu/MapRouteInfoMenuFragment.java, OsmAnd/src/net/osmand/plus/routepreparationmenu/cards/TracksCard.java, OsmAnd/src/net/osmand/plus/track/TrackMenuFragment.java
https://github.com/osmandapp/OsmAnd-Issues/issues/518
=> Displayed tracks

OsmAnd/src/net/osmand/plus/quickaction/QuickActionListFragment.java
https://github.com/osmandapp/OsmAnd/issues/10196
=> Quick action list fix for show/hide for editable items

OsmAnd/res/values/strings.xml
"Please follow this link if you any issues with purchases." is missing "have".
=> Add missing word

OsmAnd/src/net/osmand/plus/settings/datastorage/DataStorageFragment.java, OsmAnd/src/net/osmand/plus/srtmplugin/TerrainFragment.java
https://github.com/osmandapp/OsmAnd/issues/11212
=> Text direction

OsmAnd/res/values/strings.xml, OsmAnd/src/net/osmand/plus/quickaction/actions/MapStyleAction.java, OsmAnd/src/net/osmand/plus/rastermaps/MapOverlayAction.java, OsmAnd/src/net/osmand/plus/rastermaps/MapSourceAction.java, OsmAnd/src/net/osmand/plus/rastermaps/MapUnderlayAction.java
https://github.com/osmandapp/OsmAnd/issues/10473
=> Quick action map: suggestion to display current map name

OsmAnd/res/layout/profile_preference_toolbar_with_switch.xml, OsmAnd/res/values/strings.xml, OsmAnd/res/xml/voice_announces.xml, OsmAnd/src/net/osmand/plus/routing/VoiceRouter.java, OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java, OsmAnd/src/net/osmand/plus/settings/fragments/BaseSettingsFragment.java, OsmAnd/src/net/osmand/plus/settings/fragments/ScreenAlertsFragment.java, OsmAnd/src/net/osmand/plus/settings/fragments/VoiceAnnouncesFragment.java
https://github.com/osmandapp/OsmAnd/issues/9592
=> Voice prompts

OsmAnd/src/net/osmand/plus/osmedit/OsmBugsLayer.java
https://github.com/osmandapp/OsmAnd/issues/9933
=> OSM Notes icons on low zoom levels shows wrong icons

OsmAnd/res/xml/voice_announces.xml
https://github.com/osmandapp/OsmAnd/issues/9592
=> Divider fix on speed limit in voice

OsmAnd/src/net/osmand/plus/track/TrackMenuFragment.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/WidgetsVisibilityHelper.java
https://github.com/osmandapp/OsmAnd/issues/11311
=> Plan route show hide

OsmAnd-java/src/main/java/net/osmand/search/core/SearchCoreFactory.java
=> fix search result for interpolation, 11346

OsmAnd/src/net/osmand/plus/download/DownloadActivityType.java, OsmAnd/src/net/osmand/plus/helpers/FileNameTranslationHelper.java
https://github.com/osmandapp/OsmAnd/issues/11398
=> Untranslated Travel guides (wikivoyage) file names

OsmAnd/res/layout/dialog_list_item_with_compound_button.xml, OsmAnd/res/layout/drawer_list_radius_ex.xml, OsmAnd/res/layout/open_bug.xml, OsmAnd/res/layout/search_poi_filter.xml, OsmAnd/res/layout/split_segments_layout.xml, OsmAnd/res/layout/subscription_fragment.xml, OsmAnd/res/layout/switch_select_list_item.xml, OsmAnd/res/layout/test_backup_layout.xml, OsmAnd/res/layout/undo_popup.xml, OsmAnd/src/net/osmand/plus/myplaces/SplitSegmentDialogFragment.java
https://github.com/osmandapp/OsmAnd/issues/11444
=> "Split interval:" not translated

OsmAnd/src/net/osmand/plus/importfiles/ImportHelper.java
https://github.com/osmandapp/OsmAnd/issues/11332
=> OpenTrack duplicate SharingTrack

OsmAnd/src/net/osmand/plus/track/TrackPointsCard.java
https://github.com/osmandapp/OsmAnd/issues/11683
=> Add waypoint track menu

OsmAnd/res/values-de/phrases.xml, OsmAnd/res/values/phrases.xml
Based on https://wiki.openstreetmap.org/wiki/Climbing#Grading
Included German translation
=> Added POI types for minimum climbing grade

OsmAnd-java/src/main/java/net/osmand/osm/MapRenderingTypes.java, OsmAnd-java/src/main/java/net/osmand/osm/edit/EntityParser.java
Result:
service: craft_plumber Eberhard Rink Sanitär · Heizung · Elektro GmbH & Co. KG Lat 51.011543 Lon 13.705439...
office: company Eberhard Rink Sanitär · Heizung · Elektro GmbH & Co. KG Lat 51.011543 Lon 13.705439 ...
man_made: building Eberhard Rink Sanitär · Heizung · Elektro GmbH & Co. KG Lat 51.011543 Lon 13.705439 ...
service: craft_electrician Eberhard Rink Sanitär · Heizung · Elektro GmbH & Co. KG Lat 51.011543 Lon 13.705439 ...
service: craft_hvac Eberhard Rink Sanitär · Heizung · Elektro GmbH & Co. KG Lat 51.011543 Lon 13.705439 ...
service: craft_tiler Eberhard Rink Sanitär · Heizung · Elektro GmbH & Co. KG Lat 51.011543 Lon 13.705439 ...
=> fix tags with multi values, 11460

OsmAnd/src/net/osmand/AndroidNetworkUtils.java, OsmAnd/src/net/osmand/plus/backup/BackupHelper.java, OsmAnd/src/net/osmand/plus/backup/BackupImporter.java, OsmAnd/src/net/osmand/plus/backup/NetworkWriter.java, OsmAnd/src/net/osmand/plus/settings/backend/backup/SettingsExporter.java, OsmAnd/src/net/osmand/plus/settings/backend/backup/SettingsHelper.java, OsmAnd/src/net/osmand/plus/settings/fragments/ExportSettingsFragment.java, OsmAnd/src/net/osmand/plus/views/layers/GPXLayer.java
Reverts osmandapp/OsmAnd#11804
=> Revert "Fix compilation"

OsmAnd/src/net/osmand/plus/onlinerouting/engine/OnlineRoutingEngine.java, OsmAnd/src/net/osmand/plus/profiles/SelectNavProfileBottomSheet.java, OsmAnd/src/net/osmand/plus/profiles/SelectProfileBottomSheet.java, OsmAnd/src/net/osmand/plus/profiles/data/RoutingDataUtils.java
Don't reload JSON again after screen rotation
=> Open dialog on appropriate tab (offline / online)

OsmAnd/src/net/osmand/plus/settings/fragments/RouteParametersFragment.java
=> Fix #12105 Setting "OsmAnd Live data" only available for car profile

OsmAnd/src/net/osmand/plus/osmedit/OsmEditsLayer.java, OsmAnd/src/net/osmand/plus/osmedit/OsmPoint.java, OsmAnd/src/net/osmand/plus/views/layers/POIMapLayer.java
Reverts osmandapp/OsmAnd#12506
=> Revert "Fix #12430 Show labels for OSM Edits"

OsmAnd-java/src/main/java/net/osmand/util/GeoPointParserUtil.java
Reverts osmandapp/OsmAnd#12591
=> Revert "fix parse point for google link, 12521"

OsmAnd-java/src/main/java/net/osmand/binary/RouteDataObject.java, OsmAnd/src/net/osmand/plus/routing/RouteCalculationResult.java
Fixed refs in the turns with exit point and usual.
Checked old tests from issue https://github.com/osmandapp/OsmAnd/issues/11778 .
Fixed shield icon in top navigation panel.
=> Fix ref and shield in announce next street

OsmAnd/res/layout/gpx_item_altitude.xml, OsmAnd/res/layout/gpx_item_general.xml, OsmAnd/res/layout/gpx_item_speed.xml, OsmAnd/src/net/osmand/plus/myplaces/GPXItemPagerAdapter.java, OsmAnd/src/net/osmand/plus/track/SegmentsCard.java, OsmAnd/src/net/osmand/plus/track/TrackMenuFragment.java
Fix title, icon distance, bottom space, action button text style
=> Fix Gpx Track Tab view

OsmAnd/src/net/osmand/plus/notifications/DownloadNotification.java
Excess notifications on map updates for every download percent change
=> Try to fix #12803 Excess notifications

OsmAnd/src/net/osmand/plus/download/DownloadIndexesThread.java, OsmAnd/src/net/osmand/plus/download/SrtmDownloadItem.java, OsmAnd/src/net/osmand/plus/srtmplugin/ContourLinesMenu.java
=> Fix #12152 Allow selection of meters/feet for SRTM maps in

OsmAnd/res/values/strings.xml
=> Fix lost -> lose in strings.xml

OsmAnd/res/layout/bottom_sheet_display_groups_visibility.xml, OsmAnd/src/net/osmand/plus/mapcontextmenu/other/HorizontalSelectionAdapter.java, OsmAnd/src/net/osmand/plus/track/DisplayGroupsBottomSheet.java, OsmAnd/src/net/osmand/plus/track/PointsGroupsCard.java
Fix "hideAll" -> "showAll" if all invisible
Fix chip inner padding if inner icon size == 16dp
=> Fix Gpx Context Menu "Points groups visibility" after 2nd UI Review

OsmAnd/src/net/osmand/plus/views/layers/MapTileLayer.java
Related issue: https://github.com/osmandapp/OsmAnd-Issues/issues/1024
=> Crash when selecting online overlay layer - OpenGL

README.md
Contributing to OsmAnd is not "Directly Contribute to OpenStreetMap"
=> try to improve readme

OsmAnd-api/src/net/osmand/aidlapi/OsmAndCustomizationConstants.java, OsmAnd/res/layout/main_menu_drawer_osmand_version.xml, OsmAnd/src/net/osmand/plus/ContextMenuAdapter.java, OsmAnd/src/net/osmand/plus/activities/MapActivityActions.java, OsmAnd/src/net/osmand/plus/settings/backend/DrawerMenuItemsSettings.java, OsmAnd/src/net/osmand/plus/settings/fragments/RearrangeMenuItemsAdapter.java
(cherry picked from commit fb171fa4749b3eccb97d77ef026542998558a791)
=> Add OsmAnd version and release date

OsmAnd/src/net/osmand/plus/helpers/LocaleHelper.java
[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1170)
fix crash after import osf with incorrect "preferred_locale" value
=> fix import incorrect language settings

OsmAnd/src/net/osmand/plus/download/ui/DownloadResourceGroupFragment.java
[issue](https://github.com/osmandapp/OsmAnd/issues/14072)
=> subscribe for free maps fix

OsmAnd/res/values/phrases.xml
String ID and other surrounding strings imply this should be Contactless Girocard.
=> Fix Contactless Girocard

OsmAnd/res/values/strings.xml
Reorder routing_attr_difficulty_preference_intermediate_name string to group it with related values.
=> Move routing_attr_difficulty_preference_intermediate_name

OsmAnd-java/src/main/java/net/osmand/router/BinaryRoutePlanner.java
[issue](https://github.com/osmandapp/OsmAnd/issues/14113)
=> Routing by loop crash fix

OsmAnd/res/values-it/strings.xml
Reverts osmandapp/OsmAnd#14141
=> Revert "Fix #13776 Italian Language translate error"

OsmAnd/src/net/osmand/plus/plugins/osmedit/OsmEditsLayer.java
Problem present here of resources initialization (solved) and text below icons (need to fix in OpenGL)
=> OsmEdits layer

OsmAnd/src/net/osmand/plus/plugins/osmedit/OsmBugsLayer.java, OsmAnd/src/net/osmand/plus/views/MapLayers.java, OsmAnd/src/net/osmand/plus/views/layers/TransportStopsLayer.java, OsmAnd/src/net/osmand/plus/views/layers/core/OsmBugsTileProvider.java, OsmAnd/src/net/osmand/plus/views/layers/core/TilePointsProvider.java, OsmAnd/src/net/osmand/plus/views/layers/core/TransportStopsTileProvider.java
Transport stops layer and fixes in OSM points layer
https://github.com/osmandapp/OsmAnd-Issues/issues/1327
=> Issue 1327 3

OsmAnd/src/net/osmand/plus/OsmAndLocationSimulation.java, OsmAnd/src/net/osmand/plus/routing/RouteCalculationResult.java
[video](https://www.dropbox.com/s/7g0j7sh9n7nffav/Screen%20Recording%202022-05-30%20at%2009.41.59.mov?dl=0)
=> tune_simulation_location

OsmAnd/res/values/strings.xml
=> Word order in strings.xml

OsmAnd/src/net/osmand/plus/resources/ResourceManager.java, OsmAnd/src/net/osmand/plus/views/layers/DownloadedRegionsLayer.java
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/1394
=> Fix deletion. Fix download when selected

OsmAnd/src/net/osmand/plus/views/layers/MapMarkersLayer.java
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/1397
=> Fix on/off appearance. One/two active markers

OsmAnd/src/net/osmand/plus/OsmAndLocationSimulation.java
[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2023)
[video](https://www.dropbox.com/s/9rxr2j9haogdimk/Screen%20Recording%202022-06-21%20at%2010.26.43.mov?raw=1)
=> tune_realistic_speed_simulation

OsmAnd/src/net/osmand/plus/views/layers/DistanceRulerControlLayer.java, OsmAnd/src/net/osmand/plus/views/layers/RadiusRulerControlLayer.java
[issue](https://github.com/osmandapp/OsmAnd/issues/14713)
[video](https://www.dropbox.com/s/tp7mzx68na82nyk/Screen%20Recording%202022-07-07%20at%2015.49.44.mov?raw=1)
=> fix tap to distance widget in OpenGL r4.2

OsmAnd/src/net/osmand/plus/backup/NetworkWriter.java
Do not backup road, hillshade, slope and wiki maps if they exists on server
=> Backup fixes

OsmAnd-java/src/main/java/net/osmand/GPXUtilities.java, OsmAnd-java/src/main/java/net/osmand/data/Amenity.java, OsmAnd/src/net/osmand/data/FavouritePoint.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/MapContextMenu.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/MenuBuilder.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/FavouritePointMenuBuilder.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/WptPtMenuBuilder.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/FavoritePointEditor.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/WptPtEditor.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/WptPtEditorFragment.java, OsmAnd/src/net/osmand/plus/mapmarkers/CoordinateInputDialogFragment.java
[issue](https://github.com/osmandapp/OsmAnd/issues/14717)
=> saving amenity fields to wpt

OsmAnd/src/net/osmand/plus/views/layers/MapMarkersLayer.java
[issue](https://github.com/osmandapp/OsmAnd/issues/14694)
before / after
=> fix plan route by markers in opengl

OsmAnd/src/net/osmand/plus/plugins/mapillary/MapillaryVectorLayer.java
[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1398)
Indicator on OpenGL (emulator)
Indicator on Canvas (device)
Indicator on Android Auto (with the same device)
=> mapillary layer android auto fixes. show selected point indicator

OsmAnd/src/net/osmand/plus/views/MapLayers.java, OsmAnd/src/net/osmand/plus/views/layers/MapVectorLayer.java
Merge only with request https://github.com/osmandapp/OsmAnd-core/pull/378
From task https://github.com/osmandapp/OsmAnd/issues/14347
=> Transparency for vector layer (symbols)

OsmAnd/res/values/strings.xml
=> Fix 'trio' typo in strings.xml

OsmAnd/src/net/osmand/plus/views/layers/MapMarkersLayer.java
Fix floating of line text to markers https://github.com/osmandapp/OsmAnd-Issues/issues/1587
=> Fix floating text for lanes to markers

OsmAnd/src/net/osmand/core/android/MapRendererContext.java, OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java, OsmAnd/src/net/osmand/plus/views/MapLayers.java, OsmAnd/src/net/osmand/plus/views/layers/MapVectorLayer.java
=> Gradually hide map symbols

OsmAnd/src/net/osmand/plus/measurementtool/MeasurementToolLayer.java, OsmAnd/src/net/osmand/plus/plugins/audionotes/AudioNotesLayer.java, OsmAnd/src/net/osmand/plus/plugins/mapillary/MapillaryVectorLayer.java, OsmAnd/src/net/osmand/plus/plugins/osmedit/OsmBugsLayer.java, OsmAnd/src/net/osmand/plus/plugins/osmedit/OsmEditsLayer.java, OsmAnd/src/net/osmand/plus/views/MapLayers.java, OsmAnd/src/net/osmand/plus/views/layers/AidlMapLayer.java, OsmAnd/src/net/osmand/plus/views/layers/ContextMenuLayer.java, OsmAnd/src/net/osmand/plus/views/layers/FavouritesLayer.java, OsmAnd/src/net/osmand/plus/views/layers/GPXLayer.java, OsmAnd/src/net/osmand/plus/views/layers/ImpassableRoadsLayer.java, OsmAnd/src/net/osmand/plus/views/layers/MapMarkersLayer.java, OsmAnd/src/net/osmand/plus/views/layers/POIMapLayer.java, OsmAnd/src/net/osmand/plus/views/layers/PointLocationLayer.java, OsmAnd/src/net/osmand/plus/views/layers/PointNavigationLayer.java, OsmAnd/src/net/osmand/plus/views/layers/RouteLayer.java, OsmAnd/src/net/osmand/plus/views/layers/TransportStopsLayer.java, OsmAnd/src/net/osmand/plus/views/layers/base/OsmandMapLayer.java
To issue https://github.com/osmandapp/OsmAnd-iOS/issues/2117
=> Change order rendering

OsmAnd-java/src/main/java/net/osmand/GPXUtilities.java
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/1650
=> Fix turn lanes in GPX export/import

OsmAnd/src/net/osmand/plus/routing/RouteCalculationResult.java, OsmAnd/src/net/osmand/plus/routing/RouteRecalculationHelper.java, OsmAnd/src/net/osmand/plus/routing/RoutingHelper.java, OsmAnd/src/net/osmand/plus/routing/RoutingHelperUtils.java
Fix bearing when enabled recalculate routing in case of reverse direction.
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/1597
=> Fix bearing

OsmAnd/res/layout/fragment_map_context_menu.xml, OsmAnd/res/values/attrs.xml, OsmAnd/src/net/osmand/plus/mapcontextmenu/MapContextMenu.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/MapContextMenuFragment.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/MenuController.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/IconsCard.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/widgets/AltitudeWidget.java, OsmAnd/src/net/osmand/plus/widgets/FlowLayout.java
* Add altitude info on the Context Menu dialog
* Use FlowLayout for Context Menu info widgets
=> Add altitude info on the Context Menu dialog

OsmAnd/src/net/osmand/plus/views/MapLayers.java
To issue https://github.com/osmandapp/OsmAnd/issues/15457
=> Fix overlay transparency for legacy

OsmAnd/src/net/osmand/core/android/TileSourceProxyProvider.java, OsmAnd/src/net/osmand/plus/views/layers/MapMarkersLayer.java, OsmAnd/src/net/osmand/plus/views/layers/geometry/GeometryWayDrawer.java
=> Fix long tile image loading

OsmAnd-java/src/main/java/net/osmand/Location.java
=> fix Different Uphill/Downhill, 642

OsmAnd/src/net/osmand/plus/views/corenative/NativeCoreContext.java
Issue https://github.com/osmandapp/OsmAnd/issues/15529
=> Add Nauticals maps to core

OsmAnd/src/net/osmand/core/android/TileSourceProxyProvider.java
Get tiles from cache on demand
=> Support overscale tiles

OsmAnd/src/net/osmand/plus/routing/GPXRouteParams.java, OsmAnd/src/net/osmand/plus/routing/RouteRecalculationHelper.java
https://github.com/osmandapp/OsmAnd/issues/14230
=> Fix #14230 Follow track - change destination point

OsmAnd/src/net/osmand/plus/helpers/IntentHelper.java
Do not use setIntent(null). Under some conditions the original intent may come back.
Instead of that clear the intent data after use.
=> Fix bug with intent came back after screen rotation

OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java, OsmAnd/src/net/osmand/plus/views/AnimateDraggingMapThread.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
=> Fix double-tap animation

OsmAnd/src/net/osmand/plus/views/mapwidgets/widgets/StreetNameWidget.java
To issue https://github.com/osmandapp/OsmAnd/issues/14863
=> Fix street name with road ref

OsmAnd-java/src/main/java/net/osmand/search/SearchUICore.java, OsmAnd-java/src/main/java/net/osmand/search/core/SearchCoreFactory.java, OsmAnd-java/src/main/java/net/osmand/search/core/SearchSettings.java, OsmAnd-java/src/test/java/net/osmand/search/LocationSearchTest.java, OsmAnd/src/net/osmand/plus/search/QuickSearchCoordinatesFragment.java
not transferred: QuickSearchCoordinatesViewController, QuickSearchCoordinatesViewController,LocationParser
=> ios code transfer to java, 12809

OsmAnd/src/net/osmand/plus/views/layers/RouteLayer.java
To issue https://github.com/osmandapp/OsmAnd/issues/15557
=> Fix first line segment dissapears

OsmAnd/src/net/osmand/plus/views/MapLayers.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1637)
[android auto video](https://www.dropbox.com/s/w7a3spvqffez0vg/Screen%20Recording%202022-11-21%20at%2000.11.13.mov?raw=1)
Android (not broken)
=> fix_dissappearing_aundroid_auto_route_line

OsmAnd-java/src/main/java/net/osmand/util/GeoPointParserUtil.java, OsmAnd/src/net/osmand/data/PointDescription.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/other/ShareMenu.java
[issue](https://github.com/osmandapp/OsmAnd/issues/15681)
=> change sharing point url

OsmAnd/src/net/osmand/plus/search/QuickSearchHelper.java
=> fix search gpx

OsmAnd-java/src/main/java/net/osmand/IndexConstants.java, OsmAnd/src/net/osmand/plus/plugins/weather/WeatherWidget.java
Reverts osmandapp/OsmAnd#15821
=> Revert "Show forecast info on weather widget click"

OsmAnd-java/src/main/java/net/osmand/router/RouteDataResources.java, OsmAnd-java/src/main/java/net/osmand/router/RouteImporter.java, OsmAnd-java/src/main/java/net/osmand/router/RouteSegmentResult.java, OsmAnd/src/net/osmand/plus/measurementtool/MeasurementEditingContext.java, OsmAnd/src/net/osmand/plus/routing/RouteProvider.java
=> Fix gpx routing #14331

OsmAnd-java/src/main/java/net/osmand/IndexConstants.java, OsmAnd/src/net/osmand/plus/plugins/weather/WeatherWidget.java
This reverts commit 1c9b40f5d7c39ad42fcf04fe114714deb8d981a1.
=> Revert "Revert "Show forecast info on weather widget click""

OsmAnd/src/net/osmand/plus/auto/RoutePreviewScreen.java, OsmAnd/src/net/osmand/plus/views/layers/MapControlsLayer.java
[issue](https://github.com/osmandapp/OsmAnd/issues/14138)
[video before - infinity loading ](https://www.dropbox.com/s/iizqwl1q3os09g5/Screen%20Recording%202022-11-29%20at%2020.48.38.mov?raw=1)
[video after](https://www.dropbox.com/s/8u1jdv0im8o0e1b/Screen%20Recording%202022-11-29%20at%2020.43.02.mov?raw=1)
=> android_auto_gpx_fix

OsmAnd-java/src/main/java/net/osmand/GPXUtilities.java, OsmAnd/src/net/osmand/plus/AppInitializer.java
To issue https://github.com/osmandapp/OsmAnd/issues/15760
=> Fix date format of GPX for old devices Android 6.0 and lower

OsmAnd/src/net/osmand/plus/plugins/osmedit/fragments/AdvancedEditPoiFragment.java
[Issue](https://github.com/osmandapp/OsmAnd/issues/13660)
=> osm_editor_hits_fitching_update

OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Issue https://github.com/osmandapp/OsmAnd/issues/15934
=> Fix legacy/opengl orders

OsmAnd/src/net/osmand/plus/views/layers/RouteLayer.java
Issue https://github.com/osmandapp/OsmAnd/issues/15928
=> Fix dot on analyze on map chart

OsmAnd/src/net/osmand/plus/measurementtool/MeasurementToolLayer.java
[exception (10).log](https://github.com/osmandapp/OsmAnd/files/10276151/exception.10.log)
Move point in Plan Route https://github.com/osmandapp/OsmAnd-Issues/issues/1784
=> Fix crash when move point in Plan Route

OsmAnd/src/net/osmand/plus/views/layers/core/TilePointsProvider.java
Correct collection point class name
=> Fix collection point overriden class name

OsmAnd/src/net/osmand/plus/plugins/srtm/SRTMPlugin.java, OsmAnd/src/net/osmand/plus/plugins/srtm/TerrainLayer.java
Remove extra draw cycle for hillshade layer
=> Fix legacy hillshade rendered too dark

OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/AmenityUIHelper.java
To issue https://github.com/osmandapp/OsmAnd/issues/15500
=> Fix icons in POI details

OsmAnd/src/net/osmand/plus/OsmandApplication.java, OsmAnd/src/net/osmand/plus/views/MapViewWithLayers.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java, OsmAnd/src/net/osmand/plus/views/layers/core/OsmBugsTileProvider.java, OsmAnd/src/net/osmand/plus/views/layers/core/POITileProvider.java, OsmAnd/src/net/osmand/plus/views/layers/core/TilePointsProvider.java, OsmAnd/src/net/osmand/plus/views/layers/core/TransportStopsTileProvider.java
Stop provider when renderer is removed
=> Check renderer is present

OsmAnd/src/net/osmand/plus/views/AnimateDraggingMapThread.java
Stop animations if renderer is gone
=> Stop animation when renderer is lost

OsmAnd-java/src/main/java/net/osmand/GPXUtilities.java, OsmAnd/src/net/osmand/plus/track/CachedTrack.java, OsmAnd/src/net/osmand/plus/track/helpers/FilteredSelectedGpxFile.java, OsmAnd/src/net/osmand/plus/track/helpers/SelectedGpxFile.java, OsmAnd/src/net/osmand/plus/views/layers/GPXLayer.java
Recalculate visible and markedly zoomed tracks only
=> Check track visibility and zoom change

OsmAnd/src/net/osmand/plus/configmap/ConfigureMapUtils.java
Add Simplified and Traditional Chinese to Map language
=> Add zh-Hans and zh-Hant to Map language

OsmAnd-java/src/main/java/net/osmand/IndexConstants.java, OsmAnd/src/net/osmand/core/android/MapRendererContext.java
=> Attach geotiff heightmap collection

OsmAnd/src/net/osmand/core/android/MapRendererContext.java
Store geotiff sqlite cache in application cache directory
=> Use application cache directory

OsmAnd/src/net/osmand/core/android/MapillaryTilesProvider.java, OsmAnd/src/net/osmand/core/android/TileSourceProxyProvider.java
Stop online maps jamming in memory
=> Fix online maps memory leaks

OsmAnd/src/net/osmand/plus/views/layers/MapSelectionHelper.java
Reverts osmandapp/OsmAnd#16402
=> Revert "Fixed point selection if a part of route"

OsmAnd/src/net/osmand/plus/activities/MapActivity.java, OsmAnd/src/net/osmand/plus/backup/ui/BackupSettingsFragment.java
Open backup authorization screen after logout
=> Fix #16461

OsmAnd/src/net/osmand/plus/views/mapwidgets/widgets/StreetNameWidget.java
Issue https://github.com/osmandapp/OsmAnd/issues/16434
Old issue https://github.com/osmandapp/OsmAnd/issues/14863
Old commit https://github.com/osmandapp/OsmAnd/pull/16523
iOS PR https://github.com/osmandapp/OsmAnd-iOS/pull/2603
=> Fix remove ref from street name

OsmAnd/src/net/osmand/plus/configmap/tracks/TracksComparator.java
Not sure if the compiler would anyway optimize this, but probably not.
=> Optimize code - Remove duplicate condition query

OsmAnd-api/build.gradle, OsmAnd/build-common.gradle, gradle.properties
Reverts osmandapp/OsmAnd#16665
=> Revert "Disable Jetifier"

OsmAnd/src/net/osmand/plus/plugins/development/widget/CameraDistanceWidget.java, OsmAnd/src/net/osmand/plus/plugins/development/widget/TargetDistanceWidget.java
=> Fix development plugins

OsmAnd/src/net/osmand/plus/base/MapViewTrackingUtilities.java, OsmAnd/src/net/osmand/plus/routepreparationmenu/MapRouteInfoMenu.java, OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java
Implement logic suggested in: https://github.com/osmandapp/OsmAnd/issues/16352#issuecomment-1434568299
=> Fix logic of compass rotation in route planing mode

OsmAnd/src/net/osmand/core/android/MapRendererContext.java, OsmAnd/src/net/osmand/plus/configmap/ConfigureMapMenu.java, OsmAnd/src/net/osmand/plus/dialogs/RasterMapMenu.java, OsmAnd/src/net/osmand/plus/plugins/rastermaps/OsmandRasterMapsPlugin.java, OsmAnd/src/net/osmand/plus/render/MapRenderRepositories.java, OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java
Implement logic suggested in  https://github.com/osmandapp/OsmAnd/issues/15935#issuecomment-1467997271
=> Fix polygons visibility logic when underlay map is on (#15935)

OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Reverts osmandapp/OsmAnd#16746
=> Revert "Improved cooperation with zooming and rotation"

OsmAnd/src/net/osmand/plus/views/corenative/NativeCoreContext.java
Show map symbols using downloaded fonts
=> Use downloaded fonts

OsmAnd/res/values/strings.xml, OsmAnd/res/xml/multimedia_notes.xml, OsmAnd/src/net/osmand/plus/plugins/audionotes/AudioVideoNotesPlugin.java, OsmAnd/src/net/osmand/plus/plugins/audionotes/MultimediaNotesFragment.java
Implement UI suggested in https://github.com/osmandapp/OsmAnd/issues/12648#issuecomment-1351319238
=> Improve Camera App preference UI on A/V Notes plugin settings screen

OsmAnd-java/src/main/java/net/osmand/router/BinaryRoutePlanner.java, OsmAnd-java/src/main/java/net/osmand/router/GeneralRouter.java
Issue https://github.com/osmandapp/OsmAnd/issues/16173
=> Fix wrong route with car profile #16173

OsmAnd/src/net/osmand/core/android/MapRendererContext.java
To issue https://github.com/osmandapp/OsmAnd/issues/16914
=> Fix addons loading

OsmAnd/src/net/osmand/core/android/MapRendererContext.java
To issues https://github.com/osmandapp/OsmAnd/issues/16926 and https://github.com/osmandapp/OsmAnd/issues/16914
And discussion https://github.com/osmandapp/OsmAnd/discussions/16699
=> Rollback changes

OsmAnd-java/src/main/java/net/osmand/binary/RouteDataObject.java
Full copy from BinaryMapDataObject. Need for task Relation Live Updates
=> Add contains type for RouteDataObject

OsmAnd/src/net/osmand/plus/views/AnimateDraggingMapThread.java, OsmAnd/src/net/osmand/plus/views/MultiTouchSupport.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Smooth dragging for map with relief
=> Smooth dragging of 3D map

OsmAnd/src/net/osmand/plus/views/AnimateDraggingMapThread.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Don't reset stable map target location
=> Remove unnecessary map target reset

OsmAnd/src/net/osmand/plus/activities/MapActivity.java, OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java, OsmAnd/src/net/osmand/plus/views/AnimateDraggingMapThread.java, OsmAnd/src/net/osmand/plus/views/MultiTouchSupport.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Fix wrong initial map location on relief
=> Fix zoom lag and initial map location on relief

OsmAnd-java/src/main/java/net/osmand/binary/BinaryMapIndexReader.java, OsmAnd-java/src/main/java/net/osmand/binary/OsmandOdb.java
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/1885
=> Add OsmAndOwner to obf

OsmAnd/src/net/osmand/plus/download/MultipleDownloadItem.java, OsmAnd/src/net/osmand/plus/download/ui/ItemViewHolder.java, OsmAnd/src/net/osmand/plus/plugins/weather/OfflineForecastHelper.java, OsmAnd/src/net/osmand/plus/routepreparationmenu/cards/SuggestionsMapsDownloadWarningCard.java
Fix bug described in https://github.com/osmandapp/OsmAnd/issues/16936#issuecomment-1510934156.
Also make it impossible to start a new multiple download if one of the inner files is in removing process at the moment.
=> Fix problems of Weather Multiple download

OsmAnd/src/net/osmand/plus/utils/NativeUtilities.java, OsmAnd/src/net/osmand/plus/views/layers/ContextMenuLayer.java
Display context menu marker on relief
=> Correct marker position for relief

OsmAnd/src/net/osmand/plus/activities/MapActivityKeyListener.java, OsmAnd/src/net/osmand/plus/helpers/ScrollHelper.java, OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java, OsmAnd/src/net/osmand/plus/settings/enums/InputDevice.java, OsmAnd/src/net/osmand/plus/settings/fragments/GeneralProfileSettingsFragment.java
Implement key codes proposed in https://github.com/osmandapp/OsmAnd/issues/16327#issuecomment-1497505570.
Also don't handle letter key codes if the map isn't visible.
=> Implement keyboard support for keys "Esc", "N", "S", "P", "O"

OsmAnd/src/net/osmand/plus/views/AnimateDraggingMapThread.java, OsmAnd/src/net/osmand/plus/views/MultiTouchSupport.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Provide precise touch gestures to pan/zoom/rotate 3D map
=> Allow 3D map gestures

OsmAnd/res/layout/list_item_with_descr.xml, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/AmenityUIHelper.java, OsmAnd/src/net/osmand/plus/track/cards/RouteInfoCard.java, OsmAnd/src/net/osmand/plus/track/fragments/TrackMenuFragment.java, OsmAnd/src/net/osmand/plus/wikipedia/WikiArticleHelper.java, OsmAnd/src/net/osmand/plus/wikipedia/WikiArticleSearchTask.java, OsmAnd/src/net/osmand/plus/wikipedia/WikipediaDialogFragment.java
Implement logic suggested in https://github.com/osmandapp/OsmAnd-Issues/issues/1955#issuecomment-1539953927
=> Use the same algorithm to handle clicks on Wikipedia links

OsmAnd-java/src/main/java/net/osmand/binary/BinaryMapRouteReaderAdapter.java, OsmAnd-java/src/main/java/net/osmand/binary/RouteDataObject.java, OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java, OsmAnd/src/net/osmand/plus/routing/RouteCalculationResult.java, OsmAnd/src/net/osmand/plus/routing/RoutingHelper.java, OsmAnd/src/net/osmand/plus/settings/backend/ApplicationMode.java
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/1979
=> Fix maxspeed:hgv

OsmAnd/src/net/osmand/plus/views/AnimateDraggingMapThread.java
Restore correct map position after fling animation
=> Fix map jump when zooming after fling

OsmAnd-java/src/main/java/net/osmand/router/RoutePlannerFrontEnd.java
To issue https://github.com/osmandapp/OsmAnd/issues/16379
=> Fix routing with intermediate points

OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Don't reset map center location on touching map edge
=> Fix map flicker on edge dragging

OsmAnd-java/src/main/java/net/osmand/gpx/GPXUtilities.java, OsmAnd/src/net/osmand/plus/measurementtool/MeasurementToolFragment.java, OsmAnd/src/net/osmand/plus/track/helpers/FilteredSelectedGpxFile.java, OsmAnd/src/net/osmand/plus/track/helpers/SelectedGpxFile.java, OsmAnd/src/net/osmand/plus/views/Renderable.java, OsmAnd/src/net/osmand/plus/views/layers/GPXLayer.java
Check visibility of corrected long tracks
=> Check visibility for long tracks

OsmAnd/src/net/osmand/plus/views/layers/RadiusRulerControlLayer.java
Display map ruler beyond 180 longitude
=> Display map ruler over 180 longitude

OsmAnd/src/net/osmand/plus/views/mapwidgets/MapWidgetRegistry.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/widgets/LanesWidget.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/widgets/MapMarkersBarWidget.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/widgets/MapWidget.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/widgets/StreetNameWidget.java
Fix bug described in https://github.com/osmandapp/OsmAnd/issues/17267#issuecomment-1573517841
=> Fix "Street name widget isn't visible in Bottom panel in Landscape mode"

OsmAnd/src/net/osmand/plus/activities/MapActivity.java, OsmAnd/src/net/osmand/plus/helpers/ScrollHelper.java
=> Fix map scroll by buttons and trackball

OsmAnd/src/net/osmand/plus/views/MultiTouchSupport.java
Use angle to detect tilt gesture instead of vertical offsets
=> Fix strict tilt gesture

OsmAnd-java/src/main/java/net/osmand/binary/RouteDataObject.java, OsmAnd-java/src/main/java/net/osmand/router/RouteResultPreparation.java
Main issue https://github.com/osmandapp/OsmAnd/issues/15930
Other issues https://github.com/osmandapp/OsmAnd/issues/17238 
https://github.com/osmandapp/OsmAnd/issues/16752#issuecomment-1592569809
=> New turn lanes conception

OsmAnd-java/src/main/java/net/osmand/router/RouteResultPreparation.java, OsmAnd-java/src/main/java/net/osmand/router/TurnType.java
To PR https://github.com/osmandapp/OsmAnd/pull/17421
=> Refactoring turn lanes

OsmAnd/src/net/osmand/plus/mapcontextmenu/other/DestinationReachedFragment.java
Reverts osmandapp/OsmAnd#17279
=> Revert "Move map center on destination reached"

OsmAnd/src/net/osmand/plus/plugins/weather/WeatherHelper.java, OsmAnd/src/net/osmand/plus/plugins/weather/WeatherWebClient.java, OsmAnd/src/net/osmand/plus/utils/AndroidNetworkUtils.java
Use Last-Modified response header to check file generation time
=> Check weather forecast generation time

OsmAnd/src/net/osmand/plus/plugins/weather/WeatherHelper.java
Use path to application cache for weather forecast files
=> Change path to cache for weather forecasts

OsmAnd/res/xml/development_settings.xml, OsmAnd/src/net/osmand/plus/plugins/accessibility/AccessibilitySettingsFragment.java, OsmAnd/src/net/osmand/plus/plugins/audionotes/MultimediaNotesFragment.java, OsmAnd/src/net/osmand/plus/plugins/development/DevelopmentSettingsFragment.java, OsmAnd/src/net/osmand/plus/plugins/development/OsmandDevelopmentPlugin.java, OsmAnd/src/net/osmand/plus/plugins/monitoring/MonitoringSettingsFragment.java, OsmAnd/src/net/osmand/plus/plugins/weather/WeatherPlugin.java, OsmAnd/src/net/osmand/plus/plugins/weather/dialogs/WeatherSettingsFragment.java, OsmAnd/src/net/osmand/plus/profiles/SelectCopyAppModeBottomSheet.java, OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java, OsmAnd/src/net/osmand/plus/settings/bottomsheets/ResetProfilePrefsBottomSheet.java, OsmAnd/src/net/osmand/plus/settings/fragments/ConfigureMenuItemsFragment.java, OsmAnd/src/net/osmand/plus/settings/fragments/ConfigureProfileFragment.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/configure/ConfigureScreenActionsCard.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/configure/reorder/ReorderWidgetsFragment.java
* Add ability to reset plugin settings to default (Weather / Development)
* Add ability to copy preferences from another profile (Weather)
=> Add ability to reset plugin settings to default (Weather / Development)

OsmAnd-java/src/main/java/net/osmand/router/RouteResultPreparation.java, OsmAnd-java/src/main/java/net/osmand/router/TurnType.java
https://github.com/osmandapp/OsmAnd/issues/13829
https://github.com/osmandapp/OsmAnd/issues/16498
https://github.com/osmandapp/OsmAnd/issues/16752#issuecomment-1592644516
https://github.com/osmandapp/OsmAnd/issues/17508
=> Add combined turn lanes

OsmAnd/src/net/osmand/plus/settings/backend/backup/ZipWriter.java, OsmAnd/src/net/osmand/plus/settings/backend/backup/items/FavoritesSettingsItem.java, OsmAnd/src/net/osmand/plus/settings/backend/backup/items/SettingsItem.java
Reverts osmandapp/OsmAnd#17304
=> Revert "Fix "Data doesn't import if use "/" in name of Favorites folder" part 2"

OsmAnd-java/src/main/java/net/osmand/search/core/SearchPhrase.java
To issue https://github.com/osmandapp/OsmAnd-iOS/issues/2939
=> Fix search phrase with apostrophe

OsmAnd-java/src/main/java/net/osmand/IndexConstants.java, OsmAnd-java/src/main/java/net/osmand/data/Amenity.java, OsmAnd-java/src/main/java/net/osmand/osm/MapPoiTypes.java
To issue https://github.com/osmandapp/OsmAnd/issues/17335
=> Add amenity order for obf creation

OsmAnd-java/src/main/java/net/osmand/router/RouteResultPreparation.java
To issue https://github.com/osmandapp/OsmAnd/issues/17635
=> Fix turn lanes

OsmAnd/src/net/osmand/plus/views/controls/SideWidgetsPanel.java
https://github.com/osmandapp/OsmAnd/issues/17570
=> #17570: Fixed widget dots flickering

README.md
- The missing F-Droid badge was added
- Some badges were reordered
- Outdated badges were fixed
- All of them are displayed in a table
=> Improvements to badges in README.md

OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Don't restart rotation animations unnecessarily.
=> Fix compass rotation delays in OpenGL

OsmAnd-java/src/main/java/net/osmand/router/RoutePlannerFrontEnd.java, OsmAnd-java/src/main/java/net/osmand/router/RouteSegmentResult.java
https://github.com/osmandapp/OsmAnd-Issues/issues/2007
=> Fix 2007 Crash while attach gpx, sync with C++

OsmAnd/src/net/osmand/plus/routing/data/AnnounceTimeDistances.java
@vshcherb Explanation see https://github.com/osmandapp/OsmAnd/issues/17376#issuecomment-1673492154. But please check if I am overlooking anything?
=> Eliminate TURN_NOW_TIME as an independent parameter

OsmAnd/src/net/osmand/plus/plugins/weather/OfflineForecastHelper.java, OsmAnd/src/net/osmand/plus/plugins/weather/WeatherWebClient.java, OsmAnd/src/net/osmand/plus/plugins/weather/widgets/WeatherWidget.java
Use custom objects for shared pointers in SWIG
=> Fix SWIG shared pointers

OsmAnd/res/values/strings.xml
Following up on https://github.com/osmandapp/OsmAnd/pull/17950
=> Arrival distance wording "Very late"

OsmAnd-java/src/main/java/net/osmand/router/RouteResultPreparation.java
To issue https://github.com/osmandapp/OsmAnd/issues/17671
=> Add XOR for turn instruction (keepLeft keepRight)

OsmAnd-java/src/main/java/net/osmand/osm/MapRenderingTypes.java
To issue https://github.com/osmandapp/OsmAnd/issues/17401
=> Propagate to nodes

OsmAnd/src/net/osmand/plus/helpers/MapScrollHelper.java
Use simple map center for relative map shifts
=> Fix jumps in keyboard scroll

OsmAnd-java/src/main/java/net/osmand/router/RouteImporter.java, OsmAnd-java/src/main/java/net/osmand/router/RouteSegmentResult.java, OsmAnd-java/src/main/java/net/osmand/router/TurnType.java, OsmAnd/src/net/osmand/plus/routing/GPXRouteParams.java, OsmAnd/src/net/osmand/plus/routing/RouteProvider.java
To issue https://github.com/osmandapp/OsmAnd/issues/17912
=> Add left side to routing by gpx

OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java
To issue https://github.com/osmandapp/OsmAnd/issues/17723
=> Avoid series of same types alarms

OsmAnd/src/net/osmand/plus/helpers/MapScrollHelper.java
Use floating-point coordinates for center pixel of map
=> Fix map sliding down when scrolling

OsmAnd/src/net/osmand/plus/OsmandApplication.java, OsmAnd/src/net/osmand/plus/routing/RouteProvider.java
In keeping with Issue #18244 here the changes presented by @EssBee59
=> Enable restart BRouter service

OsmAnd/src/net/osmand/plus/plugins/osmedit/helpers/OsmBugsRemoteUtil.java
https://github.com/osmandapp/OsmAnd/issues/16489
Example note: https://master.apis.dev.openstreetmap.org/note/46911
=> Add hashtag with appname in notes #16489

OsmAnd-java/src/main/java/net/osmand/osm/MapRenderingTypes.java
To issue https://github.com/osmandapp/OsmAnd/issues/10983
=> Change values of propagateToNodes=[yes,true,all,start,end,center]

OsmAnd/src/net/osmand/plus/base/ContextMenuScrollFragment.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/WidgetsVisibilityHelper.java
Reverts osmandapp/OsmAnd#18362
=> Revert "fix control buttons on gpx approximation fix"

.gitignore, OsmAnd-java/build.gradle, OsmAnd-java/src/test/java/net/osmand/rendering/OpenGLTest.java
To issue https://github.com/osmandapp/OsmAnd/issues/18143
=> Unit test for rendering

OsmAnd/res/layout-land/street_name_widget.xml, OsmAnd/res/layout/street_name_widget.xml, OsmAnd/src/net/osmand/plus/routing/CurrentStreetName.java, OsmAnd/src/net/osmand/plus/routing/RoutingHelperUtils.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/widgets/StreetNameWidget.java
Reverts osmandapp/OsmAnd#18392
=> Revert "Fix 16434 Highway shield steals numbers from the route/ref/name"

OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Check and update zoom to stay in limits.
=> Fix "No enum class ZoomLevel with value -2"

OsmAnd-java/src/main/java/net/osmand/osm/MapRenderingTypes.java
To issue https://github.com/osmandapp/OsmAnd/issues/10983
=> Add new propagation type

OsmAnd-java/src/main/java/net/osmand/osm/MapRenderingTypes.java
To issue https://github.com/osmandapp/OsmAnd/issues/10983
=> Add propagateIfTag propagateIfValue

OsmAnd/src/net/osmand/core/android/MapRendererContext.java, OsmAnd/src/net/osmand/plus/OsmandApplication.java, OsmAnd/src/net/osmand/plus/auto/NavigationCarAppService.java, OsmAnd/src/net/osmand/plus/auto/NavigationScreen.java, OsmAnd/src/net/osmand/plus/auto/NavigationSession.java, OsmAnd/src/net/osmand/plus/auto/SurfaceRenderer.java, OsmAnd/src/net/osmand/plus/utils/NativeUtilities.java, OsmAnd/src/net/osmand/plus/views/MapViewWithLayers.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java, OsmAnd/src/net/osmand/plus/views/corenative/NativeCoreContext.java, OsmAnd/src/net/osmand/plus/views/layers/base/OsmandMapLayer.java
Enable OpenGL rendering for Android Auto
=> Allow OpenGL rendering in Android Auto

OsmAnd-java/src/main/java/net/osmand/router/TransportRoutePlanner.java, OsmAnd/src/net/osmand/plus/routing/TransportRoutingHelper.java
To issue https://github.com/osmandapp/OsmAnd/issues/17530
Cause of bug: route segments only added to priority queue, making request of stops, but did not take part in route building.
Analized routes before:
Analized routes after:
=> Fix rough bug in priority queue of public transport

OsmAnd/src/net/osmand/plus/views/AnimateDraggingMapThread.java
Use correct point position in route planning after map scroll has finished
=> Fix point position in plan route during fast pan

OsmAnd/src/net/osmand/plus/views/AnimateDraggingMapThread.java
Apply slow rotation to animations to turn smoothly during navigation
=> Use smooth turn animations during navigation

OsmAnd/res/values-de/phrases.xml
Hi,
here I fixed and enhanced some translations for traffic signals equipment in German.  Thank you
=> fixed some translations for traffic signals equipment.xml

OsmAnd/src/net/osmand/plus/auto/SurfaceRenderer.java, OsmAnd/src/net/osmand/plus/views/MapViewWithLayers.java
Use map zoom constraints in OpenGL renderer
=> Apply map zoom limits to renderer

OsmAnd/res/xml/development_settings.xml, OsmAnd/src/net/osmand/plus/plugins/development/DevelopmentSettingsFragment.java, OsmAnd/src/net/osmand/plus/plugins/development/OsmandDevelopmentPlugin.java, OsmAnd/src/net/osmand/plus/views/MapViewWithLayers.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Add development settings for map symbol debugging
=> Add developer options to show symbols debug info

OsmAnd/res/values-pl/strings.xml
The translation of "Free ride" to Polish "Bezpłatny przejazd" is wrong. "Bezpłatny przejazd" actually means "a ride free of charge". The correct translation should be "Jazda dowolna" which means "any ride".
=> Update strings.xml "free ride" in Polish

OsmAnd/src/net/osmand/core/android/MapRendererContext.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Use different colors for sky and distant fog in night mode
=> Change sky and fog colors in night mode

OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Correct value of zoom level in widget in accordance to increased detail level of tiles
=> Zoom in widget must match detail level of tiles

OsmAnd/src/net/osmand/plus/plugins/development/DevelopmentSettingsFragment.java, OsmAnd/src/net/osmand/plus/plugins/development/OsmandDevelopmentPlugin.java, OsmAnd/src/net/osmand/plus/views/layers/geometry/GeometryWayDrawer.java
Add developer options to render routes as volumetric (lifted up)
=> Add developer options for volumetric routes

OsmAnd/src/net/osmand/plus/activities/MapActivity.java, OsmAnd/src/net/osmand/plus/auto/SurfaceRenderer.java
Stop map dragging animations before renderer stop
=> Fix SWIG crash during map dragging animations

OsmAnd/src/net/osmand/plus/plugins/weather/WeatherRasterLayer.java, OsmAnd/src/net/osmand/plus/plugins/weather/dialogs/WeatherForecastFragment.java
Temporary disable dynamic resource switching for weather forecast
=> Disable dynamic resource switching for weather

OsmAnd/src/net/osmand/plus/plugins/weather/OfflineForecastHelper.java, OsmAnd/src/net/osmand/plus/plugins/weather/WeatherHelper.java, OsmAnd/src/net/osmand/plus/plugins/weather/WeatherRasterLayer.java, OsmAnd/src/net/osmand/plus/plugins/weather/dialogs/WeatherForecastFragment.java, OsmAnd/src/net/osmand/plus/utils/AndroidNetworkUtils.java, OsmAnd/src/net/osmand/plus/utils/OsmAndFormatter.java
Use dynamic resources and textures for weather forecast
=> Use dynamic resources for weather forecast

OsmAnd-java/src/main/java/net/osmand/router/RoutePlannerFrontEnd.java
To issue https://github.com/osmandapp/OsmAnd/issues/19016
=> Fix route recalculation HH vs BASE

OsmAnd/res/layout-v26/simple_map_widget_large.xml, OsmAnd/res/layout-v26/simple_map_widget_medium.xml, OsmAnd/res/layout-v26/simple_map_widget_small.xml, OsmAnd/res/layout/simple_map_widget_large.xml, OsmAnd/res/layout/simple_map_widget_medium.xml, OsmAnd/res/layout/simple_map_widget_small.xml, OsmAnd/src/net/osmand/plus/views/controls/VerticalWidgetPanel.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/widgets/SimpleWidget.java
Reverts osmandapp/OsmAnd#19251 we need to keep height the same
=> Revert "made all widgets same height in one row"

OsmAnd/src/net/osmand/plus/plugins/weather/WeatherRasterLayer.java
Use UTC-aligned time gaps for weather forecasts
=> Fix weather forecasts for days after tomorrow

OsmAnd-java/src/main/java/net/osmand/osm/edit/OSMSettings.java
Relation id tags before map generation 01.04.2024
To issues https://github.com/osmandapp/OsmAnd-Issues/issues/2375
https://github.com/osmandapp/OsmAnd/issues/14938
=> Add relation_id tag

OsmAnd-java/src/main/java/net/osmand/router/RouteResultPreparation.java
Fix muting in issues:
https://github.com/osmandapp/OsmAnd/issues/19064
https://github.com/osmandapp/OsmAnd/issues/19379
https://github.com/osmandapp/OsmAnd/issues/19275
=> Fix muting turn lanes

OsmAnd-java/src/main/java/net/osmand/router/RouteResultPreparation.java
To issue https://github.com/osmandapp/OsmAnd/issues/19379
=> Fix turn lanes in the middle between KL and KR

OsmAnd/src/net/osmand/plus/plugins/weather/WeatherRasterLayer.java
Use proper time period for next day weather forecasts
=> Smoothly change period for weather forecast

OsmAnd/res/values/phrases.xml
Group us_maps strings in phrases.xml for better translation overview.
=> Group us_maps strings in phrases.xml

OsmAnd-java/src/main/java/net/osmand/router/RouteResultPreparation.java
To issues https://github.com/osmandapp/OsmAnd/issues/19343 , https://github.com/osmandapp/OsmAnd/issues/19178 , https://github.com/osmandapp/OsmAnd/issues/19441
=> Turn lanes. Switch to _link. Twice road

OsmAnd/src/net/osmand/plus/plugins/weather/WeatherRasterLayer.java, OsmAnd/src/net/osmand/plus/plugins/weather/dialogs/WeatherForecastFragment.java
Use shorter time slice for next day weather forecasts if available
=> Use precise time periods for next day forecasts

OsmAnd-java/src/main/java/net/osmand/router/RoutePlannerFrontEnd.java, OsmAnd/src/net/osmand/plus/measurementtool/MeasurementEditingContext.java
=> Approximation fixes (dupes, crash)

OsmAnd-java/src/main/java/net/osmand/router/HHRouteDataStructure.java, OsmAnd-java/src/main/java/net/osmand/router/HHRoutePlanner.java
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/2471
=> Routing. MAX_COUNT_REITERATION

OsmAnd-java/src/main/java/net/osmand/router/RouteResultPreparation.java
To issue https://github.com/osmandapp/OsmAnd/issues/19458#issuecomment-2042615301
=> Turn lanes KL KR on motorways

OsmAnd/src/net/osmand/plus/routing/RoutingHelper.java
To issue https://github.com/osmandapp/OsmAnd/issues/19498
=> Fix location jumping

OsmAnd-java/src/main/java/net/osmand/router/HHRoutePlanner.java
To issue https://github.com/osmandapp/OsmAnd/issues/19420
=> Fix HH routing with live updates

OsmAnd/src/net/osmand/plus/views/layers/PointLocationLayer.java
Use elevation-aware accuracy circle for current location
=> Use relief-aware accuracy circle

OsmAnd-java/src/main/java/net/osmand/gpx/GPXUtilities.java
DateTimeFormatter Added in API level 26 :-(
=> [4.7] Revert "Fix GPX ms parsing with DateTimeFormatter (Java 8)"

OsmAnd-java/src/main/java/net/osmand/router/RoutingConfiguration.java
To issue https://github.com/osmandapp/OsmAnd/issues/19456
=> Add multi parameters

OsmAnd/src/net/osmand/plus/routing/RouteProvider.java
=> Hotfix HH-to-BRP fallback NORMAL to COMPLEX mode

OsmAnd-java/src/main/java/net/osmand/data/Amenity.java, OsmAnd-java/src/main/java/net/osmand/osm/MapPoiTypes.java, OsmAnd-java/src/main/java/net/osmand/osm/edit/EntityParser.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/AmenityUIHelper.java, OsmAnd/src/net/osmand/plus/render/RenderingIcons.java, OsmAnd/src/net/osmand/plus/utils/OsmAndFormatter.java
To issue https://github.com/osmandapp/OsmAnd/issues/8483
BinaryInspector:
```Binary index Poi_test2.obf version = 2 edition = Wed Jun 19 13:13:07 EEST 2024
1 POI data Poi_test2 - 724 bytes
Region: Poi_test2
Bounds (left top - right bottom) : 9.5407, 48.8079 NE - 9.5407, 48.8079 NE
Categories:
sustenance
pub
sport
10pin
table_soccer
Subtypes:
fax text
opening_hours text
pub text
phone text
website text
10pin text
name text
table_soccer text
wheelchair_yes  encoded 1
sustenance: pub Sportbar Kalaluna Lat 48.807945 Lon 9.540649 osmid=573347977  [ sport='10pin;table_soccer' ]  poi_additional:[ website='http://kalaluna.de'phone='+49 7181 64477'opening_hours='Mo-Tu 16:00-01:00, Fr 16:00-03:00, Sa 14:30-03:00, Su 15:00-01:00'fax='+49 7181 980394'wheelchair_yes='yes' ] 
sport: 10pin;table_soccer …
```
=> Support multivalued amenity

OsmAnd/src/net/osmand/plus/views/layers/PointLocationLayer.java
Use sequential loading for 3D-models
=> Fix concurrency while loading same 3D model

OsmAnd/src/net/osmand/plus/views/layers/PointLocationLayer.java
Use text size to scale location 3D model size
=> Use text size to scale location 3D model size

OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java, OsmAnd/src/net/osmand/plus/views/controls/maphudbuttons/Map3DButton.java
Reverts osmandapp/OsmAnd#20137
=> Revert "Add adjusted tilt angle to map 3D button"

OsmAnd/src/net/osmand/plus/views/layers/PointLocationLayer.java
Use shader to display heading sector for my location icon
=> Use map renderer to display heading sector

OsmAnd/src/net/osmand/plus/plugins/weather/WeatherPlugin.java, OsmAnd/src/net/osmand/plus/plugins/weather/WeatherRasterLayer.java, OsmAnd/src/net/osmand/plus/plugins/weather/dialogs/WeatherForecastFragment.java
Use proper parameters for weather forecast time period
=> Fix weather forecast time periods

OsmAnd/src/net/osmand/plus/plugins/weather/WeatherPlugin.java, OsmAnd/src/net/osmand/plus/plugins/weather/WeatherRasterLayer.java, OsmAnd/src/net/osmand/plus/plugins/weather/dialogs/WeatherForecastFragment.java
Use properly set animation period for weather forecasts
=> Fix weather animation period

OsmAnd/src/net/osmand/plus/utils/NativeUtilities.java, OsmAnd/src/net/osmand/plus/views/AutoZoomBySpeedHelper.java
Use proper terrain elevation values when zooming during navigation
=> Fix too close view during autozoom on relief

OsmAnd-java/src/main/java/net/osmand/search/core/SearchCoreFactory.java
To issue https://github.com/osmandapp/OsmAnd/issues/20256
=> Search. Fix brands in categories

OsmAnd/src/net/osmand/plus/routing/RoutingHelper.java, OsmAnd/src/net/osmand/plus/routing/RoutingHelperUtils.java, OsmAnd/src/net/osmand/plus/views/layers/PointLocationLayer.java, OsmAnd/src/net/osmand/plus/views/layers/RouteLayer.java
Use track direction to display correct marker bearing during navigation
=> Display correct arrow direction during navigation

OsmAnd/res/values/strings.xml, OsmAnd/res/xml/development_settings.xml, OsmAnd/src/net/osmand/plus/plugins/development/DevelopmentSettingsFragment.java
https://forum.developer.samsung.com/t/charging-current-battery-property-current-now/13517
=> Implement AUTO_DETECT_MICROAMPERES (energy stats)

OsmAnd-java/src/main/java/net/osmand/binary/BinaryMapPoiReaderAdapter.java
To issue https://github.com/osmandapp/OsmAnd/issues/16397
=> Do not show top_index in additional amenity tags

OsmAnd/src/net/osmand/plus/mapcontextmenu/MapContextMenuFragment.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/cards/NoImagesCard.java, OsmAnd/src/net/osmand/plus/utils/AndroidUtils.java, OsmAnd/src/net/osmand/plus/utils/UiUtilities.java, OsmAnd/src/net/osmand/plus/views/OsmandMap.java, OsmAnd/src/net/osmand/plus/views/layers/AidlMapLayer.java, OsmAnd/src/net/osmand/plus/views/layers/ContextMenuLayer.java, OsmAnd/src/net/osmand/plus/views/layers/MapTextLayer.java, OsmAnd/src/net/osmand/plus/views/layers/PointNavigationLayer.java, OsmAnd/src/net/osmand/plus/views/layers/base/OsmandMapLayer.java, OsmAnd/src/net/osmand/plus/views/layers/geometry/GeometryWayContext.java, OsmAnd/src/net/osmand/plus/views/layers/geometry/MultiColoringGeometryWayContext.java
Reverts osmandapp/OsmAnd#20242
=> Revert "test samsung dex"

OsmAnd-java/src/main/java/net/osmand/osm/MapPoiTypes.java, OsmAnd-java/src/main/java/net/osmand/search/core/SearchCoreFactory.java, OsmAnd-java/src/main/java/net/osmand/search/core/TopIndexFilter.java
To issue https://github.com/osmandapp/OsmAnd/issues/16397
=> Add lang support for top_index

OsmAnd-java/src/main/java/net/osmand/binary/BinaryMapPoiReaderAdapter.java
To issue https://github.com/osmandapp/OsmAnd/issues/8483
=> multivalue amenity, add other subtypes

OsmAnd-java/src/main/java/net/osmand/search/core/TopIndexFilter.java, OsmAnd/src/net/osmand/plus/poi/PoiFiltersHelper.java, OsmAnd/src/net/osmand/plus/poi/PoiUIFilter.java, OsmAnd/src/net/osmand/plus/search/dialogs/QuickSearchDialogFragment.java
Filter for issue https://github.com/osmandapp/OsmAnd/issues/16397
=> Filter for top_index search

OsmAnd/src/net/osmand/plus/search/SearchUtils.java, OsmAnd/src/net/osmand/plus/search/dialogs/QuickSearchDialogFragment.java
To issue https://github.com/osmandapp/OsmAnd/issues/16397
=> Show on map for top_index search

OsmAnd-java/src/main/java/net/osmand/search/core/SearchCoreFactory.java
Fix duplicates in brand search, if brand present in different maps
=> Fix duplicates

OsmAnd/src/net/osmand/plus/utils/NativeUtilities.java, OsmAnd/src/net/osmand/plus/views/AutoZoomBySpeedHelper.java
Avoid unnecessary reading of heightmap geotiffs
=> Fix crash during heights calculations

OsmAnd/src/net/osmand/plus/wikivoyage/data/TravelDbHelper.java, OsmAnd/src/net/osmand/plus/wikivoyage/data/TravelHelper.java, OsmAnd/src/net/osmand/plus/wikivoyage/data/TravelObfHelper.java, OsmAnd/src/net/osmand/plus/wikivoyage/search/WikivoyageSearchHelper.java
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/1164
=> Fix Wikiwoyage searching

OsmAnd-java/src/main/java/net/osmand/router/network/NetworkRouteContext.java
To issue https://github.com/osmandapp/OsmAnd/issues/20122
=> Support live updates in network route selector

OsmAnd-java/src/main/java/net/osmand/router/RouteResultPreparation.java
https://osmand.net/map/navigate/?start=50.458071,30.526215&end=50.458368,30.526838&profile=car#19/50.45917/30.52521
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/2630
=> Fix turn lanes. Fix active turn lanes index

OsmAnd-java/src/main/java/net/osmand/router/RouteResultPreparation.java
https://osmand.net/map/navigate/?start=50.424255,30.564373&end=50.423975,30.558493&profile=car#16/50.4262/30.5501
=> Fix turn lanes on Y-intersection

OsmAnd-java/src/main/java/net/osmand/search/core/SearchCoreFactory.java
Brand _Starbucks_ wasn't search in South Korea
=> Fix brand searching

OsmAnd-java/src/main/java/net/osmand/search/core/SearchCoreFactory.java
Fix searching for similar words:
Superman
Super
中国邮政储蓄银行
中国邮政
=> Fix brand searching with similar words

OsmAnd-java/src/main/java/net/osmand/render/RenderingRule.java, OsmAnd-java/src/main/java/net/osmand/render/RenderingRuleSearchRequest.java, OsmAnd-java/src/main/java/net/osmand/render/RenderingRuleStorageProperties.java, OsmAnd-java/src/main/java/net/osmand/render/RenderingRulesStorage.java
Support associations in map styles for legacy renderer
=> Support associations in map styles

README.md
follow-up on https://github.com/osmandapp/OsmAnd/pull/20567
=> Link from README to technical docs

OsmAnd-java/src/main/java/net/osmand/router/RouteResultPreparation.java
To issue https://github.com/osmandapp/OsmAnd/issues/20524
Tests https://github.com/osmandapp/OsmAnd-resources/pull/1107
=> Check keep instruction after merge turn lanes

OsmAnd/src/net/osmand/plus/poi/NominatimPoiFilter.java, OsmAnd/src/net/osmand/plus/poi/PoiUIFilter.java, OsmAnd/src/net/osmand/plus/search/dialogs/QuickSearchDialogFragment.java
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/2650
=> Fix show on map for brands

OsmAnd-java/src/main/java/net/osmand/gpx/ElevationApproximator.java
[…ll calculation](https://github.com/osmandapp/OsmAnd-iOS/issues/3865)
=> Fix https://github.com/osmandapp/OsmAnd-iOS/issues/3865 bug with uphill

OsmAnd/res/values/strings.xml, OsmAnd/res/xml/development_settings.xml, OsmAnd/src/net/osmand/plus/auto/SurfaceRenderer.java, OsmAnd/src/net/osmand/plus/plugins/development/DevelopmentSettingsFragment.java, OsmAnd/src/net/osmand/plus/plugins/development/OsmandDevelopmentPlugin.java, OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java, OsmAnd/src/net/osmand/plus/views/MapViewWithLayers.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Use development setting to apply battery saving mode
=> Allow using battery saving mode

OsmAnd/src/net/osmand/plus/views/layers/geometry/GeometryWay.java, OsmAnd/src/net/osmand/plus/views/layers/geometry/GeometryWayDrawer.java, OsmAnd/src/net/osmand/plus/views/layers/geometry/GeometryWayPathAlgorithms.java
Use partial track drawing to improve power efficiency
=> Use partial track drawing

OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Disable two-fingers tap during short multitouch gestures
=> Fix two-fingers tap while zooming

OsmAnd/src/net/osmand/plus/views/MultiTouchSupport.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Perform smooth animations for map scrolling and zooming gestures
=> Use smooth animations for drag and pinch gestures

OsmAnd/src/net/osmand/plus/views/layers/geometry/GeometryWay.java
Use correct start point for navigation route
=> Fix far start of navigation route

OsmAnd-java/src/main/java/net/osmand/NativeLibrary.java, OsmAnd-java/src/main/java/net/osmand/data/Amenity.java, OsmAnd/src/net/osmand/core/android/MapRendererContext.java
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/2393
=> Fix retreive data for polygon UI Android

OsmAnd/src/net/osmand/plus/views/layers/geometry/GeometryWay.java
Use previous point in navigation route
=> Fix starting distance after renderer reinit

OsmAnd-java/src/main/java/net/osmand/NativeLibrary.java, OsmAnd-java/src/main/java/net/osmand/data/Amenity.java, OsmAnd-java/src/main/java/net/osmand/data/QuadRect.java, OsmAnd/src/net/osmand/core/android/MapRendererContext.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/MenuBuilder.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/AmenityMenuBuilder.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/RenderedObjectMenuBuilder.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/controllers/RenderedObjectMenuController.java
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/2393
=> Retrieve amenity for rendering polygon

OsmAnd-java/src/main/java/net/osmand/NativeLibrary.java
Use native function to read geotiffs
=> Add native function to read geotiffs

OsmAnd/src/net/osmand/core/android/MapRendererContext.java
To issue https://github.com/osmandapp/OsmAnd/issues/20938
=> Avoid osmand_change:delete in within polygons

OsmAnd/src/net/osmand/plus/views/layers/geometry/GeometryWay.java
Correct distance calculation for coloured route during navigation
=> Fix gaps in gradient route during navigation

OsmAnd/src/net/osmand/plus/plugins/weather/dialogs/WeatherLayerFragment.java
Reverts osmandapp/OsmAnd#21013
=> Revert "Fixed update display slider value on slider drag selecting weather tr…"

OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/EditorFragment.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/icon/EditorIconController.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/icon/EditorIconUtils.java, OsmAnd/src/net/osmand/plus/myplaces/tracks/filters/FilterParamsAdapter.kt, OsmAnd/src/net/osmand/plus/plugins/monitoring/MonitoringSettingsFragment.java, OsmAnd/src/net/osmand/plus/quickaction/MapButtonIconController.java, OsmAnd/src/net/osmand/plus/track/cards/InfoCard.java, OsmAnd/src/net/osmand/plus/track/cards/OverviewCard.java, OsmAnd/src/net/osmand/plus/track/fragments/controller/SelectRouteActivityController.java, OsmAnd/src/net/osmand/plus/utils/AndroidUtils.java
We should merge this request before merging of https://github.com/osmandapp/OsmAnd-resources/pull/1147 to escape problems with changed icon names support.
=> Add category "Activity" on the icons palette (fix #20538)

OsmAnd/src/net/osmand/plus/auto/SurfaceRenderer.java
Enable battery saving mode while using Android Auto
=> Enable battery saving mode in Android Auto

OsmAnd/src/net/osmand/plus/views/mapwidgets/WidgetType.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/banner/WidgetPromoBanner.java
[ios issue](https://github.com/osmandapp/OsmAnd-Issues/issues/2658)
[ios pr](https://github.com/osmandapp/OsmAnd-iOS/pull/4057)
video after:
https://github.com/user-attachments/assets/339fc210-3a0c-49f7-89ce-944fba94b239
=> altitude pro widget

OsmAnd/src/net/osmand/plus/search/listitems/QuickSearchListItem.java
Fix to issue https://github.com/osmandapp/OsmAnd-Issues/issues/2751#issuecomment-2434925582
=> Fix duplications

OsmAnd-java/src/main/java/net/osmand/router/RouteSegmentResult.java
To issue https://github.com/osmandapp/OsmAnd/issues/18180
=> Fix destination description in turn instructions

OsmAnd-java/src/main/java/net/osmand/CollatorStringMatcher.java, OsmAnd-java/src/main/java/net/osmand/binary/GeocodingUtilities.java
To issue https://github.com/osmandapp/OsmAnd/issues/19290 (fix partially Flowers instead Clayton)
To issue https://github.com/osmandapp/OsmAnd/issues/20045
=> Fix geocoding sorting

OsmAnd-java/src/main/java/net/osmand/router/RouteResultPreparation.java, OsmAnd-java/src/main/java/net/osmand/router/RoutingConfiguration.java, OsmAnd/src/net/osmand/plus/routing/RouteProvider.java, OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java
To issue https://github.com/osmandapp/OsmAnd/issues/19065#issuecomment-2321211820
=> Add setting show minor turns

OsmAnd/src/net/osmand/plus/auto/screens/BaseAndroidAutoScreen.kt, OsmAnd/src/net/osmand/plus/auto/screens/RoutePreviewScreen.java, OsmAnd/src/net/osmand/plus/routepreparationmenu/MapRouteInfoMenu.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java, OsmAnd/src/net/osmand/plus/views/Zoom.java
Reverts osmandapp/OsmAnd#21242
=> Revert "Fix aa zoom"

OsmAnd/src/net/osmand/plus/auto/TripHelper.java
Reverts osmandapp/OsmAnd#21244
=> Revert "Try to fix nextDirInfo for AA"

OsmAnd/src/net/osmand/plus/measurementtool/MeasurementToolLayer.java, OsmAnd/src/net/osmand/plus/views/layers/GPXLayer.java, OsmAnd/src/net/osmand/plus/views/layers/RouteLayer.java, OsmAnd/src/net/osmand/plus/views/layers/geometry/MultiColoringGeometryWay.java
Don't rebuild vector lines when thack changes applied
=> Fix blinking track while recording

OsmAnd/src/net/osmand/plus/views/layers/MapSelectionHelper.java
To issue https://github.com/osmandapp/OsmAnd/issues/8159
=> Support osmand_poi_lat_lon tag

OsmAnd/src/net/osmand/plus/views/layers/MapSelectionHelper.java
To issue https://github.com/osmandapp/OsmAnd/issues/8159
Related PR https://github.com/osmandapp/OsmAnd/pull/21341
=> Fix osmand_poi_lat_lon parsing

OsmAnd/src/net/osmand/core/android/MapRendererContext.java, OsmAnd/src/net/osmand/plus/auto/SurfaceRenderer.java, OsmAnd/src/net/osmand/plus/views/MapViewWithLayers.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java, OsmAnd/src/net/osmand/plus/views/corenative/NativeCoreContext.java
Use already initialized OpenGL renderer when switching to and from Android Auto
=> Support fast switching to and from Android Auto

OsmAnd/src/net/osmand/plus/configmap/tracks/TrackSortModesHelper.java
It is not allowed to store "null" keys and values in ConcurrentHashMap
=> Fix crash after remove Tracks Folder

OsmAnd-java/src/main/java/net/osmand/osm/OsmRouteType.java
Reverts osmandapp/OsmAnd#21595
=> Revert "Fix OsmRouteType for route_piste (OSM ski routes)"

OsmAnd-java/src/main/java/net/osmand/router/MissingMapsCalculator.java
To issue https://github.com/osmandapp/OsmAnd-iOS/issues/4227
=> Fix MissingMapsCalculator

OsmAnd-java/src/main/java/net/osmand/gpx/GpxParameter.java, OsmAnd-shared/src/commonMain/kotlin/net/osmand/shared/gpx/GpxDatabase.kt, OsmAnd-shared/src/commonMain/kotlin/net/osmand/shared/gpx/GpxDbUtils.kt, OsmAnd-shared/src/commonMain/kotlin/net/osmand/shared/gpx/GpxParameter.kt, OsmAnd-shared/src/commonMain/kotlin/net/osmand/shared/gpx/GpxTrackAnalysis.kt
[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3956)
video before:
https://github.com/user-attachments/assets/2ec3f072-a865-4eb9-b7a5-ebefa7341a8c
video after:
https://github.com/user-attachments/assets/7950f394-6c26-47a9-8f81-9e12c3f49133
=> add EXPECTED_DURATION field to db

OsmAnd-java/src/main/java/net/osmand/gpx/GpxParameter.java, OsmAnd-shared/src/commonMain/kotlin/net/osmand/shared/gpx/GpxDatabase.kt, OsmAnd-shared/src/commonMain/kotlin/net/osmand/shared/gpx/GpxDbUtils.kt, OsmAnd-shared/src/commonMain/kotlin/net/osmand/shared/gpx/GpxParameter.kt, OsmAnd-shared/src/commonMain/kotlin/net/osmand/shared/gpx/GpxTrackAnalysis.kt
https://github.com/osmandapp/OsmAnd/pull/21700
=> cherry-pick pr from master to 4.9

OsmAnd-java/src/main/java/net/osmand/CollatorStringMatcher.java, OsmAnd-java/src/main/java/net/osmand/binary/GeocodingUtilities.java
To issue https://github.com/osmandapp/web/issues/650
=> Fix geocoding

OsmAnd-java/src/main/java/net/osmand/osm/edit/OSMSettings.java, OsmAnd-java/src/main/java/net/osmand/osm/edit/OsmMapUtils.java, OsmAnd-java/src/main/java/net/osmand/util/JarvisAlgorithm.java
To issue https://github.com/osmandapp/OsmAnd/issues/21248
=> Jarvis algorithm and climbing

OsmAnd/src/net/osmand/core/android/MapRendererContext.java
To issue https://github.com/osmandapp/OsmAnd/issues/21248
=> Change tags for retrieved OpenGL polygons

OsmAnd/src/net/osmand/core/android/MapRendererContext.java
Reverts osmandapp/OsmAnd#21836
=> Revert "Change tags for retrieved OpenGL polygons"

OsmAnd/res/values/strings.xml, OsmAnd/res/xml/development_settings.xml, OsmAnd/src/net/osmand/plus/plugins/development/DevelopmentSettingsFragment.java, OsmAnd/src/net/osmand/plus/plugins/development/OsmandDevelopmentPlugin.java, OsmAnd/src/net/osmand/plus/views/MapViewWithLayers.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Enable showing grid on the map in development plugin settings
=> Enable map grid in development plugin

OsmAnd-java/src/main/java/net/osmand/CollatorStringMatcher.java
To issue https://github.com/osmandapp/OsmAnd/issues/11709
=> Fix arabic search

OsmAnd/src/net/osmand/plus/mapcontextmenu/controllers/RenderedObjectMenuController.java
To issue https://github.com/osmandapp/OsmAnd/issues/21248
=> Fix translation for objects from rendering layer

OsmAnd/src/net/osmand/plus/views/mapwidgets/widgets/SpeedometerWidget.java
To issue https://github.com/osmandapp/OsmAnd/issues/21521
=> Fix speed alarm

OsmAnd-java/src/main/java/net/osmand/binary/GeocodingUtilities.java
To issue https://github.com/osmandapp/OsmAnd/issues/20045
Related issue https://github.com/osmandapp/web/issues/650
=> Fix reverse address search

OsmAnd/src/net/osmand/plus/mapcontextmenu/editors/icon/EditorIconController.java
User complaints that after switching icon categories to POI categories we have lost some icons "Chappel, church, cathedral favorite icons disappeared"
=> Added Travel group as icon category

OsmAnd-java/src/test/java/net/osmand/router/RouteTestingTest.java, OsmAnd/res/values/strings.xml, OsmAnd/res/xml/development_settings.xml, OsmAnd/src/net/osmand/plus/plugins/development/DevelopmentSettingsFragment.java, OsmAnd/src/net/osmand/plus/plugins/development/OsmandDevelopmentPlugin.java, OsmAnd/src/net/osmand/plus/views/AutoZoomBySpeedHelper.java, OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Allow using different coordinate systems on geographic grids
=> Display labels on map grids

OsmAnd/src/net/osmand/plus/views/layers/geometry/GeometryWayDrawer.java, OsmAnd/src/net/osmand/plus/views/layers/geometry/GeometryWayStyle.java
https://github.com/osmandapp/OsmAnd/issues/21661
=> Fixed path splitting algorithm

OsmAnd-java/src/main/java/net/osmand/osm/MapPoiTypes.java, OsmAnd-java/src/main/java/net/osmand/osm/edit/OsmMapUtils.java
Related https://github.com/osmandapp/OsmAnd-tools/pull/1065
=> Support superroute

OsmAnd-java/src/main/java/net/osmand/CollatorStringMatcher.java, OsmAnd-java/src/main/java/net/osmand/binary/BinaryMapIndexReader.java, OsmAnd-java/src/main/java/net/osmand/binary/BinaryMapPoiReaderAdapter.java, OsmAnd-java/src/main/java/net/osmand/data/Amenity.java, OsmAnd/res/values/strings.xml, OsmAnd/src/net/osmand/plus/mapcontextmenu/MenuBuilder.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/SearchByRouteIdTask.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/MenuRowBuilder.java, OsmAnd/src/net/osmand/plus/resources/ResourceManager.java, OsmAnd/src/net/osmand/plus/views/layers/MapSelectionHelper.java, OsmAnd/src/net/osmand/plus/wikivoyage/data/TravelGpx.java, OsmAnd/src/net/osmand/plus/wikivoyage/data/TravelObfGpxFileReader.java
To issue https://github.com/osmandapp/OsmAnd/issues/16808 
Related multipolygons - searchRouteMembers (by "route_id")
Get parent route (part of) - searchRoutePartOf (find by "route_id")
Get members of route (superroute) - searchRouteMembers (by "route_members_ids")
=> [5.0] Multiple search route_members_ids. Search by route_id

OsmAnd/res/values/strings.xml, OsmAnd/src/net/osmand/core/android/MapRendererContext.java
Fix crash during creation of map presentation environment
=> Fix crash on map presentation environment creation

OsmAnd-java/src/main/java/net/osmand/OsmAndCollator.java
To issue https://github.com/osmandapp/OsmAnd/issues/11709
=> Sort search result using ArabicNormalizer

OsmAnd-java/src/main/java/net/osmand/search/core/SearchCoreFactory.java, OsmAnd/src/net/osmand/plus/utils/OsmAndFormatter.java
To issue https://github.com/osmandapp/OsmAnd/issues/16808
=> Fix name in history and search for empty route names

OsmAnd-java/src/main/java/net/osmand/data/Amenity.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/controllers/AmenityMenuController.java, OsmAnd/src/net/osmand/plus/search/listitems/QuickSearchListItem.java
_Route sub-type is missed in What's here menu_ from task https://github.com/osmandapp/OsmAnd/issues/16808
=> Add activity type

OsmAnd/src/net/osmand/plus/views/layers/MapSelectionHelper.java
To comment in issue https://github.com/osmandapp/OsmAnd/issues/21993#issuecomment-2815480777
=> Fix lags on click, fix multypolygon POI

OsmAnd/res/values/strings.xml
Group rendering_attr_hide* strings together in strings.xml and fix some of the value where *_name and *_description are swapped.
=> Group rendering_attr_hide* strings

OsmAnd-java/src/main/java/net/osmand/search/SearchUICore.java
To issue https://github.com/osmandapp/OsmAnd/issues/21993
=> Fix deduplication

OsmAnd/src/net/osmand/plus/ChartPointsHelper.java, OsmAnd/src/net/osmand/plus/plugins/aistracker/AisMessageListener.java, OsmAnd/src/net/osmand/plus/plugins/aistracker/AisMessageSimulationListener.java, OsmAnd/src/net/osmand/plus/plugins/aistracker/AisObject.java, OsmAnd/src/net/osmand/plus/plugins/aistracker/AisSimulationProvider.java, OsmAnd/src/net/osmand/plus/plugins/aistracker/AisTrackerLayer.java, OsmAnd/src/net/osmand/plus/plugins/aistracker/AisTrackerPlugin.java, OsmAnd/src/net/osmand/plus/utils/AndroidUtils.java
https://github.com/osmandapp/OsmAnd/issues/21559
=> Draw AIS icons using engine V2

OsmAnd-java/src/main/java/net/osmand/binary/BinaryMapIndexReader.java
To issue https://github.com/osmandapp/OsmAnd/issues/22445
=> [5.0] Fix crash

OsmAnd/src/net/osmand/plus/base/MapViewTrackingUtilities.java
https://github.com/osmandapp/OsmAnd/issues/22304
=> Correct camera azimuth depending on scale and elevation

OsmAnd/src/net/osmand/plus/plugins/aistracker/AisObject.java, OsmAnd/src/net/osmand/plus/plugins/aistracker/AisTrackerLayer.java
https://github.com/osmandapp/OsmAnd/issues/21559
=> Set min draw zoom for ais icons for Engine V2

OsmAnd/src/net/osmand/plus/base/MapViewTrackingUtilities.java
Reverts osmandapp/OsmAnd#22475
=> Revert "Correct camera azimuth depending on scale and elevation"

OsmAnd-java/src/main/java/net/osmand/wiki/WikiCoreHelper.java, OsmAnd-shared/src/androidMain/kotlin/net/osmand/shared/util/NetworkImageLoader.kt, OsmAnd/res/layout/gallery_card_item.xml, OsmAnd/src/net/osmand/plus/mapcontextmenu/MenuBuilder.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/gallery/GalleryPhotoViewerFragment.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/gallery/PhotoCacheManager.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/gallery/holders/GalleryImageHolder.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/gallery/tasks/CacheReadTask.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/gallery/tasks/CacheWriteTask.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/gallery/tasks/GetImageCardsTask.java
* show cached photos in offline mode
* code review fix
=> show cached photos in offline mode (#22489)

OsmAnd/src/net/osmand/plus/auto/SurfaceRenderer.java
https://github.com/osmandapp/OsmAnd/issues/22304
=> Fixed camera position in android auto

OsmAnd/src/net/osmand/plus/auto/SurfaceRenderer.java
https://github.com/osmandapp/OsmAnd/issues/22304
=> Fixed camera position for engine V1 in android auto

OsmAnd/src/net/osmand/plus/views/AnimateMapMarkersThread.java, OsmAnd/src/net/osmand/plus/views/MapViewWithLayers.java, OsmAnd/src/net/osmand/plus/views/OsmandMap.java
Proper transition of renderer back from Android Auto to device screen
=> Avoid ANR and crash in Android Auto

OsmAnd-java/src/main/java/net/osmand/data/BaseDetailsObject.java, OsmAnd-java/src/main/java/net/osmand/search/AmenitySearcher.java
=> Fix retrieving geometry

OsmAnd/res/values/strings.xml, OsmAnd/src/net/osmand/plus/base/BaseLoadAsyncTask.java, OsmAnd/src/net/osmand/plus/helpers/SearchHistoryHelper.java, OsmAnd/src/net/osmand/plus/settings/fragments/DeleteHistoryTask.java, OsmAnd/src/net/osmand/plus/settings/fragments/HistoryItemsFragment.java, OsmAnd/src/net/osmand/plus/settings/fragments/MarkersHistorySettingsFragment.java, OsmAnd/src/net/osmand/plus/settings/fragments/NavigationHistorySettingsFragment.java, OsmAnd/src/net/osmand/plus/settings/fragments/SearchHistorySettingsFragment.java
-async history deleting with progress dialog
=> fix #21456 ui freeze

OsmAnd-java/src/main/java/net/osmand/router/PrecalculatedRouteDirection.java
In issue https://github.com/osmandapp/OsmAnd-Issues/issues/3009
=> Add log for server

OsmAnd/src/net/osmand/plus/views/layers/MapMarkersLayer.java
https://github.com/osmandapp/OsmAnd/issues/22759
=> Used attached marker do draw distance lable on map markers layer

OsmAnd/src/net/osmand/plus/views/layers/GPXLayer.java, OsmAnd/src/net/osmand/plus/views/layers/base/OsmandMapLayer.java
- Tracks disappears after re-connecting to AA
=> fix #22526

OsmAnd/src/net/osmand/core/android/MapRendererContext.java, OsmAnd/src/net/osmand/plus/views/layers/POIMapLayer.java, OsmAnd/src/net/osmand/plus/views/layers/core/POITileProvider.java
Update POI symbols on the screen when ready
=> Separately renew POI symbols on the screen

OsmAnd/src/net/osmand/plus/download/ui/ItemViewHolder.java
=> Fix ##22766

OsmAnd/src/net/osmand/plus/routepreparationmenu/cards/RouteDirectionsCard.java, OsmAnd/src/net/osmand/plus/routing/RouteDirectionInfo.java, OsmAnd/src/net/osmand/plus/routing/RoutingHelperUtils.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/OutlinedTextContainer.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/widgets/NextTurnWidget.java, OsmAnd/src/net/osmand/plus/views/mapwidgets/widgets/SecondNextTurnWidget.java
-fix text crop/excessive padding
-use turn type instruction instead empty route description -fix additional empty space
=> fix #22666

OsmAnd-java/src/main/java/net/osmand/data/BaseDetailsObject.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/PlaceDetailsMenuBuilder.java, OsmAnd/src/net/osmand/plus/wikivoyage/data/TravelArticle.java, OsmAnd/src/net/osmand/plus/wikivoyage/data/TravelObfHelper.java
To issue https://github.com/osmandapp/OsmAnd/issues/22566
=> Fix Travel guides for cities

OsmAnd-java/src/main/java/net/osmand/search/core/SearchCoreFactory.java, OsmAnd-java/src/main/java/net/osmand/search/core/SearchPhrase.java, OsmAnd/src/net/osmand/plus/poi/PoiFiltersHelper.java
To issues https://github.com/osmandapp/OsmAnd/issues/22074 and https://github.com/osmandapp/OsmAnd/issues/22089
=> Synchronize search and show on map

OsmAnd-java/src/main/java/net/osmand/search/core/TopIndexFilter.java
To issue https://github.com/osmandapp/OsmAnd/issues/22855
=> Case insensitive brand search

OsmAnd-java/src/main/java/net/osmand/binary/RouteDataObject.java, OsmAnd-java/src/main/java/net/osmand/router/RouteResultPreparation.java, OsmAnd-java/src/main/java/net/osmand/router/RouteSegmentResult.java
https://github.com/osmandapp/OsmAnd/issues/22949
=> Improve DIST_BEARING_DETECT in splitRoadsAndAttachRoadSegments

OsmAnd-java/src/main/java/net/osmand/data/Amenity.java, OsmAnd-java/src/main/java/net/osmand/data/MapObject.java
https://github.com/osmandapp/OsmAnd/issues/22226
=> Use LinkedHashMap for names and poi-additionals

OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java
Statement is repeated just below
=> Remove obsolete line?

OsmAnd/src/net/osmand/plus/settings/backend/backup/GpxAppearanceInfo.java
https://github.com/osmandapp/OsmAnd-iOS/issues/4894
=> Hide new tag TAG_IS_JOIN_SEGMENTS (gpxAppearanceTags)

OsmAnd-java/src/main/java/net/osmand/search/AmenitySearcher.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/RenderedObjectMenuBuilder.java
To issue https://github.com/osmandapp/OsmAnd/issues/20153
=> Fix url for context menu

OsmAnd/src/net/osmand/plus/poi/PoiUIFilter.java
https://github.com/osmandapp/OsmAnd/issues/22226
=> Hotfix ConcurrentModificationException in currentSearchResult

OsmAnd-java/src/main/java/net/osmand/gpx/clickable/ClickableWayTags.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/controllers/AmenityMenuController.java, OsmAnd/src/net/osmand/plus/mapcontextmenu/controllers/NetworkRouteDrawable.java, OsmAnd/src/net/osmand/plus/search/listitems/QuickSearchListItem.java, OsmAnd/src/net/osmand/plus/track/clickable/ClickableWayHelper.java
https://github.com/osmandapp/OsmAnd/issues/22226
=> Implement shields (icons) for ClickableWay POI/GPX
